# Generated by Django 3.1.5 on 2021-01-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_person', '0007_auto_20210105_2032'),
        ('betik_app_staff', '0003_stafftypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Registration Number')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Finish Date')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Passive'), (3, 'Dismiss')], default=1, verbose_name='Status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staffs', to='betik_app_staff.departmentmodel', verbose_name='Department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='betik_app_person.naturalpersonmodel', verbose_name='Person')),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staffs', to='betik_app_staff.stafftypemodel', verbose_name='Staff Type')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staffs', to='betik_app_staff.titlemodel', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
    ]
