
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-26T12:09:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "96fe1bb3878ce6af05e83aad3f5a1ce2307f57f1",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
