name: Test PyPI install
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 3'

jobs:
  test-installation:
    name: Test PyPI install (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
    # avoid installing pre-releases of non-mesmer-openscmrunner packages
      run: |
        pip install --upgrade pip
        pip install mesmer-openscmrunner
        pip install mesmer-openscmrunner --pre --upgrade
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Test installation
      run: |
        python scripts/test-install.py
