
# This file was generated by '_versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-27T13:02:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "16d60b16da75b347cf0891b51a1d1d03f93739cc",
 "version": "1.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
