[tool.poetry]
name = "ingeniiadfg"
version = "0.1.5"
description = "Generate Azure Data Factory objects from configuration"
authors = ["Greg Atkins <greg@ingenii.dev>"]
readme = "README.md"

[tool.poetry.scripts]
ingeniiadfg = "ingeniiadfg.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4.0"}
deepdiff = "5.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
