[tool.poetry]
authors = ["guyskk <guyskk@qq.com>"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
]
description = "EZTea Web Framework"
keywords = ["web", "framework", "development"]
license = "MIT"
name = "eztea"
readme = "README.md"
repository = "https://github.com/guyskk/eztea"
version = "0.1.1"

[[tool.poetry.source]]
default = true
name = "douban"
url = "https://pypi.doubanio.com/simple/"

[tool.poetry.scripts]
eztea = 'eztea.__main__:main'

[tool.poetry.dependencies]
alembic = {version = ">=1.7.5", optional = true}
black = {version = ">=21.12b0", optional = true}
ciso8601 = ">=2.2.0"
click = {version = ">=7.1.2", optional = true}
falcon = ">=3.0.1"
mako = {version = ">=1.1.6", optional = true}
psycopg2 = {version = ">=2.9.3", optional = true}
pymysql = {version = ">=1.0.2", optional = true}
python = ">=3.7.4,<4.0"
python-dateutil = {version = ">=2.8.2", optional = true}
python-dotenv = ">=0.12.0"
sqlalchemy = ">=1.3.19"
sqlalchemy-jsonfield = ">=1.0.0"
sqlalchemy-utc = ">=0.14.0"
sqlalchemy-utils = ">=0.38.2"
validr = ">=1.2.1"

[tool.poetry.extras]
migration = [
  "alembic",
  "black",
  "click",
  "mako",
  "python-dateutil",
]
mysql = ["pymysql"]
postgresql = ["psycopg2"]

[tool.poetry.dev-dependencies]
coverage = "==6.2"
flake8 = "==4.0.1"
isort = "==5.10.1"
pip-tools = "==6.4.0"
pycodestyle = "==2.8.0"
pytest = "==6.2.5"
pytest-cov = "==3.0.0"
pytest-env = "==0.6.2"
tox = "==3.24.5"
gunicorn = "==20.1.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
