name: dqsegdb2
channels:
  - conda-forge
dependencies:
  # build
  - pip
  - setuptools
  - setuptools-scm
  - wheel
  # install
  - igwn-auth-utils
  - ligo-segments
  - requests
  - safe-netrc
  # docs
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinx-tabs
