
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-01T10:02:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4e3bf8aab2e377732e9167a1b1ccd09764e6827",
 "version": "0.9.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
