[tool.poetry]
name = "acl_mngt"
version = "0.1.6"
description = "Parse acl config as string, generate vendor specific config."
authors = ["Teun Ouwehand <teun@nextpertise.nl>"]
repository = "https://github.com/Nextpertise/acl_mngt/"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pylint = "^2.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
