[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cef_logger"
authors = [{name = "Alexander Morokov", email = "morocov.ap.muz@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dynamic = ["version", "description"]
dependencies = [
    "pydantic >=1.6.1, <2.0.0",
]
requires-python = ">=3.6.0"

[project.urls]
Home = "https://github.com/delatars/cef_logger"

[project.optional-dependencies]
test = [
    "pytest >=5.4.3,<6.0.0",
    "flake8 >=3.9.2,<4.0.0",
    "flake8-bugbear >=0.11.1,<0.12.0",
    "flake8-builtins >=1.5.3,<2.0.0",
    "flake8-comprehensions >=3.7.0,<4.0.0",
    "flake8-debugger >=3.2.1,<4.0.0",
    "flake8-isort >=3.0.1,<4.0.0",
    "flake8-logging-format >=0.6.0,<0.7.0",
    "flake8-mutable >=1.2.0,<2.0.0",
    "flake8-pep3101 >=1.3.0,<2.0.0",
    "flake8-print >=3.1.4,<4.0.0",
    "flake8-quotes >=3.3.1,<4.0.0",
    "flake8-string-format >=0.3.0,<0.4.0",
    "mypy >=0.910,<1.0",
    "isort >=4.3.21,<5.0.0",
]
