---
repos:
    - repo: https://github.com/markdownlint/markdownlint
      rev: v0.11.0
      hooks:
          - id: markdownlint
    # NOTE: See also .mdlrc and .mdlstyle.rb files
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.3
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.29.0
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.6.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.1.0
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/psf/black
      rev: 21.9b0
      hooks:
          - id: black
            args: [--safe]
            language_version: python3.9
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-implicit-str-concat == 0.2.0
                - flake8-bugbear == 21.9.2
            language_version: python3.9
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: fix-byte-order-marker
          - id: check-docstring-first
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: debug-statements
          - id: check-yaml
          - id: check-toml
