
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-26T16:36:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6f2884c33cf5df93b660043c81989804fef0f0a",
 "version": "1.0.0-rc.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
