
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-25T16:36:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9dfb3f95c8fa0b6c24f798baeb25c28397ec1506",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
