
[".editorconfig"]
root = true

[".editorconfig"."*"]
end_of_line = "lf"
charset = "utf-8"
indent_style = "space"
indent_size = 2
trim_trailing_whitespace = true
insert_final_newline = true

[".editorconfig"."*.py"]
indent_size = 4

[".editorconfig".Makefile]
indent_style = "tab"

[".editorconfig"."*.md"]
trim_trailing_whitespace = false

[".editorconfig"."*.sh"]
indent_style = "tab"
