
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T18:19:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2a945423f9fd410b9761d93d9d088da0ba53a03",
 "version": "2022.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
