
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-29T15:51:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "86f86199ebff8070c394da65acc92e14c15172d3",
 "version": "6.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
