[tool.poetry]
name = "flask-siwe-auth"
version = "0.1.0"
description = "Custom Flask authentication using Sign-In with Ethereum (EIP-4361), a custom wallet user model, and authorization via on-chain attributes."
license = "MIT"
authors = ["Payton Garland <payton.r.g@gmail.com>"]
packages = [
    { include = "siwe_auth" }
]
readme = "README.md"
repository = "https://github.com/payton/flask-siwe-auth"
keywords = ["SIWE", "EIP-4361", "Sign-In with Ethereum", "Flask", "Web3", "Authentication", "Authorization"]

[tool.poetry.dependencies]
python = "^3.8"
web3 = "^5.26.0"
siwe = "^0.1.2"
pytz = "^2021.3"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pytest = "^6.2.5"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
