[tool.poetry]
name = "UploadgramPyAPI"
version = "1.6"
description = "This API can upload, download, remove and rename any files from the service uploadgram.me"
authors = ["tankalxat34"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
