[tool.poetry]
name = "rich-cli"
version = "1.0.0"
description = "Command Line Interface to Rich"
authors = ["Will McGugan <willmcgugan@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
rich = "^11.0.0"
click = "^8.0.0"
requests = "^2.0.0"

[tool.poetry.dev-dependencies]
black = "21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rich = 'rich_cli.__main__:run'

[tool.poetry.plugins."pipx.run"]
rich-cli = 'rich_cli.__main__:run'
