
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-30T22:53:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "da53fe8ddc61a95894cf17b48d24ccb4139e7bb5",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
