
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T08:30:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "43a1200d00df8a397e8a94387b29957f6ec24898",
 "version": "0.9.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
