[tool.poetry]
name = "holeysheet"
version = "0.1.2"
description = ""
authors = ["Nico Ekkart <nekkart@crunchanalytics.be>"]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^6.0"
pydantic = "^1.8.2"
pylightxl = "^1.58"
xlrd = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
