# Generated by Django 3.1.5 on 2021-05-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0011_dismissstafflogmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dismissstafflogmodel',
            options={'verbose_name': 'Dismiss Staff Log', 'verbose_name_plural': 'Dismiss Staff Logs'},
        ),
    ]
