language: python
cache: pip
os: linux
dist: bionic # OS+dist should be kept in sync with Dockerfile
env:
  global: # MongoDB version should be kept in sync with docker-compose image
    - MONGODB=4.4.0
jobs:
  include:
    - python: pypy3
      env: TOX_ENV=pypy3-pymongo-pyexecjs
    - python: 3.6
      env: TOX_ENV=py36-pymongo-pyexecjs
    - python: 3.7
      env: TOX_ENV=py37-pymongo-pyexecjs
    - python: 3.8
      env: TOX_ENV=py38-pymongo-pyexecjs
    - python: 3.9
      env: TOX_ENV=py39
    - python: 3.9
      env: TOX_ENV=py39-pymongo
    - python: 3.9
      env: TOX_ENV=py39-pyexecjs
    - python: 3.9
      env: TOX_ENV=py39-pymongo361-pyexecjs
    - python: 3.9
      env: TOX_ENV=py39-pymongo-pyexecjs
    - python: 3.9
      env: TOX_ENV=pep8
    - python: 3.9
      env: TOX_ENV=pylint
    - python: 3.9
      env: TOX_ENV=mypy
script:
  - tox -e $TOX_ENV
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "sudo apt-get update"
  - "sudo apt-get install libcurl3 -y"
before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/mongodb.log --fork
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
after_script:
  - pkill mongod
install:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-ubuntu1604-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongod --version
  - pip install tox
deploy:
  provider: pypi
  username: vmalloc
  distributions: "bdist_wheel sdist"
  password:
    secure: sNOkUNFfWKGsRy4BI+1jyqycZGSMiXTLtpCrX1mTuvjddbndULrHL3ecIPsCno49/nPR4Gww+e9U3HXc8LKJ9qR4mJ8bVCNiHO5GlGVnpV+wdGh9LVnsU1LWwuD8uWlLyTSOKP+ZmerCw7tGACYiv0e9zp8SqZXCH6VS+sAGFxU=
  on:
    tags: true
    all_branches: true
    repo: mongomock/mongomock
