name: morphodynamics
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - jupyterlab=3.2
  - ipywidgets
  - pip
  - ipympl
  - python-graphviz
  - pip:
    - cellpose
    - morphodynamics
    - bokeh>=0.13.0    