CACHES:
    default:
        BACKEND: redis_cache.RedisCache
        LOCATION: redis://cache:6379
        OPTIONS:
            DB: 1
            PARSER_CLASS: redis.connection.HiredisParser

DATABASES:
    default:
        ENGINE: django.db.backends.postgresql_psycopg2
        HOST: db
        PORT: 5432

CELERY_BROKER_URL: redis://cache:6379/0

# Disable some security headers, because they are already added by NGINX
# Disable X-Content-Type-Options
SECURE_CONTENT_TYPE_NOSNIFF: false

# Disable X-XSS-Protection
SECURE_BROWSER_XSS_FILTER: false

# Disable X-Frame-Options (Clickjacking protection)
CA_ENABLE_CLICKJACKING_PROTECTION: false
