[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["gwdatafind"]

[tool.pytest.ini_options]
addopts = "-r a --color=yes"
filterwarnings = [
	"error",
]
