
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T11:12:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e2fa86abcf6e775d1acea1b85fe44d15ff57387",
 "version": "0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
