
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-28T23:20:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccd315e00b3095f54fe5048584e6ac3fe1d5f18e",
 "version": "1.32.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
