
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T00:05:15+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b68913d5c28c4d5566748d9b7a75f712c3b49fe5",
 "version": "2.0.7-2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
