locators:
  inclusions:
    -
  exclusions:
    -
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: phone
    locators:
      - mode: id
        value: ltkpopup-phone
        index: 0
        uses: 54
  - verb: click
    name: submit
    locators:
      - mode: id
        value: ltkpopup-submit
        index: 0
        uses: 89
