
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T16:50:49-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b6dca06455c7092ae36bf7c423ca100ce4a6d76",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
