# Generated by Django 3.1.5 on 2021-05-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0007_passivereasonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveStaffEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passive_events', to='betik_app_staff.passivereasonmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_events', to='betik_app_staff.staffmodel')),
            ],
            options={
                'verbose_name': 'Passive Staff Event',
                'verbose_name_plural': 'Passive Staff Events',
            },
        ),
    ]
