# Generated by Django 3.1.5 on 2021-05-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0009_auto_20210513_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissReasonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dismiss Reason',
                'verbose_name_plural': 'Dismiss Reasons',
            },
        ),
    ]
