# Generated by Django 3.1.5 on 2021-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0012_auto_20210514_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveReasonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Active Reason',
                'verbose_name_plural': 'Active Reasons',
            },
        ),
    ]
