# Generated by Django 3.1.5 on 2021-10-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0013_activereasonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStaffLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dismiss_logs', to='betik_app_staff.activereasonmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_logs', to='betik_app_staff.staffmodel')),
            ],
            options={
                'verbose_name': 'Active Staff Log',
                'verbose_name_plural': 'Active Staff Logs',
            },
        ),
    ]
