# Generated by Django 3.1.5 on 2021-10-21 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0014_activestafflogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHolidayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='the start date the bank holiday becomes official')),
                ('finish_date', models.DateField(blank=True, help_text='the date of the abolition of the bank holiday', null=True)),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
