# Generated by Django 3.1.5 on 2021-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0015_bankholidaymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='the first day of holiday')),
                ('finish_date', models.DateField(help_text='one day after the last day of holiday')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='holidaymodel',
            index=models.Index(fields=['start_date', 'finish_date'], name='betik_app_s_start_d_38583a_idx'),
        ),
    ]
