# Generated by Django 3.1.5 on 2021-10-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0016_auto_20211022_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('monday', models.JSONField(blank=True, null=True)),
                ('tuesday', models.JSONField(blank=True, null=True)),
                ('wednesday', models.JSONField(blank=True, null=True)),
                ('thursday', models.JSONField(blank=True, null=True)),
                ('friday', models.JSONField(blank=True, null=True)),
                ('saturday', models.JSONField(blank=True, null=True)),
                ('sunday', models.JSONField(blank=True, null=True)),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_days', to='betik_app_staff.stafftypemodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='businessdaymodel',
            index=models.Index(fields=['start_date', 'finish_date', 'staff_type'], name='betik_app_s_start_d_58ee2a_idx'),
        ),
    ]
