# Generated by Django 3.1.5 on 2021-10-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0017_auto_20211022_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeaveRuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('periods', models.JSONField()),
                ('duration_type', models.PositiveIntegerField(choices=[(1, 'Day'), (2, 'Business Day')])),
                ('forward_next_year', models.BooleanField()),
                ('forward_year', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_leave_rules', to='betik_app_staff.stafftypemodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='annualleaverulemodel',
            index=models.Index(fields=['start_date', 'finish_date', 'staff_type'], name='betik_app_s_start_d_bf4e6d_idx'),
        ),
    ]
