# Generated by Django 3.1.5 on 2021-10-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0018_auto_20211024_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
