# Generated by Django 3.1.5 on 2021-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0019_leavetypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('business_days', models.JSONField()),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('period_duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='shiftrulemodel',
            index=models.Index(fields=['start_date', 'finish_date'], name='betik_app_s_start_d_2cb96b_idx'),
        ),
    ]
