# Generated by Django 3.1.5 on 2021-11-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0020_auto_20211102_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRuleStaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_no', models.PositiveIntegerField()),
                ('shift_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='betik_app_staff.shiftrulemodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betik_app_staff.staffmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shiftrulestaffmodel',
            constraint=models.UniqueConstraint(fields=('shift_rule', 'staff'), name='staff_in_shift_rule'),
        ),
    ]
