# Generated by Django 3.1.5 on 2021-11-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0021_auto_20211116_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrulestaffmodel',
            name='shift_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_staffs', to='betik_app_staff.shiftrulemodel'),
        ),
    ]
