# Generated by Django 3.1.5 on 2021-11-17 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0022_auto_20211116_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualShiftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('finish_dt', models.DateTimeField()),
                ('work_hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('type', models.PositiveIntegerField(choices=[(1, 'Overtime Shift'), (2, 'Weekend Shift'), (3, 'Holiday Shift'), (4, 'Exchange Shift')])),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_shifts', to='betik_app_staff.staffmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='individualshiftmodel',
            index=models.Index(fields=['start_dt', 'staff'], name='betik_app_s_start_d_912101_idx'),
        ),
        migrations.AddIndex(
            model_name='individualshiftmodel',
            index=models.Index(fields=['staff'], name='betik_app_s_staff_i_0fd6ab_idx'),
        ),
    ]
