# Generated by Django 3.1.5 on 2021-11-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0023_auto_20211117_1354'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='individualshiftmodel',
            name='betik_app_s_start_d_912101_idx',
        ),
        migrations.AddIndex(
            model_name='individualshiftmodel',
            index=models.Index(fields=['finish_dt', 'staff'], name='betik_app_s_finish__4ec405_idx'),
        ),
    ]
