# Generated by Django 3.1.5 on 2021-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0024_auto_20211119_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdaymodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
