# Generated by Django 3.1.5 on 2021-12-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0025_businessdaymodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('finish_dt', models.DateTimeField()),
                ('work_start_dt', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('duration_type', models.PositiveIntegerField(choices=[(3, 'Hour'), (4, 'Week'), (1, 'Day'), (2, 'Business Day'), (5, 'Month'), (6, 'Year')])),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betik_app_staff.leavetypemodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='betik_app_staff.staffmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='staffleavemodel',
            index=models.Index(fields=['start_dt', 'staff', 'leave_type'], name='betik_app_s_start_d_b2ceba_idx'),
        ),
    ]
