# Generated by Django 3.1.5 on 2021-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0026_auto_20211201_1326'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffleavemodel',
            index=models.Index(fields=['start_dt', 'finish_dt', 'staff', 'leave_type'], name='betik_app_s_start_d_1051ba_idx'),
        ),
    ]
