# Generated by Django 3.1.5 on 2021-12-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0027_auto_20211202_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrulestaffmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_staffs', to='betik_app_staff.staffmodel'),
        ),
    ]
