# Generated by Django 3.1.5 on 2021-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0028_auto_20211204_1941'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shiftrulestaffmodel',
            index=models.Index(fields=['shift_rule', 'staff', 'shift_no'], name='betik_app_s_shift_r_199b52_idx'),
        ),
    ]
