# Generated by Django 3.1.5 on 2021-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0029_auto_20211204_1958'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='individualshiftmodel',
            name='betik_app_s_staff_i_0fd6ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='individualshiftmodel',
            name='betik_app_s_finish__4ec405_idx',
        ),
        migrations.AddIndex(
            model_name='individualshiftmodel',
            index=models.Index(fields=['start_dt', 'finish_dt', 'staff'], name='betik_app_s_start_d_68a834_idx'),
        ),
        migrations.AddIndex(
            model_name='individualshiftmodel',
            index=models.Index(fields=['start_dt', 'staff'], name='betik_app_s_start_d_912101_idx'),
        ),
    ]
