# Generated by Django 3.1.5 on 2021-12-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0030_auto_20211204_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('finish_dt', models.DateTimeField()),
                ('work_hour', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField(choices=[(1, 'Overtime Shift'), (2, 'Weekend Shift'), (3, 'Holiday Shift'), (4, 'Normal Shift')])),
                ('in_dt', models.DateTimeField(blank=True, null=True)),
                ('out_dt', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='betik_app_staff.staffmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='workinghourmodel',
            index=models.Index(fields=['start_dt', 'finish_dt', 'staff'], name='betik_app_s_start_d_2baf99_idx'),
        ),
        migrations.AddIndex(
            model_name='workinghourmodel',
            index=models.Index(fields=['start_dt', 'staff'], name='betik_app_s_start_d_4a234b_idx'),
        ),
    ]
