# Generated by Django 3.1.5 on 2021-12-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0031_auto_20211206_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualshiftmodel',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Overtime Shift'), (2, 'Weekend Shift'), (3, 'Holiday Shift'), (4, 'Normal Shift')]),
        ),
    ]
