# Generated by Django 3.1.5 on 2021-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0032_auto_20211206_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghourmodel',
            name='late_minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
