# Generated by Django 3.1.5 on 2021-12-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0033_workinghourmodel_late_minute'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workinghourmodel',
            index=models.Index(fields=['start_dt', 'late_minute'], name='betik_app_s_start_d_0b15a3_idx'),
        ),
    ]
