# Generated by Django 3.1.5 on 2021-12-11 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0038_auto_20211211_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='passivereasonmodel',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passivereasonmodel',
            name='created_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passivereasonmodel',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='passivereasonmodel',
            name='updated_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
