# Generated by Django 3.1.5 on 2021-12-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0046_auto_20211212_1755'),
        ('betik_app_staff', '0046_auto_20211212_1312'),
    ]

    operations = [
    ]
