# Generated by Django 3.1.5 on 2021-12-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_document', '0003_auto_20211220_1435'),
        ('betik_app_staff', '0054_auto_20211212_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='file_employment_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_employment_agreement', to='betik_app_document.documentmodel', verbose_name='Employment Agreement'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='file_statement_of_insured_employment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_statement_of_insured_employment', to='betik_app_document.documentmodel', verbose_name='Statement of Insured Employment'),
        ),
    ]
