# Generated by Django 3.1.5 on 2021-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_document', '0003_auto_20211220_1435'),
        ('betik_app_staff', '0055_auto_20211223_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='files',
            field=models.ManyToManyField(related_name='staff_files', to='betik_app_document.DocumentModel'),
        ),
    ]
