[package]
name = "camerata"
version = "0.1.2"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "camerata"
crate-type = ["cdylib"]

[dependencies]
cpython = { version = "0.7.0", features = ["extension-module"] }
nokhwa = { version = "0.9.4", features = ["input-v4l", "output-threaded", "input-avfoundation"] }
image = "0.23"
parking_lot = "^0.11"
