repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: check-toml
    - id: check-yaml
    - id: check-json
    - id: check-merge-conflict
    - id: debug-statements
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.18.1
    hooks:
    - id: pyupgrade
      args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    - id: black
