[project]
name = "pkm-cli-app"
version = "0.4.25"
description = "Command line interface for PKM"
readme = "README.md"
requires-python = ">=3.8, <4.0"
license = {text = "MIT License"}
scripts = {pkm = "pkm_cli_app.pkm:main"}

[[project.authors]]
name = "bennyl"

[tool.pkm.internal.package]
type = "application-installer"
app = "pkm-cli"

[build-system]
requires = [ "pkm >=0.4.21",  "pkm-cli ==0.4.25"]
build-backend = "pkm.api.buildsys"