
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-28T19:47:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dc8bf306d00beda7aa8b477f03c2d85da7f1153",
 "version": "2.0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
