[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 96
target-version = ['py310']

[tool.poetry]
name = "fondat-postgresql"
version = "3.0.3"
description = "Fondat PostgreSQL module."
readme = "README.md"
authors = ["fondat-postgresql authors"]
homepage = "https://github.com/fondat/fondat-postgresql/"
documentation = "https://github.com/fondat/fondat-postgresql/wiki"
license = "MIT"
keywords = ["asgi", "framework", "resource", "openapi"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
packages = [
    { include = "fondat" }
]

[tool.poetry.dependencies]
python = "^3.9"
fondat-core = "^3.0.15"
asyncpg = "^0.25"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.17"
pytest = "^6.2"
pytest-asyncio = "^0.14"
pytest-cov = "^2.12"
