[project]
name = "django-2fa"
description = "2 Factor authenication application for Django"
dependencies = [ "django-fernet-encrypted-fields~=0.0", "pyotp~=2.6", "fido2~=0.9", "haikunator>=2.1.0", "pyjwt>=2.3.0",]
requires-python = ">=3.7"
dynamic = []
readme = "README.md"
version = "0.9.0"
[[project.authors]]
name = "Paul Bailey"
email = "paul@neutron.studio"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/neutron-sync/django-2fa"

[tool.pdm.version]
from = "django_2fa/__init__.py"

[tool.pdm.scripts]
publish = "pdm publish --username pizzapanther"
