[tool.poetry]
name = "mg_file"
version = "0.1.2"
description = "Удобное пользование файлами"
authors = ["Ваше Имя <denis-kustov@rambler.ru>"]
license = "BSD"
readme = "README.md"
homepage = "https://github.com/denisxab/mg_file"
repository = "https://github.com/denisxab/mg_file"
keywords = ["File"]
exclude = ["mg_file/.idea",
    "mg_file/venv",
    "mg_file/.git",
    "mg_file/.gitignore"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



