[tool.poetry]
name = "morningstar_data"
version = "0.0.3"
description = "Morningstar Data"
authors = ["Morningstar, Inc."]

[tool.poetry.dependencies]
python = "^3.8"
mypy = "^0.931"
pytest = "^6.2.5"
pre-commit = "^2.16.0"
black = "^21.12b0"
coverage = "^6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
