[tool.poetry]
name = "udgram"
include = ["src/udgram.py"]
version = "1.1.7"
description = ""
authors = ["wellington36 <wellington.71319@gmail.com>"]

[tool.poetry.dependencies]
python = ">3.8"
conllu = "4.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
