[tool.poetry]
name = "nonebug"
version = "0.2.1"
description = "nonebot2 test framework"
authors = ["AkiraXie <l997460364@outlook.com>", "yanyongyu <yyy@nonebot.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://v2.nonebot.dev/"
repository = "https://github.com/nonebot/nonebug"
documentation = "https://v2.nonebot.dev/"
keywords = ["nonebot", "pytest", "test", "bot", "onebot", "cqhttp"]
classifiers = ["Framework :: Pytest"]

[tool.poetry.dependencies]
python = "^3.7.3"
pytest = "^6.2.5"
asgiref = "^3.4.0"
pytest-asyncio = "^0.16.0"
nonebot2 = "^2.0.0-beta.1"
typing-extensions = "^4.0.0"
async-asgi-testclient = "^1.4.8"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^21.11b1"
pytest-cov = "^3.0.0"
pytest-order = "^1.0.0"
nonebot2 = { git = "https://github.com/nonebot/nonebot2.git", branch = "dev" }

[tool.poetry.plugins.pytest11]
nonebug = "nonebug.fixture"

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[tool.pytest.ini_options]
addopts = "--cov nonebug --cov-report term-missing -p no:nonebug"

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39", "py310"]
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 80
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
