"""Package version information."""
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
# flake8: noqa
version = '0.1.1'  # pylint: disable=invalid-name
version_tuple = (0, 1, 1)  # pylint: disable=invalid-name
