[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
source =["pathable"]

[tool.coverage.xml]
output = "reports/coverage.xml"

[tool.poetry]
name = "pathable"
version = "0.3.0"
description = "Object-oriented paths"
authors = ["Artur Maciag <maciag.artur@gmail.com>"]
license = "Apache License, Version 2.0"
readme = "README.rst"
repository = "https://github.com/p1c2u/pathable"
keywords = ["dict", "dictionary", "list", "lookup", "path", "pathable"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = ">= 2.7, != 3.0.*, != 3.1.*, != 3.2.*, != 3.3.*, != 3.4.*"
six = "*"

[tool.poetry.extras]
dev = ["pre-commit"]

[tool.poetry.dev-dependencies]
pre-commit =  {version = "*", optional = true}
pytest = "=3.5.0"
pytest-flake8 = "=1.0.7"
pytest-cov = "=2.5.1"

[tool.pytest.ini_options]
addopts = """
--capture=no
--verbose
--showlocals
--junitxml=reports/junit.xml
--cov=pathable
--cov-report=term-missing
--cov-report=xml
"""

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
force_single_line = true
