[tool.poetry]
name = "mockumentary"
version = "0.0.1"
description = "Safety placeholder"
authors = ["Prima"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
