STANDARD = [
    {
        "name":"signal",
        "zname":"signal",
        "filetype":"json",
        "path":"standard/signal.json"
    },
    {
        "name":"xmlrpc.client",
        "zname":"xmlrpc.client",
        "filetype":"json",
        "path":"standard/xmlrpc.client.json"
    },
    {
        "name":"xml.dom.pulldom",
        "zname":"xml.dom.pulldom",
        "filetype":"json",
        "path":"standard/xml.dom.pulldom.json"
    },
    {
        "name":"imghdr",
        "zname":"imghdr",
        "filetype":"json",
        "path":"standard/imghdr.json"
    },
    {
        "name":"tkinter.simpledialog",
        "zname":"tkinter.simpledialog",
        "filetype":"json",
        "path":"standard/tkinter.simpledialog.json"
    },
    {
        "name":"subprocess",
        "zname":"subprocess",
        "filetype":"json",
        "path":"standard/subprocess.json"
    },
    {
        "name":"nntplib",
        "zname":"nntplib",
        "filetype":"json",
        "path":"standard/nntplib.json"
    },
    {
        "name":"configparser",
        "zname":"configparser",
        "filetype":"json",
        "path":"standard/configparser.json"
    },
    {
        "name":"heapq",
        "zname":"heapq",
        "filetype":"json",
        "path":"standard/heapq.json"
    },
    {
        "name":"timeit",
        "zname":"timeit",
        "filetype":"json",
        "path":"standard/timeit.json"
    },
    {
        "name":"logging",
        "zname":"logging",
        "filetype":"json",
        "path":"standard/logging.json"
    },
    {
        "name":"xml.dom.minidom",
        "zname":"xml.dom.minidom",
        "filetype":"json",
        "path":"standard/xml.dom.minidom.json"
    },
    {
        "name":"difflib",
        "zname":"difflib",
        "filetype":"json",
        "path":"standard/difflib.json"
    },
    {
        "name":"struct",
        "zname":"struct",
        "filetype":"json",
        "path":"standard/struct.json"
    },
    {
        "name":"trace",
        "zname":"trace",
        "filetype":"json",
        "path":"standard/trace.json"
    },
    {
        "name":"quopri",
        "zname":"quopri",
        "filetype":"json",
        "path":"standard/quopri.json"
    },
    {
        "name":"site",
        "zname":"site",
        "filetype":"json",
        "path":"standard/site.json"
    },
    {
        "name":"cmd",
        "zname":"cmd",
        "filetype":"json",
        "path":"standard/cmd.json"
    },
    {
        "name":"csv",
        "zname":"csv",
        "filetype":"json",
        "path":"standard/csv.json"
    },
    {
        "name":"lzma",
        "zname":"lzma",
        "filetype":"json",
        "path":"standard/lzma.json"
    },
    {
        "name":"cmath",
        "zname":"cmath",
        "filetype":"json",
        "path":"standard/cmath.json"
    },
    {
        "name":"tkinter.ttk",
        "zname":"tkinter.ttk",
        "filetype":"json",
        "path":"standard/tkinter.ttk.json"
    },
    {
        "name":"shelve",
        "zname":"shelve",
        "filetype":"json",
        "path":"standard/shelve.json"
    },
    {
        "name":"pdb",
        "zname":"pdb",
        "filetype":"json",
        "path":"standard/pdb.json"
    },
    {
        "name":"zipapp",
        "zname":"zipapp",
        "filetype":"json",
        "path":"standard/zipapp.json"
    },
    {
        "name":"socketserver",
        "zname":"socketserver",
        "filetype":"json",
        "path":"standard/socketserver.json"
    },
    {
        "name":"mailbox",
        "zname":"mailbox",
        "filetype":"json",
        "path":"standard/mailbox.json"
    },
    {
        "name":"logging.config",
        "zname":"logging.config",
        "filetype":"json",
        "path":"standard/logging.config.json"
    },
    {
        "name":"smtplib",
        "zname":"smtplib",
        "filetype":"json",
        "path":"standard/smtplib.json"
    },
    {
        "name":"math",
        "zname":"math",
        "filetype":"json",
        "path":"standard/math.json"
    },
    {
        "name":"datetime",
        "zname":"datetime",
        "filetype":"json",
        "path":"standard/datetime.json"
    },
    {
        "name":"traceback",
        "zname":"traceback",
        "filetype":"json",
        "path":"standard/traceback.json"
    },
    {
        "name":"fnmatch",
        "zname":"fnmatch",
        "filetype":"json",
        "path":"standard/fnmatch.json"
    },
    {
        "name":"collections",
        "zname":"collections",
        "filetype":"json",
        "path":"standard/collections.json"
    },
    {
        "name":"__future__",
        "zname":"__future__",
        "filetype":"json",
        "path":"standard/__future__.json"
    },
    {
        "name":"doctest",
        "zname":"doctest",
        "filetype":"json",
        "path":"standard/doctest.json"
    },
    {
        "name":"telnetlib",
        "zname":"telnetlib",
        "filetype":"json",
        "path":"standard/telnetlib.json"
    },
    {
        "name":"plistlib",
        "zname":"plistlib",
        "filetype":"json",
        "path":"standard/plistlib.json"
    },
    {
        "name":"itertools",
        "zname":"itertools",
        "filetype":"json",
        "path":"standard/itertools.json"
    },
    {
        "name":"dis",
        "zname":"dis",
        "filetype":"json",
        "path":"standard/dis.json"
    },
    {
        "name":"asyncio",
        "zname":"asyncio",
        "filetype":"json",
        "path":"standard/asyncio.json"
    },
    {
        "name":"os",
        "zname":"os",
        "filetype":"json",
        "path":"standard/os.json"
    },
    {
        "name":"ctypes",
        "zname":"ctypes",
        "filetype":"json",
        "path":"standard/ctypes.json"
    },
    {
        "name":"token",
        "zname":"token",
        "filetype":"json",
        "path":"standard/token.json"
    },
    {
        "name":"readline",
        "zname":"readline",
        "filetype":"json",
        "path":"standard/readline.json"
    },
    {
        "name":"py_compile",
        "zname":"py_compile",
        "filetype":"json",
        "path":"standard/py_compile.json"
    },
    {
        "name":"asynchat",
        "zname":"asynchat",
        "filetype":"json",
        "path":"standard/asynchat.json"
    },
    {
        "name":"code",
        "zname":"code",
        "filetype":"json",
        "path":"standard/code.json"
    },
    {
        "name":"pty",
        "zname":"pty",
        "filetype":"json",
        "path":"standard/pty.json"
    },
    {
        "name":"xml.sax.xmlreader",
        "zname":"xml.sax.xmlreader",
        "filetype":"json",
        "path":"standard/xml.sax.xmlreader.json"
    },
    {
        "name":"types",
        "zname":"types",
        "filetype":"json",
        "path":"standard/types.json"
    },
    {
        "name":"optparse",
        "zname":"optparse",
        "filetype":"json",
        "path":"standard/optparse.json"
    },
    {
        "name":"socket",
        "zname":"socket",
        "filetype":"json",
        "path":"standard/socket.json"
    },
    {
        "name":"pathlib",
        "zname":"pathlib",
        "filetype":"json",
        "path":"standard/pathlib.json"
    },
    {
        "name":"textwrap",
        "zname":"textwrap",
        "filetype":"json",
        "path":"standard/textwrap.json"
    },
    {
        "name":"chunk",
        "zname":"chunk",
        "filetype":"json",
        "path":"standard/chunk.json"
    },
    {
        "name":"aifc",
        "zname":"aifc",
        "filetype":"json",
        "path":"standard/aifc.json"
    },
    {
        "name":"lib2to3",
        "zname":"lib2to3",
        "filetype":"json",
        "path":"standard/lib2to3.json"
    },
    {
        "name":"ipaddress",
        "zname":"ipaddress",
        "filetype":"json",
        "path":"standard/ipaddress.json"
    },
    {
        "name":"selectors",
        "zname":"selectors",
        "filetype":"json",
        "path":"standard/selectors.json"
    },
    {
        "name":"codecs",
        "zname":"codecs",
        "filetype":"json",
        "path":"standard/codecs.json"
    },
    {
        "name":"sched",
        "zname":"sched",
        "filetype":"json",
        "path":"standard/sched.json"
    },
    {
        "name":"xml.sax.handler",
        "zname":"xml.sax.handler",
        "filetype":"json",
        "path":"standard/xml.sax.handler.json"
    },
    {
        "name":"atexit",
        "zname":"atexit",
        "filetype":"json",
        "path":"standard/atexit.json"
    },
    {
        "name":"concurrent.futures",
        "zname":"concurrent.futures",
        "filetype":"json",
        "path":"standard/concurrent.futures.json"
    },
    {
        "name":"tracemalloc",
        "zname":"tracemalloc",
        "filetype":"json",
        "path":"standard/tracemalloc.json"
    },
    {
        "name":"tempfile",
        "zname":"tempfile",
        "filetype":"json",
        "path":"standard/tempfile.json"
    },
    {
        "name":"smtpd",
        "zname":"smtpd",
        "filetype":"json",
        "path":"standard/smtpd.json"
    },
    {
        "name":"bz2",
        "zname":"bz2",
        "filetype":"json",
        "path":"standard/bz2.json"
    },
    {
        "name":"enum",
        "zname":"enum",
        "filetype":"json",
        "path":"standard/enum.json"
    },
    {
        "name":"xdrlib",
        "zname":"xdrlib",
        "filetype":"json",
        "path":"standard/xdrlib.json"
    },
    {
        "name":"symtable",
        "zname":"symtable",
        "filetype":"json",
        "path":"standard/symtable.json"
    },
    {
        "name":"os.path",
        "zname":"os.path",
        "filetype":"json",
        "path":"standard/os.path.json"
    },
    {
        "name":"tkinter.tix",
        "zname":"tkinter.tix",
        "filetype":"json",
        "path":"standard/tkinter.tix.json"
    },
    {
        "name":"shutil",
        "zname":"shutil",
        "filetype":"json",
        "path":"standard/shutil.json"
    },
    {
        "name":"bisect",
        "zname":"bisect",
        "filetype":"json",
        "path":"standard/bisect.json"
    },
    {
        "name":"unittest",
        "zname":"unittest",
        "filetype":"json",
        "path":"standard/unittest.json"
    },
    {
        "name":"locale",
        "zname":"locale",
        "filetype":"json",
        "path":"standard/locale.json"
    },
    {
        "name":"http",
        "zname":"http",
        "filetype":"json",
        "path":"standard/http.json"
    },
    {
        "name":"pipes",
        "zname":"pipes",
        "filetype":"json",
        "path":"standard/pipes.json"
    },
    {
        "name":"secrets",
        "zname":"secrets",
        "filetype":"json",
        "path":"standard/secrets.json"
    },
    {
        "name":"functools",
        "zname":"functools",
        "filetype":"json",
        "path":"standard/functools.json"
    },
    {
        "name":"platform",
        "zname":"platform",
        "filetype":"json",
        "path":"standard/platform.json"
    },
    {
        "name":"msvcrt",
        "zname":"msvcrt",
        "filetype":"json",
        "path":"standard/msvcrt.json"
    },
    {
        "name":"pickletools",
        "zname":"pickletools",
        "filetype":"json",
        "path":"standard/pickletools.json"
    },
    {
        "name":"ensurepip",
        "zname":"ensurepip",
        "filetype":"json",
        "path":"standard/ensurepip.json"
    },
    {
        "name":"nis",
        "zname":"nis",
        "filetype":"json",
        "path":"standard/nis.json"
    },
    {
        "name":"importlib.metadata",
        "zname":"importlib.metadata",
        "filetype":"json",
        "path":"standard/importlib.metadata.json"
    },
    {
        "name":"zipfile",
        "zname":"zipfile",
        "filetype":"json",
        "path":"standard/zipfile.json"
    },
    {
        "name":"random",
        "zname":"random",
        "filetype":"json",
        "path":"standard/random.json"
    },
    {
        "name":"statistics",
        "zname":"statistics",
        "filetype":"json",
        "path":"standard/statistics.json"
    },
    {
        "name":"audioop",
        "zname":"audioop",
        "filetype":"json",
        "path":"standard/audioop.json"
    },
    {
        "name":"msilib",
        "zname":"msilib",
        "filetype":"json",
        "path":"standard/msilib.json"
    },
    {
        "name":"numbers",
        "zname":"numbers",
        "filetype":"json",
        "path":"standard/numbers.json"
    },
    {
        "name":"fileinput",
        "zname":"fileinput",
        "filetype":"json",
        "path":"standard/fileinput.json"
    },
    {
        "name":"mimetypes",
        "zname":"mimetypes",
        "filetype":"json",
        "path":"standard/mimetypes.json"
    },
    {
        "name":"string",
        "zname":"string",
        "filetype":"json",
        "path":"standard/string.json"
    },
    {
        "name":"http.cookies",
        "zname":"http.cookies",
        "filetype":"json",
        "path":"standard/http.cookies.json"
    },
    {
        "name":"netrc",
        "zname":"netrc",
        "filetype":"json",
        "path":"standard/netrc.json"
    },
    {
        "name":"pwd",
        "zname":"pwd",
        "filetype":"json",
        "path":"standard/pwd.json"
    },
    {
        "name":"threading",
        "zname":"threading",
        "filetype":"json",
        "path":"standard/threading.json"
    },
    {
        "name":"compileall",
        "zname":"compileall",
        "filetype":"json",
        "path":"standard/compileall.json"
    },
    {
        "name":"ssl",
        "zname":"ssl",
        "filetype":"json",
        "path":"standard/ssl.json"
    },
    {
        "name":"winreg",
        "zname":"winreg",
        "filetype":"json",
        "path":"standard/winreg.json"
    },
    {
        "name":"time",
        "zname":"time",
        "filetype":"json",
        "path":"standard/time.json"
    },
    {
        "name":"copyreg",
        "zname":"copyreg",
        "filetype":"json",
        "path":"standard/copyreg.json"
    },
    {
        "name":"imaplib",
        "zname":"imaplib",
        "filetype":"json",
        "path":"standard/imaplib.json"
    },
    {
        "name":"xml.dom",
        "zname":"xml.dom",
        "filetype":"json",
        "path":"standard/xml.dom.json"
    },
    {
        "name":"sqlite3",
        "zname":"sqlite3",
        "filetype":"json",
        "path":"standard/sqlite3.json"
    },
    {
        "name":"queue",
        "zname":"queue",
        "filetype":"json",
        "path":"standard/queue.json"
    },
    {
        "name":"tkinter.messagebox",
        "zname":"tkinter.messagebox",
        "filetype":"json",
        "path":"standard/tkinter.messagebox.json"
    },
    {
        "name":"unittest.mock",
        "zname":"unittest.mock",
        "filetype":"json",
        "path":"standard/unittest.mock.json"
    },
    {
        "name":"resource",
        "zname":"resource",
        "filetype":"json",
        "path":"standard/resource.json"
    },
    {
        "name":"webbrowser",
        "zname":"webbrowser",
        "filetype":"json",
        "path":"standard/webbrowser.json"
    },
    {
        "name":"faulthandler",
        "zname":"faulthandler",
        "filetype":"json",
        "path":"standard/faulthandler.json"
    },
    {
        "name":"wave",
        "zname":"wave",
        "filetype":"json",
        "path":"standard/wave.json"
    },
    {
        "name":"io",
        "zname":"io",
        "filetype":"json",
        "path":"standard/io.json"
    },
    {
        "name":"asyncore",
        "zname":"asyncore",
        "filetype":"json",
        "path":"standard/asyncore.json"
    },
    {
        "name":"gettext",
        "zname":"gettext",
        "filetype":"json",
        "path":"standard/gettext.json"
    },
    {
        "name":"decimal",
        "zname":"decimal",
        "filetype":"json",
        "path":"standard/decimal.json"
    },
    {
        "name":"termios",
        "zname":"termios",
        "filetype":"json",
        "path":"standard/termios.json"
    },
    {
        "name":"collections.abc",
        "zname":"collections.abc",
        "filetype":"json",
        "path":"standard/collections.abc.json"
    },
    {
        "name":"zipimport",
        "zname":"zipimport",
        "filetype":"json",
        "path":"standard/zipimport.json"
    },
    {
        "name":"sysconfig",
        "zname":"sysconfig",
        "filetype":"json",
        "path":"standard/sysconfig.json"
    },
    {
        "name":"logging.handlers",
        "zname":"logging.handlers",
        "filetype":"json",
        "path":"standard/logging.handlers.json"
    },
    {
        "name":"__main__",
        "zname":"__main__",
        "filetype":"json",
        "path":"standard/__main__.json"
    },
    {
        "name":"operator",
        "zname":"operator",
        "filetype":"json",
        "path":"standard/operator.json"
    },
    {
        "name":"tokenize",
        "zname":"tokenize",
        "filetype":"json",
        "path":"standard/tokenize.json"
    },
    {
        "name":"json",
        "zname":"json",
        "filetype":"json",
        "path":"standard/json.json"
    },
    {
        "name":"glob",
        "zname":"glob",
        "filetype":"json",
        "path":"standard/glob.json"
    },
    {
        "name":"html.parser",
        "zname":"html.parser",
        "filetype":"json",
        "path":"standard/html.parser.json"
    },
    {
        "name":"inspect",
        "zname":"inspect",
        "filetype":"json",
        "path":"standard/inspect.json"
    },
    {
        "name":"reprlib",
        "zname":"reprlib",
        "filetype":"json",
        "path":"standard/reprlib.json"
    },
    {
        "name":"gzip",
        "zname":"gzip",
        "filetype":"json",
        "path":"standard/gzip.json"
    },
    {
        "name":"xml.parsers.expat",
        "zname":"xml.parsers.expat",
        "filetype":"json",
        "path":"standard/xml.parsers.expat.json"
    },
    {
        "name":"turtle",
        "zname":"turtle",
        "filetype":"json",
        "path":"standard/turtle.json"
    },
    {
        "name":"uuid",
        "zname":"uuid",
        "filetype":"json",
        "path":"standard/uuid.json"
    },
    {
        "name":"pprint",
        "zname":"pprint",
        "filetype":"json",
        "path":"standard/pprint.json"
    },
    {
        "name":"tarfile",
        "zname":"tarfile",
        "filetype":"json",
        "path":"standard/tarfile.json"
    },
    {
        "name":"rlcompleter",
        "zname":"rlcompleter",
        "filetype":"json",
        "path":"standard/rlcompleter.json"
    },
    {
        "name":"ftplib",
        "zname":"ftplib",
        "filetype":"json",
        "path":"standard/ftplib.json"
    },
    {
        "name":"base64",
        "zname":"base64",
        "filetype":"json",
        "path":"standard/base64.json"
    },
    {
        "name":"http.client",
        "zname":"http.client",
        "filetype":"json",
        "path":"standard/http.client.json"
    },
    {
        "name":"argparse",
        "zname":"argparse",
        "filetype":"json",
        "path":"standard/argparse.json"
    },
    {
        "name":"xml.sax",
        "zname":"xml.sax",
        "filetype":"json",
        "path":"standard/xml.sax.json"
    },
    {
        "name":"xmlrpc.server",
        "zname":"xmlrpc.server",
        "filetype":"json",
        "path":"standard/xmlrpc.server.json"
    },
    {
        "name":"dbm",
        "zname":"dbm",
        "filetype":"json",
        "path":"standard/dbm.json"
    },
    {
        "name":"crypt",
        "zname":"crypt",
        "filetype":"json",
        "path":"standard/crypt.json"
    },
    {
        "name":"tkinter",
        "zname":"tkinter",
        "filetype":"json",
        "path":"standard/tkinter.json"
    },
    {
        "name":"zoneinfo",
        "zname":"zoneinfo",
        "filetype":"json",
        "path":"standard/zoneinfo.json"
    },
    {
        "name":"weakref",
        "zname":"weakref",
        "filetype":"json",
        "path":"standard/weakref.json"
    },
    {
        "name":"graphlib",
        "zname":"graphlib",
        "filetype":"json",
        "path":"standard/graphlib.json"
    },
    {
        "name":"multiprocessing",
        "zname":"multiprocessing",
        "filetype":"json",
        "path":"standard/multiprocessing.json"
    },
    {
        "name":"urllib.parse",
        "zname":"urllib.parse",
        "filetype":"json",
        "path":"standard/urllib.parse.json"
    },
    {
        "name":"unicodedata",
        "zname":"unicodedata",
        "filetype":"json",
        "path":"standard/unicodedata.json"
    },
    {
        "name":"mmap",
        "zname":"mmap",
        "filetype":"json",
        "path":"standard/mmap.json"
    },
    {
        "name":"poplib",
        "zname":"poplib",
        "filetype":"json",
        "path":"standard/poplib.json"
    },
    {
        "name":"tkinter.colorchooser",
        "zname":"tkinter.colorchooser",
        "filetype":"json",
        "path":"standard/tkinter.colorchooser.json"
    },
    {
        "name":"venv",
        "zname":"venv",
        "filetype":"json",
        "path":"standard/venv.json"
    },
    {
        "name":"cgi",
        "zname":"cgi",
        "filetype":"json",
        "path":"standard/cgi.json"
    },
    {
        "name":"modulefinder",
        "zname":"modulefinder",
        "filetype":"json",
        "path":"standard/modulefinder.json"
    },
    {
        "name":"ast",
        "zname":"ast",
        "filetype":"json",
        "path":"standard/ast.json"
    },
    {
        "name":"binascii",
        "zname":"binascii",
        "filetype":"json",
        "path":"standard/binascii.json"
    },
    {
        "name":"contextvars",
        "zname":"contextvars",
        "filetype":"json",
        "path":"standard/contextvars.json"
    },
    {
        "name":"re",
        "zname":"re",
        "filetype":"json",
        "path":"standard/re.json"
    },
    {
        "name":"filecmp",
        "zname":"filecmp",
        "filetype":"json",
        "path":"standard/filecmp.json"
    },
    {
        "name":"pickle",
        "zname":"pickle",
        "filetype":"json",
        "path":"standard/pickle.json"
    },
    {
        "name":"tkinter.scrolledtext",
        "zname":"tkinter.scrolledtext",
        "filetype":"json",
        "path":"standard/tkinter.scrolledtext.json"
    },
    {
        "name":"urllib.error",
        "zname":"urllib.error",
        "filetype":"json",
        "path":"standard/urllib.error.json"
    },
    {
        "name":"pydoc",
        "zname":"pydoc",
        "filetype":"json",
        "path":"standard/pydoc.json"
    },
    {
        "name":"posix",
        "zname":"posix",
        "filetype":"json",
        "path":"standard/posix.json"
    },
    {
        "name":"importlib",
        "zname":"importlib",
        "filetype":"json",
        "path":"standard/importlib.json"
    },
    {
        "name":"curses",
        "zname":"curses",
        "filetype":"json",
        "path":"standard/curses.json"
    },
    {
        "name":"binhex",
        "zname":"binhex",
        "filetype":"json",
        "path":"standard/binhex.json"
    },
    {
        "name":"hashlib",
        "zname":"hashlib",
        "filetype":"json",
        "path":"standard/hashlib.json"
    },
    {
        "name":"sunau",
        "zname":"sunau",
        "filetype":"json",
        "path":"standard/sunau.json"
    },
    {
        "name":"shlex",
        "zname":"shlex",
        "filetype":"json",
        "path":"standard/shlex.json"
    },
    {
        "name":"profile",
        "zname":"profile",
        "filetype":"json",
        "path":"standard/profile.json"
    },
    {
        "name":"warnings",
        "zname":"warnings",
        "filetype":"json",
        "path":"standard/warnings.json"
    },
    {
        "name":"pyclbr",
        "zname":"pyclbr",
        "filetype":"json",
        "path":"standard/pyclbr.json"
    },
    {
        "name":"spwd",
        "zname":"spwd",
        "filetype":"json",
        "path":"standard/spwd.json"
    },
    {
        "name":"ossaudiodev",
        "zname":"ossaudiodev",
        "filetype":"json",
        "path":"standard/ossaudiodev.json"
    },
    {
        "name":"xml.etree.ElementTree",
        "zname":"xml.etree.ElementTree",
        "filetype":"json",
        "path":"standard/xml.etree.ElementTree.json"
    },
    {
        "name":"contextlib",
        "zname":"contextlib",
        "filetype":"json",
        "path":"standard/contextlib.json"
    },
    {
        "name":"typing",
        "zname":"typing",
        "filetype":"json",
        "path":"standard/typing.json"
    },
    {
        "name":"curses.panel",
        "zname":"curses.panel",
        "filetype":"json",
        "path":"standard/curses.panel.json"
    },
    {
        "name":"colorsys",
        "zname":"colorsys",
        "filetype":"json",
        "path":"standard/colorsys.json"
    },
    {
        "name":"select",
        "zname":"select",
        "filetype":"json",
        "path":"standard/select.json"
    },
    {
        "name":"dataclasses",
        "zname":"dataclasses",
        "filetype":"json",
        "path":"standard/dataclasses.json"
    },
    {
        "name":"urllib.request",
        "zname":"urllib.request",
        "filetype":"json",
        "path":"standard/urllib.request.json"
    }
]