[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "matplotlib",
    "numpy",
    "pandas",
    "prettytable",
    "PyExcelerate",
    "pytz",
    "SALib",
    "scipy"

]
build-backend = "setuptools.build_meta"
