"""
    Nomad Broker

    Make payments, and customs declaration for orders.  # noqa: E501

    The version of the OpenAPI document: 1.4.11
    Contact: manwei@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_broker_cli
from nomad_broker_cli.model.goods_info import GoodsInfo
from nomad_broker_cli.model.payment_product_req import PaymentProductReq
globals()['GoodsInfo'] = GoodsInfo
globals()['PaymentProductReq'] = PaymentProductReq
from nomad_broker_cli.model.payment_product import PaymentProduct


class TestPaymentProduct(unittest.TestCase):
    """PaymentProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentProduct(self):
        """Test PaymentProduct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentProduct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
