"""
    Nomad Broker

    Make payments, and customs declaration for orders.  # noqa: E501

    The version of the OpenAPI document: 1.4.11
    Contact: manwei@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_broker_cli
from nomad_broker_cli.model.payout_request_payee_info import PayoutRequestPayeeInfo


class TestPayoutRequestPayeeInfo(unittest.TestCase):
    """PayoutRequestPayeeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayoutRequestPayeeInfo(self):
        """Test PayoutRequestPayeeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayoutRequestPayeeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
