"""
    Nomad Broker

    Make payments, and customs declaration for orders.  # noqa: E501

    The version of the OpenAPI document: 1.4.11
    Contact: manwei@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_broker_cli
from nomad_broker_cli.model.payout_request_express_info import PayoutRequestExpressInfo


class TestPayoutRequestExpressInfo(unittest.TestCase):
    """PayoutRequestExpressInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayoutRequestExpressInfo(self):
        """Test PayoutRequestExpressInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayoutRequestExpressInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
