"""
    Nomad Broker

    Make payments, and customs declaration for orders.  # noqa: E501

    The version of the OpenAPI document: 1.4.11
    Contact: manwei@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_broker_cli
from nomad_broker_cli.model.customs_code import CustomsCode
from nomad_broker_cli.model.payment_method import PaymentMethod
globals()['CustomsCode'] = CustomsCode
globals()['PaymentMethod'] = PaymentMethod
from nomad_broker_cli.model.customs_payment_redeclare_request import CustomsPaymentRedeclareRequest


class TestCustomsPaymentRedeclareRequest(unittest.TestCase):
    """CustomsPaymentRedeclareRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomsPaymentRedeclareRequest(self):
        """Test CustomsPaymentRedeclareRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomsPaymentRedeclareRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
