"""
    Nomad Broker

    Make payments, and customs declaration for orders.  # noqa: E501

    The version of the OpenAPI document: 1.4.11
    Contact: manwei@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_broker_cli
from nomad_broker_cli.model.goods_info import GoodsInfo
from nomad_broker_cli.model.payment_method import PaymentMethod
from nomad_broker_cli.model.payout_request_express_info import PayoutRequestExpressInfo
from nomad_broker_cli.model.payout_request_payee_info import PayoutRequestPayeeInfo
from nomad_broker_cli.model.payout_request_seller_info import PayoutRequestSellerInfo
globals()['GoodsInfo'] = GoodsInfo
globals()['PaymentMethod'] = PaymentMethod
globals()['PayoutRequestExpressInfo'] = PayoutRequestExpressInfo
globals()['PayoutRequestPayeeInfo'] = PayoutRequestPayeeInfo
globals()['PayoutRequestSellerInfo'] = PayoutRequestSellerInfo
from nomad_broker_cli.model.payout_request import PayoutRequest


class TestPayoutRequest(unittest.TestCase):
    """PayoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayoutRequest(self):
        """Test PayoutRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayoutRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
