"""
    Nomad Broker

    Make payments, and customs declaration for orders.  # noqa: E501

    The version of the OpenAPI document: 1.4.11
    Contact: manwei@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_broker_cli
from nomad_broker_cli.model.error_api_response import ErrorApiResponse


class TestErrorApiResponse(unittest.TestCase):
    """ErrorApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorApiResponse(self):
        """Test ErrorApiResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorApiResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
