
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-27T18:31:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "edd3a805f3d98a5556f8f14eb3dc87eada8ec17e",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
