name: Tests
on:
  push:
  pull_request:
  pull_request_target:

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        django-version: [ "2.2.26", "3.2.11", "4.0.1" ]
        cryptography-version: [ "3.3.2", "3.4.7", "35.0.0", "36.0.1" ]
        exclude:
            - python-version: "3.7"
              django-version: "4.0.1"

    env:
      DJANGO_CA_SECRET_KEY: dummy

    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, cryptography ${{ matrix.cryptography-version }}, OS ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Apply caching of dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: os=${{ matrix.os }}-python=${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements-*.txt') }}

      - name: Install dependencies
        run: |
          echo "cryptography==${{ matrix.cryptography-version }}" > constraints.txt
          echo "django==${{ matrix.django-version }}" >> constraints.txt
          pip install -U pip setuptools
          pip install -c constraints.txt -r requirements.txt -r requirements/requirements-test.txt

      - name: Install program
        run: python setup.py develop

      - name: Run tests
        run: |
          python dev.py init-demo
          python dev.py coverage --format=text
