[tool.poetry]
name = "views_runs"
version = "1.9.1"
description = ""
authors = ["peder2911 <pglandsverk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
stepshift = "~=2.2.0"
views-partitioning = "^3.0.0"
viewser = "^5.7.3"
scikit-learn = "^1.0.2"

[tool.poetry.dev-dependencies]
jedi = "^0.18.0"
pylint = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
