[tool.poetry]
name = "kapla-cli-core"
version = "3.5.0"
description = ""
authors = ["Guillaume Charbonnier <guillaume.charbonnier@araymond.com>"]
packages = [{ include = "kapla" }]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
typer = "^0.3.2"
loguru = "^0.5.3"
pydantic = "^1.8.2"
tomlkit = "^0.7.2"
stdlib-list = "^0.8.0"
python-on-whales = "^0.24.0"
rich = "^10.7.0"
types-pkg-resources = "^0.1.3"
types-PyYAML = "^5.4.6"


[tool.poetry.dev-dependencies]
colorama = "^0.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
