[tool.poetry]
name = "sqlcli"
version = "0.1.0a2"
description = "A command line interface (CLI) for interacting with SQLModel."
authors = ["SamEdwardes <edwardes.s@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/SamEdwardes/sqlcli"
documentation = "https://samedwardes.github.io/sqlcli/"
keywords = ["sql", "cli", "typer", "python", "sqlmodel", "rich", "sqlalchemy"]
include = [
    "sqlcli/_demo/models.py"
]

[tool.poetry.dependencies]
python = "^3.9"
sqlmodel = "^0.0.6"
rich = "^11.0.0"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
mkdocs-material = "^8.1.7"
mkdocs-include-markdown-plugin = "^3.2.3"
mdx-include = "^1.4.1"
pytest-xdist = "^2.5.0"

[tool.poetry.scripts]
sqlcli = "sqlcli.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
