[tool.poetry]
name = "udn-songbook"
version = "1.1.0"
description = "songbook and songsheet management for songsheets in ukedown format"
authors = ["Stuart Sears <stuart@sjsears.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ukedown = "^2.0.0"
beautifulsoup4 = "^4.9.3"
PyYAML = ">= 5"
WeasyPrint = "^53.4"
Markdown = "^3.3.4"
Jinja2 = "^3.0.1"
lxml = "^4.6.4"
pychord = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.16.0"
black = "^21.11b1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
# configuration for the pyright syntax checker/linter
# handles warnings about variables for which we do not yet
# know the type
reportOptionalSubscript = false
reportOptionalIterable = false
reportOptionalMemberAccess = false
reportGeneralTypeIssues = false

[tool.black]
# project-specific black setup
line-length = 88
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '/(\.git|_build|build|dist|\.tox|\.venv)/'

[tool.isort]
# import-sorting plugin
profile = "black"
