[tool.poetry]
name = "UploadgramPyAPI"
version = "1.5"
description = "This API can be upload, download, remove and rename any files from the service uploadgram.me. More on my GitHub: https://github.com/tankalxat34/UploadgramPyAPI"
authors = ["tankalxat34"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
