default: &default
        model:
                module: hooknet.model
                attribute: HookNet
                input_shape@replace=true: [[1244,1244,3], [1244,1244,3]]
                n_classes: 3
                hook_indices@replace=true: [2, 4]
                depth: 4
                n_convs: 2
                filter_size: 3
                n_filters: 32
                padding: valid
                batch_norm: True
                learning_rate: 0.000005
                opt_name: adam  
                l2_lambda: 0.001
                loss_weights: [1.0, 0.0]
                merge_type: concat

