
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-30T16:46:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1d41494176f34d803582177d6f04d308c0172cf",
 "version": "v0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
