[tool.poetry]
name = "peasy-logs"
version = "0.1.0"
description = "Easily ship you logs from functions to various connectors!"
authors = ["larsheinen <larsheinen@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.17.0"
jupyter = "^1.0.0"
Sphinx = "^4.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
