
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-28T10:57:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "88e059bca24b4ebc14e1bb70b732282bd10e7906",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
