[tool.poetry]
name = "sleeep"
version = "0.5.0"
description = ""
authors = ["Steffen Brinkmann <s-b@mailbox.org>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-flake8 = "^1.0.7"
pytest-coverage = "^0.0"
flake8 = "<4.0"
pytest-mypy = "^0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sleeep = 'sleeep.sleeep_main:run'

[tool.isort]
skip = ["__init__.py"]

