# Generated by Django 3.2.11 on 2022-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0007_portforward_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portforward',
            name='proto',
            field=models.CharField(blank=True, choices=[('tcp', 'tcp'), ('udp', 'udp')], default='tcp', max_length=32, null=True, verbose_name='网络协议类型'),
        ),
    ]
