# Generated by Django 3.2.11 on 2022-01-22 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtproxy', '0015_auto_20220122_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default=None, max_length=64, verbose_name='项名')),
                ('private_key', models.TextField(blank=True, default='', null=True, verbose_name='系统专用私钥')),
                ('public_key', models.TextField(blank=True, default='', null=True, verbose_name='系统专用私钥对应公钥')),
            ],
            options={
                'verbose_name': '核心配置',
                'verbose_name_plural': '核心配置',
            },
        ),
        migrations.CreateModel(
            name='SysSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=64, verbose_name='项名')),
                ('value', models.CharField(default='', max_length=64, verbose_name='项值')),
                ('verbose', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.AlterField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
