# Generated by Django 3.2.11 on 2022-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0018_script_markdown_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='host',
            field=models.CharField(max_length=64, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='portforward',
            name='lhost',
            field=models.CharField(default='0.0.0.0', max_length=64, verbose_name='本机IP'),
        ),
        migrations.AlterField(
            model_name='sshhost',
            name='host',
            field=models.CharField(max_length=64, verbose_name='主机名'),
        ),
    ]
