# Generated by Django 3.2.11 on 2022-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0022_auto_20220127_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': '站点配置', 'verbose_name_plural': '站点配置'},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='onion',
            field=models.CharField(default=None, max_length=64, verbose_name='onion'),
        ),
    ]
