# Generated by Django 3.2.11 on 2022-01-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0024_auto_20220127_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default=None, max_length=64, unique=True, verbose_name='站点域名'),
        ),
    ]
