
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T23:39:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aadc1c2cd8141361c50ae1a5c541aa2f2507cbd1",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
