
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-28T15:40:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3c9577a5ee29622b4d6175778e0345a9beb1b86",
 "version": "0.9.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
