
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T11:15:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8b827d536493df57742d1b834546660b3e2edb5",
 "version": "v0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
