[tool.poetry]
name = 'dirty-equals'
version = '0'
description = 'Using __eq__ for dirty, but extremely useful things.'
authors = ['Samuel Colvin <s@muelcolvin.com>']
readme = 'README.md'
homepage = 'https://github.com/samuelcolvin/dirty-equals'
documentation = 'https://github.com/samuelcolvin/dirty-equals'
repository = 'https://github.com/samuelcolvin/dirty-equals'
license = 'MIT'
classifiers = [
    'Development Status :: 4 - Beta',
    'Framework :: Pytest',
    'Intended Audience :: Developers',
    'Intended Audience :: Education',
    'Intended Audience :: Information Technology',
    'Intended Audience :: Science/Research',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Topic :: Internet',
    'Typing :: Typed',
]

[tool.poetry.dependencies]
python = '^3.7.0'

[tool.poetry.dev-dependencies]
coverage = '^6.2'
pydantic = '^1.9.0'
pytest = '^6.2.5'
pytest-cov = '^3.0.0'
pytest-asyncio = '^0.17.2'
pytest-mock = '^3.6.1'
pytest-sugar = '^0.9.4'
pytest-toolbox = '^0.4'
black = '^21.12b0'
flake8 = '^4.0.1'
flake8-quotes = '^3.3.1'
isort = {extras = ['colors'], version = '^5.10.1'}
mypy = '^0.931'
pycodestyle = '^2.8.0'
pyflakes = '^2.4.0'

[build-system]
requires = ['poetry-core']
build-backend = 'poetry.core.masonry.api'

[tool.poetry-version-plugin]
source = 'init'

[tool.pytest.ini_options]
testpaths = 'tests'
filterwarnings = 'error'
asyncio_mode = 'auto'

[tool.coverage.run]
source = ['src']
branch = true

[tool.coverage.report]
precision = 2
exclude_lines = [
    'pragma: no cover',
    'raise NotImplementedError',
    'raise NotImplemented',
    'if TYPE_CHECKING:',
    '@overload',
]

[tool.black]
color = true
line-length = 120
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
color_output = true

[tool.mypy]
follow_imports = 'silent'
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
warn_unused_configs = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_calls = true
disallow_untyped_defs = true

# remaining arguments from `mypy --strict` which cause errors
#no_implicit_optional = true
#warn_return_any = true

