
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T12:10:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "85a7d8de9dab1a7af85da93d2741c157422b0b68",
 "version": "0.14.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
