[tool.poetry]
name = "simple-file-logger"
version = "0.1.5"
description = "A simple logger class to log to files"
authors = ["Karanveer Singh <karan_4496@hotmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/karanveersp/simple-file-logger"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
