# Generated by Django 3.0 on 2022-01-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SshHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, verbose_name='主机名')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='PortForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lhost', models.CharField(max_length=32, verbose_name='本机IP')),
                ('lport', models.CharField(max_length=32, verbose_name='本机端口')),
                ('rhost', models.CharField(max_length=32, verbose_name='远程IP')),
                ('rport', models.CharField(max_length=32, verbose_name='远程端口')),
                ('proto', models.CharField(blank=True, choices=[('tcp', 'tcp'), ('udp', 'udp')], max_length=32, null=True, verbose_name='网络协议类型')),
                ('via_ssh', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mtproxy.SshHost', verbose_name='通过ssh隧道')),
            ],
        ),
    ]
