# Generated by Django 3.0 on 2022-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portforward',
            name='lport',
            field=models.IntegerField(verbose_name='本机端口'),
        ),
        migrations.AlterField(
            model_name='portforward',
            name='rport',
            field=models.IntegerField(verbose_name='远程端口'),
        ),
    ]
