# Generated by Django 3.2.11 on 2022-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0003_auto_20220119_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshhost',
            name='port',
            field=models.IntegerField(default=22, verbose_name='端口'),
        ),
    ]
