# Generated by Django 3.2.11 on 2022-01-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0006_alter_portforward_lhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='portforward',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
