# Generated by Django 3.2.11 on 2022-01-19 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtproxy', '0008_alter_portforward_proto'),
    ]

    operations = [
        migrations.AddField(
            model_name='portforward',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portforward',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='portforward',
            name='title',
            field=models.CharField(blank=True, default='[new]', max_length=64, null=True, verbose_name='备注'),
        ),
    ]
