# Generated by Django 3.2.11 on 2022-01-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0011_auto_20220121_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='备注')),
                ('type', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='类型')),
                ('host', models.CharField(max_length=32, verbose_name='主机名')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, default=None, null=True, verbose_name='私钥')),
                ('tag', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='标签分类')),
                ('is_live', models.BooleanField(default=False, verbose_name='是否在线')),
                ('last_check', models.DateTimeField(auto_now=True, verbose_name='最新检测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '肉鸡',
                'verbose_name_plural': '肉鸡',
            },
        ),
        migrations.CreateModel(
            name='Onion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='[new onion]', max_length=64, null=True, verbose_name='备注')),
                ('hs_ed25519_secret_key', models.CharField(max_length=128, verbose_name='base64编码的私钥')),
                ('hs_ed25519_pub_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='base64编码的公钥')),
                ('onion', models.CharField(max_length=64, verbose_name='onion域名')),
            ],
        ),
        migrations.CreateModel(
            name='OnionBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='[new onion]', max_length=64, null=True, verbose_name='备注')),
                ('hs_ed25519_secret_key', models.CharField(max_length=128, verbose_name='base64编码的私钥')),
                ('hs_ed25519_pub_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='base64编码的公钥')),
                ('onion', models.CharField(max_length=64, verbose_name='onion域名')),
            ],
        ),
    ]
