# Generated by Django 3.2.11 on 2022-01-22 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0014_auto_20220122_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='private_key_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='私钥'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='private_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mtproxy.privatekey'),
        ),
    ]
