# Generated by Django 3.2.11 on 2022-01-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtproxy', '0016_auto_20220122_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='[new script]', max_length=64, null=True, verbose_name='备注')),
                ('type', models.CharField(choices=[('bash', 'bash'), ('python', 'python')], max_length=16, verbose_name='脚本类型')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
            },
        ),
    ]
