# Generated by Django 3.2.11 on 2022-01-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0017_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='markdown_content',
            field=models.TextField(blank=True, null=True, verbose_name='辅助内容'),
        ),
    ]
