# Generated by Django 3.2.11 on 2022-01-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0020_botlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlog',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtproxy.bot', verbose_name='肉鸡'),
            preserve_default=False,
        ),
    ]
