# Generated by Django 3.2.11 on 2022-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0023_auto_20220127_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='site_domain',
            new_name='site_name',
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='onion',
            field=models.CharField(default=None, max_length=64, verbose_name='onion域名'),
        ),
    ]
