[tool.poetry]
name = "django-simple-graphql"
version = "0.5.0"
description = "A stupid simple GraphQL setup for Django"
authors = ["Joa Riski <joa.riski@riskidev.fi>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/JoaRiski/django-simple-graphql"
repository = "https://github.com/JoaRiski/django-simple-graphql"
include = [
    "LICENSE",
]
packages = [
    { include = "simple_graphql" },
]

[tool.poetry.dependencies]
python = "^3.8"
graphene-django = "^2.15.0"
django-filter = "^2.4.0"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
django-stubs = "^1.9.0"
pytest = "^6.2.5"
pytest-django = "^4.4.0"
pytest-cov = "^2.12.1"

[tool.isort]
profile = "black"
known_third_party = ["django"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "example.settings"
norecursedirs = "venv .git .mypy_cache .pytest_cache dist __pycache__"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = "(venv|dist|.pytest_cache|.git|.mypy_cache|__pycache__|.idea)/$"

[tool.django-stubs]
django_settings_module = "example.settings"

[[tool.mypy.overrides]]
module = [
    "graphene.*",
    "graphene_django.*",
    "graphql_relay"
]
ignore_missing_imports = true
