[tool.poetry]
name = "ragclip"
version = "0.0.4"
authors = ["Mark Raleson <markraleson@outlook.com>"]
description = ""
readme = "README.md"
license = "MIT"
repository = "https://github.com/mraleson/ragclip.git"
packages = [
  { include="ragclip" }
]

[tool.poetry.scripts]
rag = 'ragclip.clip:main'

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.1.4"

[tool.poetry.dev-dependencies]
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [ "tests" ]
