# Generated by Django 3.1.5 on 2021-01-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0005_auto_20210124_1955'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffmodel',
            index=models.Index(fields=['person', 'registration_number', 'start_date'], name='betik_app_s_person__cee6ba_idx'),
        ),
    ]
