
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-28T11:09:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d12ff69c9e61afe504ca7cd06b4cfc90b8390471",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
