[tool.poetry]
name = "cortic"
version = "0.1.0"
description = ""
authors = ["Seth Juarez"]

[tool.poetry.dependencies]
python = "^3.9"
mlflow = "^1.23.1"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cortic = "cortic.cli:cli"