[tool.poetry]
name = "azure-interactive-shortcuts"
version = "0.1.0"
description = "Helpful tools for using Azure resources interactively at the command line"
authors = ["Aatif Syed <aatifsyedyp@gmail.com>"]
repository = "https://github.com/aatifsyed/azure-interactive-shortcuts"
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
argcomplete = "^2.0.0"
logging-actions = "^0.1.6"
rich = "^11.0.0"
dataclasses-json = "^0.5.6"
prompt-toolkit = "^3.0.24"
returns = "^0.18.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
black = "^21.12b0"
mypy = "^0.931"

[tool.poetry.scripts]
azure-interactive-shortcuts = "azure_interactive_shortcuts:_main"
azis = "azure_interactive_shortcuts:_main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
