[tool.cibuildwheel.macos]
before-all = [
    "brew install x265 libjpeg libde265 libheif",
    "HOMEBREW_PREFIX=$(brew --prefix)",
    "REPAIR_LIBRARY_PATH=$HOMEBREW_PREFIX/lib",
    "echo $REPAIR_LIBRARY_PATH",
]

repair-wheel-command = [
    "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-listdeps {wheel}",
    "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel -v --require-archs {delocate_archs} -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.windows]
before-all = [ ]

#set INCLUDE=%INCLUDE%;X:\path\to\libheif\source
#set LIB=%LIB%;X:\path\to\libheif\build
