[tool.poetry]
name = "views_query_planning"
version = "1.3.1"
description = "Generate queries for relational databases"
readme = "README.md"
homepage = "https://www.github.com/prio-data/views_query_planning"
authors = ["peder2911 <pglandsverk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.6.3"
SQLAlchemy = "^1.4.27"
click = "^8.0.3"
psycopg2 = "^2.9.2"
pydot = "^1.4.2"
matplotlib = "^3.5.0"
PyMonad = "^2.4.0"
toolz = "^0.11.2"

[tool.poetry.scripts]
vqp = "views_query_planning.cli:vqp"

[tool.poetry.dev-dependencies]
jedi = "^0.18.0"
pylint = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
