[tool.poetry]
name = "tawnyapi"
version = "0.1.8"
description = ""
authors = ["TAWNY GmbH <support@tawny.ai>"]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
aiohttp = "^3.7.4"
opencv-python = "4.4.0.46"
imutils = "^0.5.4"
toml = "^0.10.2"
aiofiles = "^0.7.0"
numpy = "1.19.5"
tensorflow = "^2.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.7"
pylint = "^2.9.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
