
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-28T16:45:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1fa6b714a18c25674d79c33b3ea1cfdb465067e",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
