# Generated by Django 3.2.11 on 2022-01-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0004_alter_sshhost_port'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portforward',
            options={'verbose_name': '转发', 'verbose_name_plural': '转发'},
        ),
        migrations.AlterModelOptions(
            name='sshhost',
            options={'verbose_name': 'SSH主机', 'verbose_name_plural': 'SSH主机'},
        ),
        migrations.AddField(
            model_name='portforward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portforward',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='portforward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sshhost',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='备注'),
        ),
    ]
