# Generated by Django 3.2.11 on 2022-01-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0005_auto_20220119_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portforward',
            name='lhost',
            field=models.CharField(default='0.0.0.0', max_length=32, verbose_name='本机IP'),
        ),
    ]
