# Generated by Django 3.2.11 on 2022-01-22 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtproxy', '0013_bot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.CharField(blank=True, choices=[('ssh', 'ssh'), ('webshell', 'webshell')], default=None, max_length=64, null=True, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='备注')),
                ('type', models.CharField(blank=True, choices=[('rsa', 'rsa'), ('ed25519', 'ed25519')], default='rsa', max_length=64, null=True, verbose_name='类型')),
                ('privatekey', models.CharField(max_length=4096, verbose_name='私钥值')),
                ('public', models.CharField(max_length=4096, verbose_name='公钥值')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '私钥',
                'verbose_name_plural': '私钥',
            },
        ),
    ]
