# Generated by Django 3.2.11 on 2022-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0019_auto_20220122_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='操作类型')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='操作日志')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间搓')),
            ],
            options={
                'verbose_name': '肉鸡日志',
                'verbose_name_plural': '肉鸡日志',
            },
        ),
    ]
