# Generated by Django 3.2.11 on 2022-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0025_alter_siteconfig_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='onion',
            field=models.CharField(default=None, max_length=70, verbose_name='onion域名'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='onion_key',
            field=models.CharField(default=None, max_length=130, verbose_name='站点onion私钥'),
        ),
    ]
