# Generated by Django 3.2.11 on 2022-01-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0026_auto_20220127_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onion',
            options={'verbose_name': 'onion服务', 'verbose_name_plural': 'onion服务'},
        ),
        migrations.RemoveField(
            model_name='onion',
            name='hs_ed25519_pub_key',
        ),
        migrations.RemoveField(
            model_name='onion',
            name='hs_ed25519_secret_key',
        ),
        migrations.RemoveField(
            model_name='onion',
            name='title',
        ),
        migrations.AddField(
            model_name='onion',
            name='service_port',
            field=models.IntegerField(default=80, verbose_name='服务端口'),
        ),
        migrations.AddField(
            model_name='onion',
            name='tag',
            field=models.CharField(blank=True, default='default', max_length=64, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='onion',
            name='target_host',
            field=models.CharField(default='127.0.0.1', max_length=32, verbose_name='主机名'),
        ),
        migrations.AddField(
            model_name='onion',
            name='target_port',
            field=models.IntegerField(default=80, verbose_name='目标'),
        ),
        migrations.AlterField(
            model_name='onion',
            name='private_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='私钥'),
        ),
    ]
