# coding: utf-8

"""
    external/v1/external_session_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""


import pprint
import re  # noqa: F401
from typing import TYPE_CHECKING

import six

from grid.openapi.configuration import Configuration

if TYPE_CHECKING:
    from datetime import datetime
    from grid.openapi.models import *

class Body3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'object_key': 'str',
        'urls': 'list[V1CompletePresignedUrlUpload]'
    }

    attribute_map = {
        'object_key': 'objectKey',
        'urls': 'urls'
    }

    def __init__(self, object_key: 'str' = None, urls: 'list[V1CompletePresignedUrlUpload]' = None, _configuration=None):  # noqa: E501
        """Body3 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._object_key = None
        self._urls = None
        self.discriminator = None

        if object_key is not None:
            self.object_key = object_key
        if urls is not None:
            self.urls = urls

    @property
    def object_key(self) -> 'str':
        """Gets the object_key of this Body3.  # noqa: E501


        :return: The object_key of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._object_key

    @object_key.setter
    def object_key(self, object_key: 'str'):
        """Sets the object_key of this Body3.


        :param object_key: The object_key of this Body3.  # noqa: E501
        :type: str
        """

        self._object_key = object_key

    @property
    def urls(self) -> 'list[V1CompletePresignedUrlUpload]':
        """Gets the urls of this Body3.  # noqa: E501


        :return: The urls of this Body3.  # noqa: E501
        :rtype: list[V1CompletePresignedUrlUpload]
        """
        return self._urls

    @urls.setter
    def urls(self, urls: 'list[V1CompletePresignedUrlUpload]'):
        """Sets the urls of this Body3.


        :param urls: The urls of this Body3.  # noqa: E501
        :type: list[V1CompletePresignedUrlUpload]
        """

        self._urls = urls

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'Body3') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, Body3):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: 'Body3') -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, Body3):
            return True

        return self.to_dict() != other.to_dict()
