# Generated by Django 3.2.11 on 2022-01-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220118_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '系统用户', 'verbose_name_plural': '系统用户'},
        ),
    ]
