#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['autocar_automate_po']

package_data = \
{'': ['*']}

install_requires = \
['openpyxl', 'pandas', 'pyperclip', 'xlwings']

setup(name='autocar_automate_po',
      version='0.3.3',
      description='autocar_po_automate',
      author='Jean Henstock',
      author_email='jjhenstockwork@gmail.com',
      url='https://github.com/MuseHorizon/autocar_automate_po',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
