[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "python-ourkvm"
module = "ourkvm"
authors = [{name = "Anton Hvornum", email = "anton.feeds+github@gmail.com"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
	"psutil",
	"fastapi",
	"fastapi_resource_server",
	"uvicorn",
	"python-jose[cryptography]",
	"python-multipart",
	"pydantic",
	"systemd",
	"pyjwt"
]

[project.urls]
Home = "https://github.com/Torxed/ourkvm"
Documentation = "https://ourkvm.readthedocs.io/"
Source = "https://github.com/Torxed/ourkvm"

[project.optional-dependencies]
test = [
	"pytest",
	"mypy",
	"flake8",
]

[project.scripts]
ourkvm = "ourkvm:main"

[tool.flit.sdist]
exclude = ["tests/", "test.py"]

[tool.flit.module]
name = "ourkvm"

[tool.mypy]
python_version = "3.10"
exclude = "tests"

[[tool.mypy.overrides]]
module = "fastapi_resource_server.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "psutil.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "systemd.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "uvicorn.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "jwt.*"
ignore_missing_imports = true

[tool.bandit]
targets = ["ourkvm"]
exclude = ["/tests"]
