name: test, Windows, Python 3.10

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python from Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        printenv
        pip install pywin32 pytest wheel pip six numpy pyparsing pytest pytest-cov coverage
        python setup.py install
    - name: Run test suite
      run: |
        cd tests
        pytest
