name: test, Windows, Python 3.7, 3.8, 3.9


on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python from Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        printenv
        conda install pywin32 pytest wheel pip six numpy pyparsing pytest pytest-cov coverage
        conda update -n base -c defaults conda
        conda info
        conda list
        python setup.py install
    - name: Run test suite
      run: |
        cd tests
        pytest
