[tool.poetry]
name = "req_project"
version = "0.1.0"
description = ""
authors = ["Michael Naderhirn <m.naderhirn@nmrobotic.com>"]

[tool.poetry.dependencies]
python = "^3.8"
strictdoc = "^0.0.18"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.12b0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
