/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A tyTuple__JfHvHzMrhKkWAUvQKe0i1A;
typedef struct tyObject_Env_asyncfuturesdotnim_asyncfutures___diB2NTuAIWY0FO9c5IUJRGg tyObject_Env_asyncfuturesdotnim_asyncfutures___diB2NTuAIWY0FO9c5IUJRGg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA;
typedef struct RootObj RootObj;
typedef struct tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct Exception Exception;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w;
typedef struct tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA;
typedef struct tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg;
typedef struct tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw;
typedef struct tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tySequence__aNpJjaoUowCQc7fBn3wtDQ tySequence__aNpJjaoUowCQc7fBn3wtDQ;
typedef struct TSafePoint TSafePoint;
typedef struct GcFrameHeader GcFrameHeader;
typedef struct tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg;
typedef struct tySequence__ZE4llUwluRK7Sqp4MtXogQ tySequence__ZE4llUwluRK7Sqp4MtXogQ;
typedef struct tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ;

/* section: NIM_merge_TYPES */
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyProc__HzVCwACFYM9cx9aV62PdjtuA cbproc, void* ClE_0);
void* ClE_0;
} tyProc__VHS3NdmbwcdcZKmKV1JWhw;
typedef NF tyArray__iV2wVpdhi9coq9cstlcqapXg[2001];
struct tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg {
tyArray__iV2wVpdhi9coq9cstlcqapXg tls;
};
struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A {
void* Field0;
tyObject_Env_asyncfuturesdotnim_asyncfutures___diB2NTuAIWY0FO9c5IUJRGg* Field1;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct RootObj {
TNimType* m_type;
};
struct tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ {
tyProc__HzVCwACFYM9cx9aV62PdjtuA function;
tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA {
  RootObj Sup;
tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
};
struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w {
  tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA Sup;
};
struct tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw {
  tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA Sup;
NI value;
};
typedef N_CLOSURE_PTR(void, TM__vnqLhdH9cCREQ2r9aXVOqbvQ_6) (void);
typedef N_CLOSURE_PTR(void, TM__vnqLhdH9cCREQ2r9aXVOqbvQ_7) (tyProc__HzVCwACFYM9cx9aV62PdjtuA cbproc);
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
CRITICAL_SECTION lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
struct tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA {
  tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA Sup;
NIM_BOOL value;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future, void* ClE_0);
void* ClE_0;
} tyProc__yO64b9bIq9a3QrGi0ZNirrVg;
struct tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg {
  RootObj Sup;
NI colonstate_;
tyProc__yO64b9bIq9a3QrGi0ZNirrVg cb1;
tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future2;
};
typedef N_CLOSURE_PTR(void, TM__vnqLhdH9cCREQ2r9aXVOqbvQ_13) (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
struct tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw {
  tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA Sup;
NimStringDesc* value;
};
struct tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA {
  RootObj Sup;
NI colonstate_;
tyProc__yO64b9bIq9a3QrGi0ZNirrVg cb1;
tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future2;
};
typedef N_CLOSURE_PTR(void, TM__vnqLhdH9cCREQ2r9aXVOqbvQ_15) (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef NU8 tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg;

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence__aNpJjaoUowCQc7fBn3wtDQ {
  TGenericSeq Sup;
  tyProc__HzVCwACFYM9cx9aV62PdjtuA data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__ZE4llUwluRK7Sqp4MtXogQ {
  TGenericSeq Sup;
  tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* data[SEQ_DECL_SIZE];
};
typedef struct {tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg;
tySequence__aNpJjaoUowCQc7fBn3wtDQ* threadDestructionHandlers__8OmU3x0fNdA0DLtOmU3kWw;
NI threadId__wzrdPYhtL9czkCWS4o9an9cRw;
TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
GcFrameHeader* gcFramePtr__ot48iojqko9aFxGhyjjjVaA;
tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* utcInstance__oeKVHn4dFpBJO35HhEkelw;
tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* localInstance__cLtN9cK9bCe6IPhJ3UFNLNKA;
NIM_BOOL envComputed__LLyFo9bsdu1ZXMDvAe8DhrQ;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* environment__mlhK49b6YMgc9cgrcYkKq9a3g;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* ownArgv__WVJ54JSHy7VxacV39bwBPFA;
NIM_BOOL ownParsedArgv__9btHydaUC5pNXxitEZsyzIg;
tyProc__VHS3NdmbwcdcZKmKV1JWhw callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A;
tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg* gDisp__yIbBArLUsg2pBJkilx4yvg;
tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level__hzbRBHMSEnpbC61ptpdKmA;
tySequence__ZE4llUwluRK7Sqp4MtXogQ* handlers__OpA9asfHAsjfRTcLDwhkNfA;
NIM_BOOL pyThreadFrameInited__0LBR4zzVR5uWvgtv8SrMjg;
NIM_BOOL gcInited__uuy3PWTwb5gov9ao9bXJYBPg;
NIM_BOOL isSlave__t9a8wsVVRYqGEKhg1vb49b3g;
NIM_BOOL loggingEnabled__yLPNLBe6VZ6N8qtL17YAKw;
} NimThreadVars;

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void*, GetThreadLocalVars)(void);
N_LIB_PRIVATE N_NIMCALL(void*, threadVarGetValue__O8VJSmwa3WY6y9bP6Ht9b7hw)(NI32 dwTlsIndex);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__vnqLhdH9cCREQ2r9aXVOqbvQ_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_tyRef__gcUT3qWwCET3KjsqW7m5vQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__TjokxNjmnZmr9bygVDVC9bvg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__kYv5uOSTaUb7hZbxPjTMHA_2)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
N_LIB_PRIVATE N_NIMCALL(void, call__9aC4x4HZu9cvj9bSIhJIDHvOw)(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* callbacks);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, callSoon__59aAW5mR4py7a24tTI1dxTg)(tyProc__HzVCwACFYM9cx9aV62PdjtuA cbproc);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__UI9a1IK9aM6lVG9bkQfkm9ajFA)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_NIMCALL(void, Marker_tyRef__zQLn9bxNxVo9bLicuaF3xeGg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__G3WIkXk4MjMLVyyUid6IEw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__kYv5uOSTaUb7hZbxPjTMHA_4)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future);
static N_NIMCALL(void, Marker_tyRef__WTGU9aH9aqemaOVZXD0yOniQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStackTrace__UTyxM84G9cIKwBP74ZFOh4A)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStackTrace__wZiNbtaUL82bHwwHPZjV9cQ)(void);
static N_NIMCALL(void, Marker_tyRef__JBzpn7BwubwoL9chYMetyPQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, callbackeq___LPYaMz3j7An9cL9cbuTYEaOQ)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future, tyProc__HzVCwACFYM9cx9aV62PdjtuA cb);
N_LIB_PRIVATE N_NIMCALL(void, clearCallbacks__JrpOmbFvHBwR9bGEIvY0WRA)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future);
N_LIB_PRIVATE N_NIMCALL(void, addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future, tyProc__HzVCwACFYM9cx9aV62PdjtuA cb);
N_LIB_PRIVATE N_NIMCALL(void, add__3lfRybo9baDqdgY6X2lVb8A)(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* callbacks, tyProc__HzVCwACFYM9cx9aV62PdjtuA function);
N_LIB_PRIVATE N_NIMCALL(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*, new__vaYrsahwlOcnisvj9ahpVuw)(void);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___MN9arTQq9bY9b1kq7Q44vu10g)(void* ClE_0);
static N_NIMCALL(void, Marker_tyRef__PGriAzqlEWabm3KuP9cPwnw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__jc4vkU8a9cL5JnMQ0yUdkrg)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__jc4vkU8a9cL5JnMQ0yUdkrg_2)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__SqD59c8b9bcuMkGYODa9blPzQ)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__SqD59c8b9bcuMkGYODa9blPzQ_2)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future);
static N_NIMCALL(void, Marker_tyRef__dIasvr4vOc9aM8N0sR9bpVng)(void* p, NI op);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___MN9arTQq9bY9b1kq7Q44vu10g_2)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*, newFuture__0JOdLmTwOL3FpMJAn3k6Qg)(NimStringDesc* fromProc);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__UI9a1IK9aM6lVG9bkQfkm9ajFA_2)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE TNimType NTI__VHS3NdmbwcdcZKmKV1JWhw_;
extern TNimType NTI__vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI__HsJiUUcO9cHBdUCi0HwkSTA_;
extern TNimType NTI__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTI__NMMT5akQkfNlmjYrVF9a9bwA_;
N_LIB_PRIVATE TNimType NTI__tKSBWiaJMWD3JZxwqg7UFQ_;
extern TNimType NTI__HzVCwACFYM9cx9aV62PdjtuA_;
N_LIB_PRIVATE TNimType NTI__gcUT3qWwCET3KjsqW7m5vQ_;
extern TNimType NTI__VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI__vU9aO9cTqOMn6CBzhV8rX7Sw_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTI__te3W2Tqi7xuJ7rlPtg9al5w_;
N_LIB_PRIVATE TNimType NTI__TjokxNjmnZmr9bygVDVC9bvg_;
static NIM_CONST tyProc__HzVCwACFYM9cx9aV62PdjtuA TM__vnqLhdH9cCREQ2r9aXVOqbvQ_8 = {NIM_NIL,NIM_NIL};
extern TNimType NTI__Ie1m0dv1ZHg72IgPRr1cDw_;
extern TNimType NTI__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__vnqLhdH9cCREQ2r9aXVOqbvQ_9, "Future still in progress.", 25);
N_LIB_PRIVATE TNimType NTI__4BPh0tr2SlV8S9bKCszC19aw_;
extern TNimType NTI__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTI__zQLn9bxNxVo9bLicuaF3xeGg_;
N_LIB_PRIVATE TNimType NTI__G3WIkXk4MjMLVyyUid6IEw_;
N_LIB_PRIVATE TNimType NTI__MoyhMJWEHe6l39ajVP2YSWA_;
N_LIB_PRIVATE TNimType NTI__WTGU9aH9aqemaOVZXD0yOniQ_;
STRING_LITERAL(TM__vnqLhdH9cCREQ2r9aXVOqbvQ_10, "No error in future.", 19);
N_LIB_PRIVATE TNimType NTI__RDCVAUcZinb9aLgfyV8niJg_;
extern TNimType NTI__xHTZrq9aYs6boc9bCba0JbpQ_;
N_LIB_PRIVATE TNimType NTI__yO64b9bIq9a3QrGi0ZNirrVg_;
N_LIB_PRIVATE TNimType NTI__JBzpn7BwubwoL9chYMetyPQ_;
N_LIB_PRIVATE TNimType NTI__DytvWkqCHojL9aGfYktbFPw_;
N_LIB_PRIVATE TNimType NTI__PGriAzqlEWabm3KuP9cPwnw_;
N_LIB_PRIVATE TNimType NTI__SOfwXWONSsDuJaBnMvgifA_;
N_LIB_PRIVATE TNimType NTI__dIasvr4vOc9aM8N0sR9bpVng_;

/* section: NIM_merge_VARS */
extern NI32 globalsSlot__ciXDZu9c27pHpCRMoz4RIgw;

/* section: NIM_merge_PROCS */
static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue__O8VJSmwa3WY6y9bP6Ht9b7hw(globalsSlot__ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}
static N_NIMCALL(void, TM__vnqLhdH9cCREQ2r9aXVOqbvQ_3)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	nimGCvisit((void*)NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClE_0, 0);
}
static N_NIMCALL(void, Marker_tyRef__gcUT3qWwCET3KjsqW7m5vQ)(void* p, NI op) {
	tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* a;
	a = (tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*)p;
	nimGCvisit((void*)(*a).function.ClE_0, op);
	nimGCvisit((void*)(*a).next, op);
}
static N_NIMCALL(void, Marker_tyRef__TjokxNjmnZmr9bygVDVC9bvg)(void* p, NI op) {
	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* a;
	a = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
}
N_LIB_PRIVATE N_NIMCALL(void, getCallSoonProc__IcnBX6Z0sCLxeCWCBwYPig)(tyProc__VHS3NdmbwcdcZKmKV1JWhw* Result) {
	NimThreadVars* NimTV_;
{	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	unsureAsgnRef((void**) (&(*Result).ClE_0), NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClE_0);
	(*Result).ClP_0 = NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClP_0;
	goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setCallSoonProc__EYbXvk9cDaL2C9b1nm4S2ZcQ)(tyProc__VHS3NdmbwcdcZKmKV1JWhw p) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	unsureAsgnRef((void**) (&NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClE_0), p.ClE_0);
	NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClP_0 = p.ClP_0;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__Wp5rEj9c2EOy9a59aS0FBRLuQ)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).Sup.finished;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__kYv5uOSTaUb7hZbxPjTMHA_2)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future) {
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, callSoon__59aAW5mR4py7a24tTI1dxTg)(tyProc__HzVCwACFYM9cx9aV62PdjtuA cbproc) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	{
		if (!(NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClP_0 == 0)) goto LA3_;
		cbproc.ClE_0? cbproc.ClP_0(cbproc.ClE_0):((TM__vnqLhdH9cCREQ2r9aXVOqbvQ_6)(cbproc.ClP_0))();
	}
	goto LA1_;
	LA3_: ;
	{
		NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClE_0? NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClP_0(cbproc, NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClE_0):((TM__vnqLhdH9cCREQ2r9aXVOqbvQ_7)(NimTV_->callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A.ClP_0))(cbproc);
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, call__9aC4x4HZu9cvj9bSIhJIDHvOw)(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* callbacks) {
	tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ current;
	nimZeroMem((void*)(&current), sizeof(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ));
	current.function.ClE_0 = (*callbacks).function.ClE_0;
	current.function.ClP_0 = (*callbacks).function.ClP_0;
	current.next = (*callbacks).next;
	{
		while (1) {
			{
				if (!!((current.function.ClP_0 == 0))) goto LA5_;
				callSoon__59aAW5mR4py7a24tTI1dxTg(current.function);
			}
			LA5_: ;
			{
				if (!(current.next == 0)) goto LA9_;
				goto LA1;
			}
			goto LA7_;
			LA9_: ;
			{
				current.function.ClE_0 = (*current.next).function.ClE_0;
				current.function.ClP_0 = (*current.next).function.ClP_0;
				current.next = (*current.next).next;
			}
			LA7_: ;
		}
	} LA1: ;
	unsureAsgnRef((void**) (&(*callbacks).next), ((tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*) NIM_NIL));
	unsureAsgnRef((void**) (&(*callbacks).function.ClE_0), TM__vnqLhdH9cCREQ2r9aXVOqbvQ_8.ClE_0);
	(*callbacks).function.ClP_0 = TM__vnqLhdH9cCREQ2r9aXVOqbvQ_8.ClP_0;
}
N_LIB_PRIVATE N_NIMCALL(void, complete__kYv5uOSTaUb7hZbxPjTMHA)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future) {
	checkFinished__kYv5uOSTaUb7hZbxPjTMHA_2(future);
	(*future).Sup.finished = NIM_TRUE;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__UI9a1IK9aM6lVG9bkQfkm9ajFA)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future) {
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&NimTV_->gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
}
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system(c);
	}
	LA4_: ;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
	decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T1_);
}
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef__AT1eRuflKWyTTBdLjEDZbg_3system(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(NI, read__k4tsdod5LrpwMTXX61cEoA)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future) {
	NI result;
	tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* fut;
	result = (NI)0;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == ((Exception*) NIM_NIL)))) goto LA7_;
			injectStacktrace__UI9a1IK9aM6lVG9bkQfkm9ajFA(fut);
			raiseExceptionEx((Exception*)(*fut).Sup.error, "Exception", "read", "asyncfutures.nim", 372);
		}
		LA7_: ;
		result = (*fut).value;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T10_;
		NimStringDesc* T11_;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T10_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);
		(*T10_).Sup.Sup.name = "ValueError";
		T11_ = (NimStringDesc*)0;
		T11_ = (*T10_).Sup.Sup.message; (*T10_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_9));
		if (T11_) nimGCunrefNoCycle(T11_);
		asgnRef((void**) (&(*T10_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T10_, "ValueError", "read", "asyncfutures.nim", 377);
	}
	LA1_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__zQLn9bxNxVo9bLicuaF3xeGg)(void* p, NI op) {
	tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* a;
	a = (tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw*, newFuture__tyNAjKVXvale9aem9cvenvKg)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* result;
	result = (tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw*)0;
	result = (tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw*) newObj((&NTI__zQLn9bxNxVo9bLicuaF3xeGg_), sizeof(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw));
	(*result).Sup.Sup.m_type = (&NTI__4BPh0tr2SlV8S9bKCszC19aw_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__G3WIkXk4MjMLVyyUid6IEw)(void* p, NI op) {
	tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* a;
	a = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)p;
	nimGCvisit((void*)(*a).callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).callbacks.next, op);
	nimGCvisit((void*)(*a).error, op);
	nimGCvisit((void*)(*a).errorStackTrace, op);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__zLPHIdTAe2mgu9c9c1y5dGIQ)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).Sup.finished;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__kYv5uOSTaUb7hZbxPjTMHA_4)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future) {
}
N_LIB_PRIVATE N_NIMCALL(void, read__kYv5uOSTaUb7hZbxPjTMHA_3)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future) {
	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* fut;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == ((Exception*) NIM_NIL)))) goto LA7_;
			injectStacktrace__kYv5uOSTaUb7hZbxPjTMHA_4(fut);
			raiseExceptionEx((Exception*)(*fut).Sup.error, "Exception", "read", "asyncfutures.nim", 372);
		}
		LA7_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T10_;
		NimStringDesc* T11_;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T10_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);
		(*T10_).Sup.Sup.name = "ValueError";
		T11_ = (NimStringDesc*)0;
		T11_ = (*T10_).Sup.Sup.message; (*T10_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_9));
		if (T11_) nimGCunrefNoCycle(T11_);
		asgnRef((void**) (&(*T10_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T10_, "ValueError", "read", "asyncfutures.nim", 377);
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*, newFuture__O5FiTIx7b9aJMbTMTl7J2SQ)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* result;
	result = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*)0;
	result = (tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*) newObj((&NTI__TjokxNjmnZmr9bygVDVC9bvg_), sizeof(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w));
	(*result).Sup.Sup.m_type = (&NTI__te3W2Tqi7xuJ7rlPtg9al5w_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__WTGU9aH9aqemaOVZXD0yOniQ)(void* p, NI op) {
	tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* a;
	a = (tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, failed__Cn8FMZpHNs40shvQ9cZz69aA)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	result = !(((*future).error == ((Exception*) NIM_NIL)));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(Exception*, readError__Wyb4rXkn0bNgtIL8rrfk2g)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future) {
	Exception* result;
{	result = (Exception*)0;
	{
		if (!!(((*future).Sup.error == ((Exception*) NIM_NIL)))) goto LA3_;
		result = (*future).Sup.error;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T6_;
		NimStringDesc* T7_;
		T6_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
		T6_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);
		(*T6_).Sup.Sup.name = "ValueError";
		T7_ = (NimStringDesc*)0;
		T7_ = (*T6_).Sup.Sup.message; (*T6_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_10));
		if (T7_) nimGCunrefNoCycle(T7_);
		asgnRef((void**) (&(*T6_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T6_, "ValueError", "readError", "asyncfutures.nim", 386);
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fail__KP9b34veEV0ehqMJglv63VQ)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future, Exception* error) {
	checkFinished__kYv5uOSTaUb7hZbxPjTMHA_2(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error);
		if (!((T3_ ? T3_->Sup.len : 0) == 0)) goto LA4_;
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__wZiNbtaUL82bHwwHPZjV9cQ());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error));
	}
	LA1_: ;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
static N_NIMCALL(void, Marker_tyRef__JBzpn7BwubwoL9chYMetyPQ)(void* p, NI op) {
	tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg* a;
	a = (tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg*)p;
	nimGCvisit((void*)(*a).cb1.ClE_0, op);
	nimGCvisit((void*)(*a).future2, op);
}
N_LIB_PRIVATE N_NIMCALL(void, clearCallbacks__JrpOmbFvHBwR9bGEIvY0WRA)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future) {
	asgnRef((void**) (&(*future).callbacks.function.ClE_0), TM__vnqLhdH9cCREQ2r9aXVOqbvQ_8.ClE_0);
	(*future).callbacks.function.ClP_0 = TM__vnqLhdH9cCREQ2r9aXVOqbvQ_8.ClP_0;
	asgnRef((void**) (&(*future).callbacks.next), ((tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*) NIM_NIL));
}
N_LIB_PRIVATE N_NIMCALL(void, add__3lfRybo9baDqdgY6X2lVb8A)(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* callbacks, tyProc__HzVCwACFYM9cx9aV62PdjtuA function) {
	{
		if (!((*callbacks).function.ClP_0 == 0)) goto LA3_;
		unsureAsgnRef((void**) (&(*callbacks).function.ClE_0), function.ClE_0);
		(*callbacks).function.ClP_0 = function.ClP_0;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* newCallback;
		newCallback = new__vaYrsahwlOcnisvj9ahpVuw();
		asgnRef((void**) (&(*newCallback).function.ClE_0), function.ClE_0);
		(*newCallback).function.ClP_0 = function.ClP_0;
		asgnRef((void**) (&(*newCallback).next), ((tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*) NIM_NIL));
		{
			if (!((*callbacks).next == ((tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*) NIM_NIL))) goto LA8_;
			unsureAsgnRef((void**) (&(*callbacks).next), newCallback);
		}
		goto LA6_;
		LA8_: ;
		{
			tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ* last;
			last = (*callbacks).next;
			{
				while (1) {
					if (!!(((*last).next == ((tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*) NIM_NIL)))) goto LA12;
					last = (*last).next;
				} LA12: ;
			}
			asgnRef((void**) (&(*last).next), newCallback);
		}
		LA6_: ;
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future, tyProc__HzVCwACFYM9cx9aV62PdjtuA cb) {
	{
		if (!(*future).finished) goto LA3_;
		callSoon__59aAW5mR4py7a24tTI1dxTg(cb);
	}
	goto LA1_;
	LA3_: ;
	{
		add__3lfRybo9baDqdgY6X2lVb8A((&(*future).callbacks), cb);
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, callbackeq___LPYaMz3j7An9cL9cbuTYEaOQ)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future, tyProc__HzVCwACFYM9cx9aV62PdjtuA cb) {
	clearCallbacks__JrpOmbFvHBwR9bGEIvY0WRA(future);
	addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2(future, cb);
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___MN9arTQq9bY9b1kq7Q44vu10g)(void* ClE_0) {
	tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg* colonenvP_;
	colonenvP_ = (tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg*) ClE_0;
	(*colonenvP_).cb1.ClE_0? (*colonenvP_).cb1.ClP_0((*colonenvP_).future2, (*colonenvP_).cb1.ClE_0):((TM__vnqLhdH9cCREQ2r9aXVOqbvQ_13)((*colonenvP_).cb1.ClP_0))((*colonenvP_).future2);
}
N_LIB_PRIVATE N_NIMCALL(void, callbackeq___SIq9aKuDcyPwaqfFSH7w1Lw)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future, tyProc__yO64b9bIq9a3QrGi0ZNirrVg cb) {
	tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg* colonenv_;
	tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* T1_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T2_;
	colonenv_ = (tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg*)0;
	colonenv_ = (tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg*) newObj((&NTI__JBzpn7BwubwoL9chYMetyPQ_), sizeof(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg));
	(*colonenv_).Sup.m_type = (&NTI__RDCVAUcZinb9aLgfyV8niJg_);
	asgnRef((void**) (&(*colonenv_).future2), future);
	asgnRef((void**) (&(*colonenv_).cb1.ClE_0), cb.ClE_0);
	(*colonenv_).cb1.ClP_0 = cb.ClP_0;
	T1_ = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;
	T1_ = &(*colonenv_).future2->Sup;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T2_.ClP_0 = colonanonymous___MN9arTQq9bY9b1kq7Q44vu10g; T2_.ClE_0 = colonenv_;
	callbackeq___LPYaMz3j7An9cL9cbuTYEaOQ(T1_, T2_);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__Cn8FMZpHNs40shvQ9cZz69aA_2)(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).finished;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA*, newFuture__whxT9bNj3YP19coMA8DxFVSw)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* result;
	result = (tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA*)0;
	result = (tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA*) newObj((&NTI__WTGU9aH9aqemaOVZXD0yOniQ_), sizeof(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA));
	(*result).Sup.Sup.m_type = (&NTI__MoyhMJWEHe6l39ajVP2YSWA_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__PGriAzqlEWabm3KuP9cPwnw)(void* p, NI op) {
	tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* a;
	a = (tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
	nimGCvisit((void*)(*a).value, op);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*, newFuture__0JOdLmTwOL3FpMJAn3k6Qg)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* result;
	result = (tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*)0;
	result = (tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*) newObj((&NTI__PGriAzqlEWabm3KuP9cPwnw_), sizeof(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw));
	(*result).Sup.Sup.m_type = (&NTI__DytvWkqCHojL9aGfYktbFPw_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__3fkP1fU9aS9bV6HeIXEWDkAA)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).Sup.finished;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__jc4vkU8a9cL5JnMQ0yUdkrg)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future) {
}
N_LIB_PRIVATE N_NIMCALL(void, complete__emkcSSMulxV6plj59amRXdw)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future, NimStringDesc* val) {
	NimStringDesc* T1_;
	checkFinished__jc4vkU8a9cL5JnMQ0yUdkrg(future);
	T1_ = (NimStringDesc*)0;
	T1_ = (*future).value; (*future).value = copyStringRC1(val);
	if (T1_) nimGCunrefNoCycle(T1_);
	(*future).Sup.finished = NIM_TRUE;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(void, fail__sE9bB9bP7Et9ajfmLBG9cWkSSw)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future, Exception* error) {
	checkFinished__jc4vkU8a9cL5JnMQ0yUdkrg(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error);
		if (!((T3_ ? T3_->Sup.len : 0) == 0)) goto LA4_;
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__wZiNbtaUL82bHwwHPZjV9cQ());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error));
	}
	LA1_: ;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__jc4vkU8a9cL5JnMQ0yUdkrg_2)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future) {
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, read__S5Pgt6us40MmEQwQytOYLA)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future) {
	NimStringDesc* result;
	tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* fut;
	result = (NimStringDesc*)0;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == ((Exception*) NIM_NIL)))) goto LA7_;
			injectStacktrace__jc4vkU8a9cL5JnMQ0yUdkrg_2(fut);
			raiseExceptionEx((Exception*)(*fut).Sup.error, "Exception", "read", "asyncfutures.nim", 372);
		}
		LA7_: ;
		result = copyString((*fut).value);
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T10_;
		NimStringDesc* T11_;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T10_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);
		(*T10_).Sup.Sup.name = "ValueError";
		T11_ = (NimStringDesc*)0;
		T11_ = (*T10_).Sup.Sup.message; (*T10_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_9));
		if (T11_) nimGCunrefNoCycle(T11_);
		asgnRef((void**) (&(*T10_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T10_, "ValueError", "read", "asyncfutures.nim", 377);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__SqD59c8b9bcuMkGYODa9blPzQ)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future) {
}
N_LIB_PRIVATE N_NIMCALL(void, complete__3Jv5kbUc6Bo9aCgf6CD9cNuw)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future, NIM_BOOL val) {
	checkFinished__SqD59c8b9bcuMkGYODa9blPzQ(future);
	(*future).value = val;
	(*future).Sup.finished = NIM_TRUE;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__fwA9b5NfP9a1QL9cjd9cp9cEQgw)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).Sup.finished;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fail__jxN9bUJkdb5lnzElz9bnP49bg)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future, Exception* error) {
	checkFinished__SqD59c8b9bcuMkGYODa9blPzQ(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error);
		if (!((T3_ ? T3_->Sup.len : 0) == 0)) goto LA4_;
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__wZiNbtaUL82bHwwHPZjV9cQ());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error));
	}
	LA1_: ;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace__SqD59c8b9bcuMkGYODa9blPzQ_2)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future) {
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, read__fwA9b5NfP9a1QL9cjd9cp9cEQgw_2)(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* future) {
	NIM_BOOL result;
	tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA* fut;
	result = (NIM_BOOL)0;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == ((Exception*) NIM_NIL)))) goto LA7_;
			injectStacktrace__SqD59c8b9bcuMkGYODa9blPzQ_2(fut);
			raiseExceptionEx((Exception*)(*fut).Sup.error, "Exception", "read", "asyncfutures.nim", 372);
		}
		LA7_: ;
		result = (*fut).value;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T10_;
		NimStringDesc* T11_;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
		T10_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T10_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);
		(*T10_).Sup.Sup.name = "ValueError";
		T11_ = (NimStringDesc*)0;
		T11_ = (*T10_).Sup.Sup.message; (*T10_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_9));
		if (T11_) nimGCunrefNoCycle(T11_);
		asgnRef((void**) (&(*T10_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T10_, "ValueError", "read", "asyncfutures.nim", 377);
	}
	LA1_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__dIasvr4vOc9aM8N0sR9bpVng)(void* p, NI op) {
	tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA* a;
	a = (tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA*)p;
	nimGCvisit((void*)(*a).cb1.ClE_0, op);
	nimGCvisit((void*)(*a).future2, op);
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___MN9arTQq9bY9b1kq7Q44vu10g_2)(void* ClE_0) {
	tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA* colonenvP_;
	colonenvP_ = (tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA*) ClE_0;
	(*colonenvP_).cb1.ClE_0? (*colonenvP_).cb1.ClP_0((*colonenvP_).future2, (*colonenvP_).cb1.ClE_0):((TM__vnqLhdH9cCREQ2r9aXVOqbvQ_15)((*colonenvP_).cb1.ClP_0))((*colonenvP_).future2);
}
N_LIB_PRIVATE N_NIMCALL(void, addCallback__SIq9aKuDcyPwaqfFSH7w1Lw_2)(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* future, tyProc__yO64b9bIq9a3QrGi0ZNirrVg cb) {
	tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA* colonenv_;
	tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* T1_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T2_;
	colonenv_ = (tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA*)0;
	colonenv_ = (tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA*) newObj((&NTI__dIasvr4vOc9aM8N0sR9bpVng_), sizeof(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA));
	(*colonenv_).Sup.m_type = (&NTI__SOfwXWONSsDuJaBnMvgifA_);
	asgnRef((void**) (&(*colonenv_).future2), future);
	asgnRef((void**) (&(*colonenv_).cb1.ClE_0), cb.ClE_0);
	(*colonenv_).cb1.ClP_0 = cb.ClP_0;
	T1_ = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;
	T1_ = &(*colonenv_).future2->Sup;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T2_.ClP_0 = colonanonymous___MN9arTQq9bY9b1kq7Q44vu10g_2; T2_.ClE_0 = colonenv_;
	addCallback__LPYaMz3j7An9cL9cbuTYEaOQ_2(T1_, T2_);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*, newFutureVar__XDPsxWPxi0l6fpPZSAM3yw)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* result;
	tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* fo;
	result = (tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*)0;
	fo = newFuture__0JOdLmTwOL3FpMJAn3k6Qg(fromProc);
	result = fo;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, mget__7CwNWaZC5K9cVRW7yaonRUQ)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future) {
	NimStringDesc** result;
	result = (NimStringDesc**)0;
	result = (&(*future).value);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkFinished__UI9a1IK9aM6lVG9bkQfkm9ajFA_2)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future) {
}
N_LIB_PRIVATE N_NIMCALL(void, complete__ak5IxdrxP5gm9bkexgjswhw)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future, NI val) {
	checkFinished__UI9a1IK9aM6lVG9bkQfkm9ajFA_2(future);
	(*future).value = val;
	(*future).Sup.finished = NIM_TRUE;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(void, fail__3QjCdv4ktuqlPYtaWUqJsA)(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw* future, Exception* error) {
	checkFinished__UI9a1IK9aM6lVG9bkQfkm9ajFA_2(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error);
		if (!((T3_ ? T3_->Sup.len : 0) == 0)) goto LA4_;
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__wZiNbtaUL82bHwwHPZjV9cQ());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRef((void**) (&(*future).Sup.errorStackTrace), getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(error));
	}
	LA1_: ;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(void, complete__EISjcvTkgqY9cabUcJjrfzg)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future) {
	checkFinished__jc4vkU8a9cL5JnMQ0yUdkrg(future);
	(*future).Sup.finished = NIM_TRUE;
	call__9aC4x4HZu9cvj9bSIhJIDHvOw((&(*future).Sup.callbacks));
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__dQRRMddlobcFXlKS9aHSPxw)(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw* future) {
	NIM_BOOL result;
	tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA* T1_;
	result = (NIM_BOOL)0;
	T1_ = (tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*)0;
	T1_ = &future->Sup;
	result = (*T1_).finished;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncfuturesInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();

	nimRegisterThreadLocalMarker(TM__vnqLhdH9cCREQ2r9aXVOqbvQ_3);

}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_asyncfuturesDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__vnqLhdH9cCREQ2r9aXVOqbvQ_2_2[2];
static TNimNode* TM__vnqLhdH9cCREQ2r9aXVOqbvQ_4_4[4];
static TNimNode* TM__vnqLhdH9cCREQ2r9aXVOqbvQ_5_2[2];
static TNimNode* TM__vnqLhdH9cCREQ2r9aXVOqbvQ_11_3[3];
static TNimNode* TM__vnqLhdH9cCREQ2r9aXVOqbvQ_12_2[2];
static TNimNode* TM__vnqLhdH9cCREQ2r9aXVOqbvQ_14_3[3];
static TNimNode TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[26];

/* section: NIM_merge_TYPE_INIT3 */
NTI__VHS3NdmbwcdcZKmKV1JWhw_.size = sizeof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTI__VHS3NdmbwcdcZKmKV1JWhw_.align = NIM_ALIGNOF(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTI__VHS3NdmbwcdcZKmKV1JWhw_.kind = 18;
NTI__VHS3NdmbwcdcZKmKV1JWhw_.base = 0;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_2_2[0] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[1];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field0);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].name = "Field0";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_2_2[1] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[2];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field1);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].typ = (&NTI__HsJiUUcO9cHBdUCi0HwkSTA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].name = "Field1";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[0].len = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[0].kind = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[0].sons = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_2_2[0];
NTI__VHS3NdmbwcdcZKmKV1JWhw_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[0];
NTI__NMMT5akQkfNlmjYrVF9a9bwA_.size = sizeof(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA);
NTI__NMMT5akQkfNlmjYrVF9a9bwA_.align = NIM_ALIGNOF(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA);
NTI__NMMT5akQkfNlmjYrVF9a9bwA_.kind = 17;
NTI__NMMT5akQkfNlmjYrVF9a9bwA_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_4_4[0] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[4];
NTI__tKSBWiaJMWD3JZxwqg7UFQ_.size = sizeof(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ);
NTI__tKSBWiaJMWD3JZxwqg7UFQ_.align = NIM_ALIGNOF(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ);
NTI__tKSBWiaJMWD3JZxwqg7UFQ_.kind = 18;
NTI__tKSBWiaJMWD3JZxwqg7UFQ_.base = 0;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_5_2[0] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[6];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[6].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[6].offset = offsetof(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ, function);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[6].typ = (&NTI__HzVCwACFYM9cx9aV62PdjtuA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[6].name = "function";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_5_2[1] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[7];
NTI__gcUT3qWwCET3KjsqW7m5vQ_.size = sizeof(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*);
NTI__gcUT3qWwCET3KjsqW7m5vQ_.align = NIM_ALIGNOF(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ*);
NTI__gcUT3qWwCET3KjsqW7m5vQ_.kind = 22;
NTI__gcUT3qWwCET3KjsqW7m5vQ_.base = (&NTI__tKSBWiaJMWD3JZxwqg7UFQ_);
NTI__gcUT3qWwCET3KjsqW7m5vQ_.marker = Marker_tyRef__gcUT3qWwCET3KjsqW7m5vQ;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].offset = offsetof(tyObject_CallbackList__tKSBWiaJMWD3JZxwqg7UFQ, next);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].typ = (&NTI__gcUT3qWwCET3KjsqW7m5vQ_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].name = "next";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[5].len = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[5].kind = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[5].sons = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_5_2[0];
NTI__tKSBWiaJMWD3JZxwqg7UFQ_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[5];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[4].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[4].offset = offsetof(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA, callbacks);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[4].typ = (&NTI__tKSBWiaJMWD3JZxwqg7UFQ_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[4].name = "callbacks";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_4_4[1] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[8];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[8].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[8].offset = offsetof(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA, finished);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[8].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[8].name = "finished";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_4_4[2] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[9];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].offset = offsetof(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA, error);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].typ = (&NTI__vU9aO9cTqOMn6CBzhV8rX7Sw_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].name = "error";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_4_4[3] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[10];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].offset = offsetof(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA, errorStackTrace);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].name = "errorStackTrace";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[3].len = 4; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[3].kind = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[3].sons = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_4_4[0];
NTI__NMMT5akQkfNlmjYrVF9a9bwA_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[3];
NTI__te3W2Tqi7xuJ7rlPtg9al5w_.size = sizeof(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w);
NTI__te3W2Tqi7xuJ7rlPtg9al5w_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w);
NTI__te3W2Tqi7xuJ7rlPtg9al5w_.kind = 17;
NTI__te3W2Tqi7xuJ7rlPtg9al5w_.base = (&NTI__NMMT5akQkfNlmjYrVF9a9bwA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[11].len = 0; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[11].kind = 2;
NTI__te3W2Tqi7xuJ7rlPtg9al5w_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[11];
NTI__TjokxNjmnZmr9bygVDVC9bvg_.size = sizeof(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*);
NTI__TjokxNjmnZmr9bygVDVC9bvg_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w*);
NTI__TjokxNjmnZmr9bygVDVC9bvg_.kind = 22;
NTI__TjokxNjmnZmr9bygVDVC9bvg_.base = (&NTI__te3W2Tqi7xuJ7rlPtg9al5w_);
NTI__TjokxNjmnZmr9bygVDVC9bvg_.marker = Marker_tyRef__TjokxNjmnZmr9bygVDVC9bvg;
NTI__4BPh0tr2SlV8S9bKCszC19aw_.size = sizeof(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw);
NTI__4BPh0tr2SlV8S9bKCszC19aw_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw);
NTI__4BPh0tr2SlV8S9bKCszC19aw_.kind = 17;
NTI__4BPh0tr2SlV8S9bKCszC19aw_.base = (&NTI__NMMT5akQkfNlmjYrVF9a9bwA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].offset = offsetof(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw, value);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].name = "value";
NTI__4BPh0tr2SlV8S9bKCszC19aw_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[12];
NTI__zQLn9bxNxVo9bLicuaF3xeGg_.size = sizeof(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw*);
NTI__zQLn9bxNxVo9bLicuaF3xeGg_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___4BPh0tr2SlV8S9bKCszC19aw*);
NTI__zQLn9bxNxVo9bLicuaF3xeGg_.kind = 22;
NTI__zQLn9bxNxVo9bLicuaF3xeGg_.base = (&NTI__4BPh0tr2SlV8S9bKCszC19aw_);
NTI__zQLn9bxNxVo9bLicuaF3xeGg_.marker = Marker_tyRef__zQLn9bxNxVo9bLicuaF3xeGg;
NTI__G3WIkXk4MjMLVyyUid6IEw_.size = sizeof(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*);
NTI__G3WIkXk4MjMLVyyUid6IEw_.align = NIM_ALIGNOF(tyObject_FutureBasecolonObjectType___NMMT5akQkfNlmjYrVF9a9bwA*);
NTI__G3WIkXk4MjMLVyyUid6IEw_.kind = 22;
NTI__G3WIkXk4MjMLVyyUid6IEw_.base = (&NTI__NMMT5akQkfNlmjYrVF9a9bwA_);
NTI__G3WIkXk4MjMLVyyUid6IEw_.marker = Marker_tyRef__G3WIkXk4MjMLVyyUid6IEw;
NTI__MoyhMJWEHe6l39ajVP2YSWA_.size = sizeof(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA);
NTI__MoyhMJWEHe6l39ajVP2YSWA_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA);
NTI__MoyhMJWEHe6l39ajVP2YSWA_.kind = 17;
NTI__MoyhMJWEHe6l39ajVP2YSWA_.base = (&NTI__NMMT5akQkfNlmjYrVF9a9bwA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].offset = offsetof(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA, value);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].name = "value";
NTI__MoyhMJWEHe6l39ajVP2YSWA_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[13];
NTI__WTGU9aH9aqemaOVZXD0yOniQ_.size = sizeof(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA*);
NTI__WTGU9aH9aqemaOVZXD0yOniQ_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___MoyhMJWEHe6l39ajVP2YSWA*);
NTI__WTGU9aH9aqemaOVZXD0yOniQ_.kind = 22;
NTI__WTGU9aH9aqemaOVZXD0yOniQ_.base = (&NTI__MoyhMJWEHe6l39ajVP2YSWA_);
NTI__WTGU9aH9aqemaOVZXD0yOniQ_.marker = Marker_tyRef__WTGU9aH9aqemaOVZXD0yOniQ;
NTI__RDCVAUcZinb9aLgfyV8niJg_.size = sizeof(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg);
NTI__RDCVAUcZinb9aLgfyV8niJg_.align = NIM_ALIGNOF(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg);
NTI__RDCVAUcZinb9aLgfyV8niJg_.kind = 17;
NTI__RDCVAUcZinb9aLgfyV8niJg_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_11_3[0] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[15];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[15].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[15].offset = offsetof(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg, colonstate_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[15].typ = (&NTI__xHTZrq9aYs6boc9bCba0JbpQ_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[15].name = ":state";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_11_3[1] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[16];
NTI__yO64b9bIq9a3QrGi0ZNirrVg_.size = sizeof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTI__yO64b9bIq9a3QrGi0ZNirrVg_.align = NIM_ALIGNOF(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTI__yO64b9bIq9a3QrGi0ZNirrVg_.kind = 18;
NTI__yO64b9bIq9a3QrGi0ZNirrVg_.base = 0;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_12_2[0] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[18];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[18].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[18].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field0);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[18].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[18].name = "Field0";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_12_2[1] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[19];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field1);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].typ = (&NTI__HsJiUUcO9cHBdUCi0HwkSTA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].name = "Field1";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[17].len = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[17].kind = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[17].sons = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_12_2[0];
NTI__yO64b9bIq9a3QrGi0ZNirrVg_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[17];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].offset = offsetof(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg, cb1);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].typ = (&NTI__yO64b9bIq9a3QrGi0ZNirrVg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].name = "cb1";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_11_3[2] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[20];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].offset = offsetof(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg, future2);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].typ = (&NTI__TjokxNjmnZmr9bygVDVC9bvg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].name = "future2";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[14].len = 3; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[14].kind = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[14].sons = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_11_3[0];
NTI__RDCVAUcZinb9aLgfyV8niJg_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[14];
NTI__JBzpn7BwubwoL9chYMetyPQ_.size = sizeof(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg*);
NTI__JBzpn7BwubwoL9chYMetyPQ_.align = NIM_ALIGNOF(tyObject_Env_asyncfuturesdotnim_callbackeq___RDCVAUcZinb9aLgfyV8niJg*);
NTI__JBzpn7BwubwoL9chYMetyPQ_.kind = 22;
NTI__JBzpn7BwubwoL9chYMetyPQ_.base = (&NTI__RDCVAUcZinb9aLgfyV8niJg_);
NTI__JBzpn7BwubwoL9chYMetyPQ_.marker = Marker_tyRef__JBzpn7BwubwoL9chYMetyPQ;
NTI__DytvWkqCHojL9aGfYktbFPw_.size = sizeof(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw);
NTI__DytvWkqCHojL9aGfYktbFPw_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw);
NTI__DytvWkqCHojL9aGfYktbFPw_.kind = 17;
NTI__DytvWkqCHojL9aGfYktbFPw_.base = (&NTI__NMMT5akQkfNlmjYrVF9a9bwA_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[21].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[21].offset = offsetof(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw, value);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[21].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[21].name = "value";
NTI__DytvWkqCHojL9aGfYktbFPw_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[21];
NTI__PGriAzqlEWabm3KuP9cPwnw_.size = sizeof(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*);
NTI__PGriAzqlEWabm3KuP9cPwnw_.align = NIM_ALIGNOF(tyObject_FuturecolonObjectType___DytvWkqCHojL9aGfYktbFPw*);
NTI__PGriAzqlEWabm3KuP9cPwnw_.kind = 22;
NTI__PGriAzqlEWabm3KuP9cPwnw_.base = (&NTI__DytvWkqCHojL9aGfYktbFPw_);
NTI__PGriAzqlEWabm3KuP9cPwnw_.marker = Marker_tyRef__PGriAzqlEWabm3KuP9cPwnw;
NTI__SOfwXWONSsDuJaBnMvgifA_.size = sizeof(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA);
NTI__SOfwXWONSsDuJaBnMvgifA_.align = NIM_ALIGNOF(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA);
NTI__SOfwXWONSsDuJaBnMvgifA_.kind = 17;
NTI__SOfwXWONSsDuJaBnMvgifA_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_14_3[0] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[23];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].offset = offsetof(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA, colonstate_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].typ = (&NTI__xHTZrq9aYs6boc9bCba0JbpQ_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].name = ":state";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_14_3[1] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[24];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].offset = offsetof(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA, cb1);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].typ = (&NTI__yO64b9bIq9a3QrGi0ZNirrVg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].name = "cb1";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_14_3[2] = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[25];
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[25].kind = 1;
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[25].offset = offsetof(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA, future2);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[25].typ = (&NTI__TjokxNjmnZmr9bygVDVC9bvg_);
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[25].name = "future2";
TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[22].len = 3; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[22].kind = 2; TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[22].sons = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_14_3[0];
NTI__SOfwXWONSsDuJaBnMvgifA_.node = &TM__vnqLhdH9cCREQ2r9aXVOqbvQ_0[22];
NTI__dIasvr4vOc9aM8N0sR9bpVng_.size = sizeof(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA*);
NTI__dIasvr4vOc9aM8N0sR9bpVng_.align = NIM_ALIGNOF(tyObject_Env_asyncfuturesdotnim_addCallback___SOfwXWONSsDuJaBnMvgifA*);
NTI__dIasvr4vOc9aM8N0sR9bpVng_.kind = 22;
NTI__dIasvr4vOc9aM8N0sR9bpVng_.base = (&NTI__SOfwXWONSsDuJaBnMvgifA_);
NTI__dIasvr4vOc9aM8N0sR9bpVng_.marker = Marker_tyRef__dIasvr4vOc9aM8N0sR9bpVng;
}

