/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <windows.h>
#include <intrin.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw;
typedef struct tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw;
typedef struct tyObject_Thread__aCkJjuuA9audHPimgL5uPkg tyObject_Thread__aCkJjuuA9audHPimgL5uPkg;
typedef struct tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw;
typedef struct tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA;
typedef struct tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct Barrier Barrier;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tySequence__aNpJjaoUowCQc7fBn3wtDQ tySequence__aNpJjaoUowCQc7fBn3wtDQ;
typedef struct GcFrameHeader GcFrameHeader;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg;
typedef struct tySequence__ZE4llUwluRK7Sqp4MtXogQ tySequence__ZE4llUwluRK7Sqp4MtXogQ;
typedef struct tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ;

/* section: NIM_merge_TYPES */
struct tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw {
NI c;
CRITICAL_SECTION L;
NI counter;
};
typedef N_STDCALL_PTR(NI, tyProc__KeCiSdV9aG0JRdXpLIxCQ9cQ) (void* lpEventAttributes, NI32 bManualReset, NI32 bInitialState, NCSTRING lpName);
typedef N_NIMCALL_PTR(void, tyProc__nSqh6BBL9cSEu9bcR48Z72QA) (tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* m);
struct tyObject_Thread__aCkJjuuA9audHPimgL5uPkg {
tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg* core;
NI sys;
tyProc__nSqh6BBL9cSEu9bcR48Z72QA dataFn;
tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* data;
};
typedef tyObject_Thread__aCkJjuuA9audHPimgL5uPkg tyArray__VzdKMWiVX55GSra4f1dzcQ[256];
typedef N_NIMCALL_PTR(void, tyProc__fhqfcnDhIcLpBpSTVsWEZg) (void* thread, void* args);
typedef void* tyArray__2PWyF6nokyTyhzmcY3ON3w[128];
struct tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw {
NI len;
CRITICAL_SECTION lock;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw empty;
tyArray__2PWyF6nokyTyhzmcY3ON3w data;
};
struct tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw {
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw taskArrived;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw taskStarted;
tyProc__fhqfcnDhIcLpBpSTVsWEZg f;
void* data;
NIM_BOOL ready;
NIM_BOOL initialized;
NIM_BOOL shutdown;
tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw q;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw readyForTask;
};
typedef tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw tyArray__5sGw9aMSI320X9cbYIDJFEOQ[256];
typedef tyObject_Thread__aCkJjuuA9audHPimgL5uPkg tyArray__0x6EwkmjS0RXNUNMOfdG9cg[32];
typedef tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw tyArray__W9bX58rb2TvIPS9bAprPBVQg[32];
struct tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw {
NI32 dwLowDateTime;
NI32 dwHighDateTime;
};
struct tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA {
tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw prevSysKernel;
tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw prevSysUser;
tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw prevProcKernel;
tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw prevProcUser;
NI calls;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NF tyArray__iV2wVpdhi9coq9cstlcqapXg[2001];
struct tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg {
tyArray__iV2wVpdhi9coq9cstlcqapXg tls;
};
typedef N_STDCALL_PTR(void, tyProc__ofoySXaAAlxxs9bQS9a1etlg) (NI hEvent);
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
typedef NU8 tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig;
typedef NU8 tyArray__izDbpwaA8Rxj9b5mE6pSF7Q[24];
struct Barrier {
NI entered;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw cv;
NI left;
tyArray__izDbpwaA8Rxj9b5mE6pSF7Q cacheAlign2;
NIM_BOOL interest;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
CRITICAL_SECTION lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyProc__HzVCwACFYM9cx9aV62PdjtuA cbproc, void* ClE_0);
void* ClE_0;
} tyProc__VHS3NdmbwcdcZKmKV1JWhw;
typedef NU8 tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg;

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence__aNpJjaoUowCQc7fBn3wtDQ {
  TGenericSeq Sup;
  tyProc__HzVCwACFYM9cx9aV62PdjtuA data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__ZE4llUwluRK7Sqp4MtXogQ {
  TGenericSeq Sup;
  tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* data[SEQ_DECL_SIZE];
};
typedef struct {tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg;
tySequence__aNpJjaoUowCQc7fBn3wtDQ* threadDestructionHandlers__8OmU3x0fNdA0DLtOmU3kWw;
NI threadId__wzrdPYhtL9czkCWS4o9an9cRw;
TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
GcFrameHeader* gcFramePtr__ot48iojqko9aFxGhyjjjVaA;
tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* utcInstance__oeKVHn4dFpBJO35HhEkelw;
tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* localInstance__cLtN9cK9bCe6IPhJ3UFNLNKA;
NIM_BOOL envComputed__LLyFo9bsdu1ZXMDvAe8DhrQ;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* environment__mlhK49b6YMgc9cgrcYkKq9a3g;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* ownArgv__WVJ54JSHy7VxacV39bwBPFA;
NIM_BOOL ownParsedArgv__9btHydaUC5pNXxitEZsyzIg;
tyProc__VHS3NdmbwcdcZKmKV1JWhw callSoonProc__9b9b4iUSd60RO2UqC52ifJ6A;
tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg* gDisp__yIbBArLUsg2pBJkilx4yvg;
tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level__hzbRBHMSEnpbC61ptpdKmA;
tySequence__ZE4llUwluRK7Sqp4MtXogQ* handlers__OpA9asfHAsjfRTcLDwhkNfA;
NIM_BOOL pyThreadFrameInited__0LBR4zzVR5uWvgtv8SrMjg;
NIM_BOOL gcInited__uuy3PWTwb5gov9ao9bXJYBPg;
NIM_BOOL isSlave__t9a8wsVVRYqGEKhg1vb49b3g;
NIM_BOOL loggingEnabled__yLPNLBe6VZ6N8qtL17YAKw;
} NimThreadVars;

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, initLock__fSZuw88O4GKTNx4Mza9bPbglocks)(CRITICAL_SECTION* lock);
N_LIB_PRIVATE N_NIMCALL(void, initSemaphore__Bcnye583wFsPyzfpEXQ9cCg)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, initCond__YBNKcMrfPF8txECvgyCYrAlocks)(NI* cond);
static N_INLINE(void, initSysCond__YBNKcMrfPF8txECvgyCYrA_2locks)(NI* cond);
N_LIB_PRIVATE N_NIMCALL(void, setup__WTnSSeVs19cfp5pRs6KBLXQ)(void);
N_LIB_PRIVATE N_NIMCALL(NI, ncpicountProcessors)(void);
N_LIB_PRIVATE N_NOINLINE(void, activateWorkerThread__oNQ43gcq37w6ZH7r69b8oag)(NI i);
N_LIB_PRIVATE N_NIMCALL(void, createThread__ZlRlGL9cCaGDCyoP82KIjPQ)(tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* t, tyProc__nSqh6BBL9cSEu9bcR48Z72QA tp, tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* param);
N_LIB_PRIVATE N_NIMCALL(void, slave__1yqYR9cLeffanOjn0piJ2VQ)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w);
static N_INLINE(void*, GetThreadLocalVars)(void);
N_LIB_PRIVATE N_NIMCALL(void*, threadVarGetValue__O8VJSmwa3WY6y9bP6Ht9b7hw)(NI32 dwTlsIndex);
static N_INLINE(NI, atomicDec__v6qORsZ9azlHHhOL1JYACRA_2system)(NI* memLoc, NI x);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs);
N_LIB_PRIVATE N_NIMCALL(void, signal__Bcnye583wFsPyzfpEXQ9cCg_2)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
N_LIB_PRIVATE N_NIMCALL(void, acquire__2gdcVC9bfoOlGMK1NSM2nLQ)(CRITICAL_SECTION* lock);
N_LIB_PRIVATE N_NIMCALL(void, release__2gdcVC9bfoOlGMK1NSM2nLQ_2)(CRITICAL_SECTION* lock);
static N_INLINE(void, signal__YBNKcMrfPF8txECvgyCYrA_3locks)(NI* cond);
N_LIB_PRIVATE N_NIMCALL(void, blockUntil__Bcnye583wFsPyzfpEXQ9cCg_3)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, wait__pa3B9b9ctFL22wM1ypA8MNtwlocks)(NI* cond, CRITICAL_SECTION* lock);
N_LIB_PRIVATE N_NIMCALL(void, waitSysCond__yt0qxCLgFmSktbZNtXIybQ)(NI* cond, CRITICAL_SECTION* lock);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimLeaveFinally)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, cleanFlowVars__1yqYR9cLeffanOjn0piJ2VQ_2)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w);
N_LIB_PRIVATE N_NIMCALL(void, nimGCunref)(void* p);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, selectWorker__TNxpaz54u9aohJtw68jPm4g)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc__fhqfcnDhIcLpBpSTVsWEZg fn, void* data);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, cas__JJYX9aDJanv6Du380geRC5w)(NIM_BOOL* p, NIM_BOOL oldValue, NIM_BOOL newValue);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tryAcquire__WC5DSRWH9bwv9asm9bZP5EWIw)(CRITICAL_SECTION* lock);
static N_INLINE(NI, atomicInc__v6qORsZ9azlHHhOL1JYACRAsystem)(NI* memLoc, NI x);
N_LIB_PRIVATE N_NIMCALL(tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig, advice__C0O6faaUOyXrzDKc9bL5ErA)(tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA* s);
static N_INLINE(void, destroySemaphore__NTILssLLscGtKB8oC9bOaQwthreadpool)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, deinitCond__YBNKcMrfPF8txECvgyCYrA_4locks)(NI* cond);
static N_INLINE(void, deinitSysCond__YBNKcMrfPF8txECvgyCYrA_5locks)(NI* cond);
static N_INLINE(void, deinitLock__fSZuw88O4GKTNx4Mza9bPbg_2locks)(CRITICAL_SECTION* lock);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE TNimType NTI__AqHEWWcw2VBFjoa2Hp8Akw_;
N_LIB_PRIVATE TNimType NTI__sx9abLHOwgGDBH9bpoqw2ezw_;
extern TNimType NTI__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI__lsB6JckQ3csMuiRW476VWg_;
N_LIB_PRIVATE TNimType NTI__fhqfcnDhIcLpBpSTVsWEZg_;
extern TNimType NTI__vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI__VaVACK0bpYmqIQ0mKcHfQQ_;
N_LIB_PRIVATE TNimType NTI__5COJP8EWIaAuXvZlDbQZmw_;
N_LIB_PRIVATE TNimType NTI__2PWyF6nokyTyhzmcY3ON3w_;
N_LIB_PRIVATE TNimType NTI__CyNApV6Mfiphj5eUnH5G1A_;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NI currentPoolSize__ErccdOg9batM6rAb3hYbfxA;
N_LIB_PRIVATE NI maxPoolSize__I5gWiq7COu2xfOvex9aGTWw = ((NI) 256);
N_LIB_PRIVATE NI minPoolSize__L9a7W9byTjVXeXKRg5OtqNTg = ((NI) 4);
N_LIB_PRIVATE tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw gSomeReady__RyUdpNfPQUpKmQaHtWHYoA;
N_LIB_PRIVATE tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* readyWorker__BT69aUhVoxO4qq9b8EinSVNA;
N_LIB_PRIVATE CRITICAL_SECTION numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA;
N_LIB_PRIVATE NI numSlavesRunning__ptIe6dS9bOnWPjIrLSfTasw;
N_LIB_PRIVATE NI numSlavesWaiting__fTOoJ83E0W3d2BkhxhQFwg;
extern tyProc__KeCiSdV9aG0JRdXpLIxCQ9cQ Dl_3100026_;
N_LIB_PRIVATE tyArray__VzdKMWiVX55GSra4f1dzcQ workers__bezHuru9a1bEti2XBmfodvA;
N_LIB_PRIVATE tyArray__5sGw9aMSI320X9cbYIDJFEOQ workersData__R5YxoJYCt3PvKeJGhluUDQ;
N_LIB_PRIVATE tyArray__0x6EwkmjS0RXNUNMOfdG9cg distinguished__PEEgL9bODGVNNubj61abNQA;
N_LIB_PRIVATE tyArray__W9bX58rb2TvIPS9bAprPBVQg distinguishedData__Lqsi7ieuVktaO9acMSZyorQ;
N_LIB_PRIVATE tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA state__7PVqgO4qfT36l9bZ9a9cqhD9bA;
N_LIB_PRIVATE CRITICAL_SECTION stateLock__Of3qxka1C2uLE9anKCj52kA;
N_LIB_PRIVATE CRITICAL_SECTION distinguishedLock__lPmqsqhMalxIWA0zwhlpFg;
extern NI32 globalsSlot__ciXDZu9c27pHpCRMoz4RIgw;
extern tyProc__ofoySXaAAlxxs9bQS9a1etlg Dl_3100039_;
extern tyProc__ofoySXaAAlxxs9bQS9a1etlg Dl_3100032_;

/* section: NIM_merge_PROCS */
static N_INLINE(void, initLock__fSZuw88O4GKTNx4Mza9bPbglocks)(CRITICAL_SECTION* lock) {
	InitializeCriticalSection(lock);
}
static N_INLINE(void, initSysCond__YBNKcMrfPF8txECvgyCYrA_2locks)(NI* cond) {
	(*cond) = Dl_3100026_(NIM_NIL, ((NI32) 0), ((NI32) 0), ((NCSTRING) NIM_NIL));
}
static N_INLINE(void, initCond__YBNKcMrfPF8txECvgyCYrAlocks)(NI* cond) {
	initSysCond__YBNKcMrfPF8txECvgyCYrA_2locks(cond);
}
N_LIB_PRIVATE N_NIMCALL(void, initSemaphore__Bcnye583wFsPyzfpEXQ9cCg)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	initCond__YBNKcMrfPF8txECvgyCYrAlocks((&(*cv).c));
	initLock__fSZuw88O4GKTNx4Mza9bPbglocks((&(*cv).L));
}
static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue__O8VJSmwa3WY6y9bP6Ht9b7hw(globalsSlot__ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}
static N_INLINE(NI, atomicDec__v6qORsZ9azlHHhOL1JYACRA_2system)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = _InterlockedExchangeAdd64(memLoc, ((NI64)-(x)));
	result -= x;
	return result;
}
static N_INLINE(void, signal__YBNKcMrfPF8txECvgyCYrA_3locks)(NI* cond) {
	Dl_3100039_((*cond));
}
N_LIB_PRIVATE N_NIMCALL(void, signal__Bcnye583wFsPyzfpEXQ9cCg_2)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	acquire__2gdcVC9bfoOlGMK1NSM2nLQ((&(*cv).L));
	(*cv).counter += ((NI) 1);
	release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&(*cv).L));
	signal__YBNKcMrfPF8txECvgyCYrA_3locks((&(*cv).c));
}
static N_INLINE(void, wait__pa3B9b9ctFL22wM1ypA8MNtwlocks)(NI* cond, CRITICAL_SECTION* lock) {
	waitSysCond__yt0qxCLgFmSktbZNtXIybQ(cond, lock);
}
N_LIB_PRIVATE N_NIMCALL(void, blockUntil__Bcnye583wFsPyzfpEXQ9cCg_3)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	acquire__2gdcVC9bfoOlGMK1NSM2nLQ((&(*cv).L));
	{
		while (1) {
			if (!((*cv).counter <= ((NI) 0))) goto LA2;
			wait__pa3B9b9ctFL22wM1ypA8MNtwlocks((&(*cv).c), (&(*cv).L));
		} LA2: ;
	}
	(*cv).counter -= ((NI) 1);
	release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&(*cv).L));
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	(*s).prev = NimTV_->excHandler__rqLlY5bs9atDw2OXYqJEn5g;
	NimTV_->excHandler__rqLlY5bs9atDw2OXYqJEn5g = s;
}
static N_INLINE(void, popSafePoint)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->excHandler__rqLlY5bs9atDw2OXYqJEn5g = (*NimTV_->excHandler__rqLlY5bs9atDw2OXYqJEn5g).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, cleanFlowVars__1yqYR9cLeffanOjn0piJ2VQ_2)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w) {
	tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw* q;
	q = (&(*w).q);
	acquire__2gdcVC9bfoOlGMK1NSM2nLQ((&(*q).lock));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < (*q).len)) goto LA3;
				i = i_2;
				if (((RootObj*) ((*q).data[(i)- 0]))) { nimGCunref(((RootObj*) ((*q).data[(i)- 0]))); }
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	(*q).len = ((NI) 0);
	release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&(*q).lock));
}
N_LIB_PRIVATE N_NIMCALL(void, slave__1yqYR9cLeffanOjn0piJ2VQ)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->isSlave__t9a8wsVVRYqGEKhg1vb49b3g = NIM_TRUE;
	{
		while (1) {
			TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_5;
			TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_6;
			{
				NI T7_;
				if (!(*w).shutdown) goto LA5_;
				(*w).shutdown = NIM_FALSE;
				T7_ = (NI)0;
				T7_ = atomicDec__v6qORsZ9azlHHhOL1JYACRA_2system((&currentPoolSize__ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
				{
					while (1) {
						{
							if (!!(((*w).data == NIM_NIL))) goto LA12_;
							nossleep(((NI) 100));
						}
						goto LA10_;
						LA12_: ;
						{
							goto LA8;
						}
						LA10_: ;
					}
				} LA8: ;
				goto LA1;
			}
			LA5_: ;
			(*w).ready = NIM_TRUE;
			readyWorker__BT69aUhVoxO4qq9b8EinSVNA = w;
			signal__Bcnye583wFsPyzfpEXQ9cCg_2((&gSomeReady__RyUdpNfPQUpKmQaHtWHYoA));
			blockUntil__Bcnye583wFsPyzfpEXQ9cCg_3((&(*w).taskArrived));
			acquire__2gdcVC9bfoOlGMK1NSM2nLQ((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
			pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_5);
			TM__Qzgg5NBLvccay07XFph3Rw_5.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_5.context);
			if (TM__Qzgg5NBLvccay07XFph3Rw_5.status == 0) {
			numSlavesRunning__ptIe6dS9bOnWPjIrLSfTasw += ((NI) 1);
			popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
				if (TM__Qzgg5NBLvccay07XFph3Rw_5.status != 0) nimLeaveFinally();
			}
			if (TM__Qzgg5NBLvccay07XFph3Rw_5.status != 0) reraiseException();
			(*w).f(((void*) (w)), (*w).data);
			acquire__2gdcVC9bfoOlGMK1NSM2nLQ((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
			pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_6);
			TM__Qzgg5NBLvccay07XFph3Rw_6.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_6.context);
			if (TM__Qzgg5NBLvccay07XFph3Rw_6.status == 0) {
			numSlavesRunning__ptIe6dS9bOnWPjIrLSfTasw -= ((NI) 1);
			popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
				if (TM__Qzgg5NBLvccay07XFph3Rw_6.status != 0) nimLeaveFinally();
			}
			if (TM__Qzgg5NBLvccay07XFph3Rw_6.status != 0) reraiseException();
			{
				if (!!(((*w).q.len == ((NI) 0)))) goto LA21_;
				cleanFlowVars__1yqYR9cLeffanOjn0piJ2VQ_2(w);
			}
			LA21_: ;
		}
	} LA1: ;
}
N_LIB_PRIVATE N_NOINLINE(void, activateWorkerThread__oNQ43gcq37w6ZH7r69b8oag)(NI i) {
	initSemaphore__Bcnye583wFsPyzfpEXQ9cCg((&workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].taskArrived));
	initSemaphore__Bcnye583wFsPyzfpEXQ9cCg((&workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].taskStarted));
	workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].initialized = NIM_TRUE;
	initSemaphore__Bcnye583wFsPyzfpEXQ9cCg((&workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].q.empty));
	initLock__fSZuw88O4GKTNx4Mza9bPbglocks((&workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].q.lock));
	createThread__ZlRlGL9cCaGDCyoP82KIjPQ((&workers__bezHuru9a1bEti2XBmfodvA[(i)- 0]), slave__1yqYR9cLeffanOjn0piJ2VQ, (&workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0]));
}
N_LIB_PRIVATE N_NIMCALL(void, setup__WTnSSeVs19cfp5pRs6KBLXQ)(void) {
	NI p;
	p = ncpicountProcessors();
	currentPoolSize__ErccdOg9batM6rAb3hYbfxA = ((p <= ((NI) 256)) ? p : ((NI) 256));
	readyWorker__BT69aUhVoxO4qq9b8EinSVNA = (&workersData__R5YxoJYCt3PvKeJGhluUDQ[(((NI) 0))- 0]);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < currentPoolSize__ErccdOg9batM6rAb3hYbfxA)) goto LA3;
				i = i_2;
				activateWorkerThread__oNQ43gcq37w6ZH7r69b8oag(i);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, selectWorker__TNxpaz54u9aohJtw68jPm4g)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc__fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = cas__JJYX9aDJanv6Du380geRC5w((&(*w).ready), NIM_TRUE, NIM_FALSE);
		if (!T3_) goto LA4_;
		(*w).data = data;
		(*w).f = fn;
		signal__Bcnye583wFsPyzfpEXQ9cCg_2((&(*w).taskArrived));
		blockUntil__Bcnye583wFsPyzfpEXQ9cCg_3((&(*w).taskStarted));
		result = NIM_TRUE;
	}
	LA4_: ;
	return result;
}
static N_INLINE(NI, atomicInc__v6qORsZ9azlHHhOL1JYACRAsystem)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = _InterlockedExchangeAdd64(memLoc, x);
	result += x;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimSpawn3)(tyProc__fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
	NimThreadVars* NimTV_;
{	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	{
		while (1) {
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = selectWorker__TNxpaz54u9aohJtw68jPm4g(readyWorker__BT69aUhVoxO4qq9b8EinSVNA, fn, data);
				if (!T5_) goto LA6_;
				goto BeforeRet_;
			}
			LA6_: ;
			{
				NI i;
				NI i_2;
				i = (NI)0;
				i_2 = ((NI) 0);
				{
					while (1) {
						if (!(i_2 < currentPoolSize__ErccdOg9batM6rAb3hYbfxA)) goto LA10;
						i = i_2;
						{
							NIM_BOOL T13_;
							T13_ = (NIM_BOOL)0;
							T13_ = selectWorker__TNxpaz54u9aohJtw68jPm4g((&workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0]), fn, data);
							if (!T13_) goto LA14_;
							goto BeforeRet_;
						}
						LA14_: ;
						i_2 += ((NI) 1);
					} LA10: ;
				}
			}
			{
				NIM_BOOL T18_;
				T18_ = (NIM_BOOL)0;
				T18_ = (state__7PVqgO4qfT36l9bZ9a9cqhD9bA.calls < maxPoolSize__I5gWiq7COu2xfOvex9aGTWw);
				if (T18_) goto LA19_;
				T18_ = ((NI)(state__7PVqgO4qfT36l9bZ9a9cqhD9bA.calls & ((NI) 127)) == ((NI) 0));
				LA19_: ;
				if (!T18_) goto LA20_;
				{
					NIM_BOOL T24_;
					tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig T41_;
					T24_ = (NIM_BOOL)0;
					T24_ = tryAcquire__WC5DSRWH9bwv9asm9bZP5EWIw((&stateLock__Of3qxka1C2uLE9anKCj52kA));
					if (!T24_) goto LA25_;
					{
						tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w;
						NI T35_;
						if (!(currentPoolSize__ErccdOg9batM6rAb3hYbfxA < minPoolSize__L9a7W9byTjVXeXKRg5OtqNTg)) goto LA29_;
						{
							if (!!(workersData__R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize__ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA33_;
							activateWorkerThread__oNQ43gcq37w6ZH7r69b8oag(currentPoolSize__ErccdOg9batM6rAb3hYbfxA);
						}
						LA33_: ;
						w = (&workersData__R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize__ErccdOg9batM6rAb3hYbfxA)- 0]);
						T35_ = (NI)0;
						T35_ = atomicInc__v6qORsZ9azlHHhOL1JYACRAsystem((&currentPoolSize__ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
						{
							NIM_BOOL T38_;
							T38_ = (NIM_BOOL)0;
							T38_ = selectWorker__TNxpaz54u9aohJtw68jPm4g(w, fn, data);
							if (!T38_) goto LA39_;
							release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&stateLock__Of3qxka1C2uLE9anKCj52kA));
							goto BeforeRet_;
						}
						LA39_: ;
					}
					LA29_: ;
					T41_ = (tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig)0;
					T41_ = advice__C0O6faaUOyXrzDKc9bL5ErA((&state__7PVqgO4qfT36l9bZ9a9cqhD9bA));
					switch (T41_) {
					case ((tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig) 0):
					{
					}
					break;
					case ((tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig) 1):
					{
						{
							tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w_2;
							NI T52_;
							if (!(currentPoolSize__ErccdOg9batM6rAb3hYbfxA < maxPoolSize__I5gWiq7COu2xfOvex9aGTWw)) goto LA46_;
							{
								if (!!(workersData__R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize__ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA50_;
								activateWorkerThread__oNQ43gcq37w6ZH7r69b8oag(currentPoolSize__ErccdOg9batM6rAb3hYbfxA);
							}
							LA50_: ;
							w_2 = (&workersData__R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize__ErccdOg9batM6rAb3hYbfxA)- 0]);
							T52_ = (NI)0;
							T52_ = atomicInc__v6qORsZ9azlHHhOL1JYACRAsystem((&currentPoolSize__ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
							{
								NIM_BOOL T55_;
								T55_ = (NIM_BOOL)0;
								T55_ = selectWorker__TNxpaz54u9aohJtw68jPm4g(w_2, fn, data);
								if (!T55_) goto LA56_;
								release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&stateLock__Of3qxka1C2uLE9anKCj52kA));
								goto BeforeRet_;
							}
							LA56_: ;
						}
						LA46_: ;
					}
					break;
					case ((tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig) 2):
					{
						{
							tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w_3;
							if (!(minPoolSize__L9a7W9byTjVXeXKRg5OtqNTg < currentPoolSize__ErccdOg9batM6rAb3hYbfxA)) goto LA61_;
							w_3 = (&workersData__R5YxoJYCt3PvKeJGhluUDQ[((NI)(currentPoolSize__ErccdOg9batM6rAb3hYbfxA - ((NI) 1)))- 0]);
							(*w_3).shutdown = NIM_TRUE;
						}
						LA61_: ;
					}
					break;
					default: __assume(0);
					}
					release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&stateLock__Of3qxka1C2uLE9anKCj52kA));
				}
				LA25_: ;
			}
			LA20_: ;
			{
				TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_7;
				if (!NimTV_->isSlave__t9a8wsVVRYqGEKhg1vb49b3g) goto LA65_;
				acquire__2gdcVC9bfoOlGMK1NSM2nLQ((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
				pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_7);
				TM__Qzgg5NBLvccay07XFph3Rw_7.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_7.context);
				if (TM__Qzgg5NBLvccay07XFph3Rw_7.status == 0) {
				{
					if (!(numSlavesRunning__ptIe6dS9bOnWPjIrLSfTasw <= (NI)(numSlavesWaiting__fTOoJ83E0W3d2BkhxhQFwg + ((NI) 1)))) goto LA69_;
					{
						tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w_4;
						NI T79_;
						if (!(currentPoolSize__ErccdOg9batM6rAb3hYbfxA < maxPoolSize__I5gWiq7COu2xfOvex9aGTWw)) goto LA73_;
						{
							if (!!(workersData__R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize__ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA77_;
							activateWorkerThread__oNQ43gcq37w6ZH7r69b8oag(currentPoolSize__ErccdOg9batM6rAb3hYbfxA);
						}
						LA77_: ;
						w_4 = (&workersData__R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize__ErccdOg9batM6rAb3hYbfxA)- 0]);
						T79_ = (NI)0;
						T79_ = atomicInc__v6qORsZ9azlHHhOL1JYACRAsystem((&currentPoolSize__ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
						{
							NIM_BOOL T82_;
							T82_ = (NIM_BOOL)0;
							T82_ = selectWorker__TNxpaz54u9aohJtw68jPm4g(w_4, fn, data);
							if (!T82_) goto LA83_;
							popSafePoint();
							release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
							goto BeforeRet_;
						}
						LA83_: ;
					}
					goto LA71_;
					LA73_: ;
					{
					}
					LA71_: ;
				}
				LA69_: ;
				numSlavesWaiting__fTOoJ83E0W3d2BkhxhQFwg += ((NI) 1);
				popSafePoint();
				}
				else {
					popSafePoint();
				}
				{
					release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
					if (TM__Qzgg5NBLvccay07XFph3Rw_7.status != 0) nimLeaveFinally();
				}
				if (TM__Qzgg5NBLvccay07XFph3Rw_7.status != 0) reraiseException();
			}
			LA65_: ;
			blockUntil__Bcnye583wFsPyzfpEXQ9cCg_3((&gSomeReady__RyUdpNfPQUpKmQaHtWHYoA));
			{
				TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_8;
				if (!NimTV_->isSlave__t9a8wsVVRYqGEKhg1vb49b3g) goto LA90_;
				acquire__2gdcVC9bfoOlGMK1NSM2nLQ((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
				pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_8);
				TM__Qzgg5NBLvccay07XFph3Rw_8.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_8.context);
				if (TM__Qzgg5NBLvccay07XFph3Rw_8.status == 0) {
				numSlavesWaiting__fTOoJ83E0W3d2BkhxhQFwg -= ((NI) 1);
				popSafePoint();
				}
				else {
					popSafePoint();
				}
				{
					release__2gdcVC9bfoOlGMK1NSM2nLQ_2((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
					if (TM__Qzgg5NBLvccay07XFph3Rw_8.status != 0) nimLeaveFinally();
				}
				if (TM__Qzgg5NBLvccay07XFph3Rw_8.status != 0) reraiseException();
			}
			LA90_: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimArgsPassingDone)(void* p) {
	tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w;
	w = ((tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*) (p));
	signal__Bcnye583wFsPyzfpEXQ9cCg_2((&(*w).taskStarted));
}
static N_INLINE(void, deinitSysCond__YBNKcMrfPF8txECvgyCYrA_5locks)(NI* cond) {
	Dl_3100032_((*cond));
}
static N_INLINE(void, deinitCond__YBNKcMrfPF8txECvgyCYrA_4locks)(NI* cond) {
	deinitSysCond__YBNKcMrfPF8txECvgyCYrA_5locks(cond);
}
static N_INLINE(void, deinitLock__fSZuw88O4GKTNx4Mza9bPbg_2locks)(CRITICAL_SECTION* lock) {
	DeleteCriticalSection(lock);
}
static N_INLINE(void, destroySemaphore__NTILssLLscGtKB8oC9bOaQwthreadpool)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	deinitCond__YBNKcMrfPF8txECvgyCYrA_4locks((&(*cv).c));
	deinitLock__fSZuw88O4GKTNx4Mza9bPbg_2locks((&(*cv).L));
}
N_LIB_PRIVATE N_NIMCALL(void, closeBarrier)(Barrier* b) {
	_ReadWriteBarrier();
	{
		if (!!(((*b).left == (*b).entered))) goto LA3_;
		initSemaphore__Bcnye583wFsPyzfpEXQ9cCg((&(*b).cv));
		_ReadWriteBarrier();
		(*b).interest = NIM_TRUE;
		_ReadWriteBarrier();
		{
			while (1) {
				if (!!(((*b).left == (*b).entered))) goto LA6;
				blockUntil__Bcnye583wFsPyzfpEXQ9cCg_3((&(*b).cv));
			} LA6: ;
		}
		destroySemaphore__NTILssLLscGtKB8oC9bOaQwthreadpool((&(*b).cv));
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, sync__WTnSSeVs19cfp5pRs6KBLXQ_2)(void) {
	{
		while (1) {
			NIM_BOOL allReady;
			allReady = NIM_TRUE;
			{
				NI i;
				NI i_2;
				i = (NI)0;
				i_2 = ((NI) 0);
				{
					while (1) {
						NIM_BOOL T10_;
						if (!(i_2 < currentPoolSize__ErccdOg9batM6rAb3hYbfxA)) goto LA5;
						i = i_2;
						{
							if (!!(allReady)) goto LA8_;
							goto LA3;
						}
						LA8_: ;
						T10_ = (NIM_BOOL)0;
						T10_ = allReady;
						if (!(T10_)) goto LA11_;
						T10_ = workersData__R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].ready;
						LA11_: ;
						allReady = T10_;
						i_2 += ((NI) 1);
					} LA5: ;
				}
			} LA3: ;
			{
				if (!allReady) goto LA14_;
				goto LA1;
			}
			LA14_: ;
			nossleep(((NI) 100));
		}
	} LA1: ;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_threadpoolInit000)(void) {
{
	initLock__fSZuw88O4GKTNx4Mza9bPbglocks((&numSlavesLock__WtiE83BZa1NBG7G2g8ZnmA));
	initSemaphore__Bcnye583wFsPyzfpEXQ9cCg((&gSomeReady__RyUdpNfPQUpKmQaHtWHYoA));
	initLock__fSZuw88O4GKTNx4Mza9bPbglocks((&stateLock__Of3qxka1C2uLE9anKCj52kA));
	initLock__fSZuw88O4GKTNx4Mza9bPbglocks((&distinguishedLock__lPmqsqhMalxIWA0zwhlpFg));
	setup__WTnSSeVs19cfp5pRs6KBLXQ();
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_threadpoolDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__Qzgg5NBLvccay07XFph3Rw_2_9[9];
static TNimNode* TM__Qzgg5NBLvccay07XFph3Rw_3_3[3];
static TNimNode* TM__Qzgg5NBLvccay07XFph3Rw_4_4[4];
static TNimNode TM__Qzgg5NBLvccay07XFph3Rw_0[19];

/* section: NIM_merge_TYPE_INIT3 */
NTI__AqHEWWcw2VBFjoa2Hp8Akw_.size = sizeof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw);
NTI__AqHEWWcw2VBFjoa2Hp8Akw_.align = NIM_ALIGNOF(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw);
NTI__AqHEWWcw2VBFjoa2Hp8Akw_.kind = 18;
NTI__AqHEWWcw2VBFjoa2Hp8Akw_.base = 0;
NTI__AqHEWWcw2VBFjoa2Hp8Akw_.flags = 3;
TM__Qzgg5NBLvccay07XFph3Rw_2_9[0] = &TM__Qzgg5NBLvccay07XFph3Rw_0[1];
NTI__sx9abLHOwgGDBH9bpoqw2ezw_.size = sizeof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw);
NTI__sx9abLHOwgGDBH9bpoqw2ezw_.align = NIM_ALIGNOF(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw);
NTI__sx9abLHOwgGDBH9bpoqw2ezw_.kind = 18;
NTI__sx9abLHOwgGDBH9bpoqw2ezw_.base = 0;
NTI__sx9abLHOwgGDBH9bpoqw2ezw_.flags = 3;
TM__Qzgg5NBLvccay07XFph3Rw_3_3[0] = &TM__Qzgg5NBLvccay07XFph3Rw_0[3];
TM__Qzgg5NBLvccay07XFph3Rw_0[3].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[3].offset = offsetof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw, c);
TM__Qzgg5NBLvccay07XFph3Rw_0[3].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Qzgg5NBLvccay07XFph3Rw_0[3].name = "c";
TM__Qzgg5NBLvccay07XFph3Rw_3_3[1] = &TM__Qzgg5NBLvccay07XFph3Rw_0[4];
TM__Qzgg5NBLvccay07XFph3Rw_0[4].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[4].offset = offsetof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw, L);
TM__Qzgg5NBLvccay07XFph3Rw_0[4].typ = (&NTI__lsB6JckQ3csMuiRW476VWg_);
TM__Qzgg5NBLvccay07XFph3Rw_0[4].name = "L";
TM__Qzgg5NBLvccay07XFph3Rw_3_3[2] = &TM__Qzgg5NBLvccay07XFph3Rw_0[5];
TM__Qzgg5NBLvccay07XFph3Rw_0[5].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[5].offset = offsetof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw, counter);
TM__Qzgg5NBLvccay07XFph3Rw_0[5].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Qzgg5NBLvccay07XFph3Rw_0[5].name = "counter";
TM__Qzgg5NBLvccay07XFph3Rw_0[2].len = 3; TM__Qzgg5NBLvccay07XFph3Rw_0[2].kind = 2; TM__Qzgg5NBLvccay07XFph3Rw_0[2].sons = &TM__Qzgg5NBLvccay07XFph3Rw_3_3[0];
NTI__sx9abLHOwgGDBH9bpoqw2ezw_.node = &TM__Qzgg5NBLvccay07XFph3Rw_0[2];
TM__Qzgg5NBLvccay07XFph3Rw_0[1].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[1].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, taskArrived);
TM__Qzgg5NBLvccay07XFph3Rw_0[1].typ = (&NTI__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[1].name = "taskArrived";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[1] = &TM__Qzgg5NBLvccay07XFph3Rw_0[6];
TM__Qzgg5NBLvccay07XFph3Rw_0[6].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[6].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, taskStarted);
TM__Qzgg5NBLvccay07XFph3Rw_0[6].typ = (&NTI__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[6].name = "taskStarted";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[2] = &TM__Qzgg5NBLvccay07XFph3Rw_0[7];
NTI__fhqfcnDhIcLpBpSTVsWEZg_.size = sizeof(tyProc__fhqfcnDhIcLpBpSTVsWEZg);
NTI__fhqfcnDhIcLpBpSTVsWEZg_.align = NIM_ALIGNOF(tyProc__fhqfcnDhIcLpBpSTVsWEZg);
NTI__fhqfcnDhIcLpBpSTVsWEZg_.kind = 25;
NTI__fhqfcnDhIcLpBpSTVsWEZg_.base = 0;
NTI__fhqfcnDhIcLpBpSTVsWEZg_.flags = 3;
TM__Qzgg5NBLvccay07XFph3Rw_0[7].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[7].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, f);
TM__Qzgg5NBLvccay07XFph3Rw_0[7].typ = (&NTI__fhqfcnDhIcLpBpSTVsWEZg_);
TM__Qzgg5NBLvccay07XFph3Rw_0[7].name = "f";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[3] = &TM__Qzgg5NBLvccay07XFph3Rw_0[8];
TM__Qzgg5NBLvccay07XFph3Rw_0[8].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[8].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, data);
TM__Qzgg5NBLvccay07XFph3Rw_0[8].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[8].name = "data";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[4] = &TM__Qzgg5NBLvccay07XFph3Rw_0[9];
TM__Qzgg5NBLvccay07XFph3Rw_0[9].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[9].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, ready);
TM__Qzgg5NBLvccay07XFph3Rw_0[9].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Qzgg5NBLvccay07XFph3Rw_0[9].name = "ready";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[5] = &TM__Qzgg5NBLvccay07XFph3Rw_0[10];
TM__Qzgg5NBLvccay07XFph3Rw_0[10].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[10].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, initialized);
TM__Qzgg5NBLvccay07XFph3Rw_0[10].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Qzgg5NBLvccay07XFph3Rw_0[10].name = "initialized";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[6] = &TM__Qzgg5NBLvccay07XFph3Rw_0[11];
TM__Qzgg5NBLvccay07XFph3Rw_0[11].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[11].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, shutdown);
TM__Qzgg5NBLvccay07XFph3Rw_0[11].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Qzgg5NBLvccay07XFph3Rw_0[11].name = "shutdown";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[7] = &TM__Qzgg5NBLvccay07XFph3Rw_0[12];
NTI__5COJP8EWIaAuXvZlDbQZmw_.size = sizeof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw);
NTI__5COJP8EWIaAuXvZlDbQZmw_.align = NIM_ALIGNOF(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw);
NTI__5COJP8EWIaAuXvZlDbQZmw_.kind = 18;
NTI__5COJP8EWIaAuXvZlDbQZmw_.base = 0;
NTI__5COJP8EWIaAuXvZlDbQZmw_.flags = 3;
TM__Qzgg5NBLvccay07XFph3Rw_4_4[0] = &TM__Qzgg5NBLvccay07XFph3Rw_0[14];
TM__Qzgg5NBLvccay07XFph3Rw_0[14].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[14].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, len);
TM__Qzgg5NBLvccay07XFph3Rw_0[14].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Qzgg5NBLvccay07XFph3Rw_0[14].name = "len";
TM__Qzgg5NBLvccay07XFph3Rw_4_4[1] = &TM__Qzgg5NBLvccay07XFph3Rw_0[15];
TM__Qzgg5NBLvccay07XFph3Rw_0[15].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[15].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, lock);
TM__Qzgg5NBLvccay07XFph3Rw_0[15].typ = (&NTI__lsB6JckQ3csMuiRW476VWg_);
TM__Qzgg5NBLvccay07XFph3Rw_0[15].name = "lock";
TM__Qzgg5NBLvccay07XFph3Rw_4_4[2] = &TM__Qzgg5NBLvccay07XFph3Rw_0[16];
TM__Qzgg5NBLvccay07XFph3Rw_0[16].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[16].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, empty);
TM__Qzgg5NBLvccay07XFph3Rw_0[16].typ = (&NTI__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[16].name = "empty";
TM__Qzgg5NBLvccay07XFph3Rw_4_4[3] = &TM__Qzgg5NBLvccay07XFph3Rw_0[17];
NTI__2PWyF6nokyTyhzmcY3ON3w_.size = sizeof(tyArray__2PWyF6nokyTyhzmcY3ON3w);
NTI__2PWyF6nokyTyhzmcY3ON3w_.align = NIM_ALIGNOF(tyArray__2PWyF6nokyTyhzmcY3ON3w);
NTI__2PWyF6nokyTyhzmcY3ON3w_.kind = 16;
NTI__2PWyF6nokyTyhzmcY3ON3w_.base = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
NTI__2PWyF6nokyTyhzmcY3ON3w_.flags = 3;
TM__Qzgg5NBLvccay07XFph3Rw_0[17].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[17].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, data);
TM__Qzgg5NBLvccay07XFph3Rw_0[17].typ = (&NTI__2PWyF6nokyTyhzmcY3ON3w_);
TM__Qzgg5NBLvccay07XFph3Rw_0[17].name = "data";
TM__Qzgg5NBLvccay07XFph3Rw_0[13].len = 4; TM__Qzgg5NBLvccay07XFph3Rw_0[13].kind = 2; TM__Qzgg5NBLvccay07XFph3Rw_0[13].sons = &TM__Qzgg5NBLvccay07XFph3Rw_4_4[0];
NTI__5COJP8EWIaAuXvZlDbQZmw_.node = &TM__Qzgg5NBLvccay07XFph3Rw_0[13];
TM__Qzgg5NBLvccay07XFph3Rw_0[12].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[12].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, q);
TM__Qzgg5NBLvccay07XFph3Rw_0[12].typ = (&NTI__5COJP8EWIaAuXvZlDbQZmw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[12].name = "q";
TM__Qzgg5NBLvccay07XFph3Rw_2_9[8] = &TM__Qzgg5NBLvccay07XFph3Rw_0[18];
TM__Qzgg5NBLvccay07XFph3Rw_0[18].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[18].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, readyForTask);
TM__Qzgg5NBLvccay07XFph3Rw_0[18].typ = (&NTI__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[18].name = "readyForTask";
TM__Qzgg5NBLvccay07XFph3Rw_0[0].len = 9; TM__Qzgg5NBLvccay07XFph3Rw_0[0].kind = 2; TM__Qzgg5NBLvccay07XFph3Rw_0[0].sons = &TM__Qzgg5NBLvccay07XFph3Rw_2_9[0];
NTI__AqHEWWcw2VBFjoa2Hp8Akw_.node = &TM__Qzgg5NBLvccay07XFph3Rw_0[0];
NTI__CyNApV6Mfiphj5eUnH5G1A_.size = sizeof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*);
NTI__CyNApV6Mfiphj5eUnH5G1A_.align = NIM_ALIGNOF(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*);
NTI__CyNApV6Mfiphj5eUnH5G1A_.kind = 21;
NTI__CyNApV6Mfiphj5eUnH5G1A_.base = (&NTI__AqHEWWcw2VBFjoa2Hp8Akw_);
NTI__CyNApV6Mfiphj5eUnH5G1A_.flags = 3;
}

