/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "winsock2.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_GUID__J2WQBMgezjwf6Trblkflgg tyObject_GUID__J2WQBMgezjwf6Trblkflgg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg;
typedef struct tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw;
typedef struct tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;

/* section: NIM_merge_TYPES */
typedef NI8 tyArray__9cWG514ToTTjfTPLhXXV0IQ[8];
struct tyObject_GUID__J2WQBMgezjwf6Trblkflgg {
NI32 D1;
NI16 D2;
NI16 D3;
tyArray__9cWG514ToTTjfTPLhXXV0IQ D4;
};
typedef N_STDCALL_PTR(NCSTRING, tyProc__5ctyytqoGFQ0BA1imFGbVw) (int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(int, tyProc__As5z9bYt859cLKWaorPRgQYA) (NI16 wVersionRequired, WSADATA* WSData);
typedef N_STDCALL_PTR(NI32, tyProc__aO673xGTLLxou7P7GxoCXA) (NI32 dwFlags, void* lpSource, NI32 dwMessageId, NI32 dwLanguageId, void* lpBuffer, NI32 nSize, void* arguments);
typedef N_STDCALL_PTR(void, tyProc__im9buRnIvptJfzdASYMEbBA) (void* p);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI, tyProc__9aO2cP4IgwjXF8JfUR57CHQ) (int af, int typ, int protocol);
typedef N_STDCALL_PTR(int, tyProc__IQbFr9cLT9bipWCXYfwYwjOw) (NI s);
typedef N_STDCALL_PTR(void, tyProc__X0Q3cs1Ai9bfe54O0LJQ1fQ) (NI32 para1, NI32 para2, tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg* para3);
typedef N_STDCALL_PTR(int, tyProc__m8OtNuKklv1X2vQjXQkzSA) (NI s, NI32 dwIoControlCode, void* lpvInBuffer, NI32 cbInBuffer, void* lpvOutBuffer, NI32 cbOutBuffer, NI32* lpcbBytesReturned, tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc__X0Q3cs1Ai9bfe54O0LJQ1fQ lpCompletionRoutine);
typedef N_STDCALL_PTR(NI32, tyProc__LGDJfXC77WFm4ami8tbVyg) (NI handle, NI16* buf, NI32 size);
typedef N_STDCALL_PTR(void, tyProc__9bc9cLDdaqTE6n5J78feKRYg) (tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpSystemTimeAsFileTime);
struct tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw {
NI32 dwLowDateTime;
NI32 dwHighDateTime;
};
typedef N_STDCALL_PTR(NI32, tyProc__9cfAa2qMwRsugQ9bZaJfhIcQ) (NI16* lpExistingFileName, NI16* lpNewFileName, NI32 flags);
typedef N_STDCALL_PTR(void, tyProc__Tjolzh1w2dIIpj3oCDGPFw) (NI32 dwMilliseconds);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI32, tyProc__dsGSP5d71RCsLRHTMM4ScA) (tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpIdleTime, tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpKernelTime, tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpUserTime);
typedef N_STDCALL_PTR(NI32, tyProc__Rm9bSPgU9bryMLuDkmTLzYBA) (NI hProcess, tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpCreationTime, tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpExitTime, tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpKernelTime, tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw* lpUserTime);
typedef N_STDCALL_PTR(NI, tyProc__dh38EbgnCgluxaqYvYonAg) (NI FileHandle, NI ExistingCompletionPort, NU CompletionKey, NI32 NumberOfConcurrentThreads);
typedef N_STDCALL_PTR(NI32, tyProc__JIaVmlkaszRmqoQwQevY9aA) (NI CompletionPort, NI32* lpNumberOfBytesTransferred, NU* lpCompletionKey, tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg** lpOverlapped, NI32 dwMilliseconds);
struct tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ {
int ai_flags;
int ai_family;
int ai_socktype;
int ai_protocol;
size_t ai_addrlen;
NCSTRING ai_canonname;
SOCKADDR* ai_addr;
tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ* ai_next;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NIM_CHAR tyArray__NSMq3FMCIrS8gSbyinBZ8w[14];
typedef N_STDCALL_PTR(int, tyProc__MvjKU9c5nvs0N3IrS4vNgSw) (NCSTRING nodename, NCSTRING servname, tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ* hints, tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ** res);
typedef N_STDCALL_PTR(int, tyProc__T129bsPZ4FvuSF4rGFSBKkg) (NI s, SOCKADDR* name, unsigned int namelen);
typedef N_STDCALL_PTR(void, tyProc__IV3cwg4tBg3JP8ITSKt7oQ) (tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ* ai);
struct tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg {
NI* internal;
NI* internalHigh;
NI32 offset;
NI32 offsetHigh;
NI hEvent;
};
typedef N_STDCALL_PTR(int, tyProc__kfyUyr89bETC8vA9b9aJWaMyQ) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesSent, NI32 flags, tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc__X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(int, tyProc__EzSr684Zq8WJvaKasuLSqQ) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesReceived, NI32* flags, tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc__X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef NIM_CHAR tyArray__EWK8XzFKXCg2WflN3ijhqA[257];
typedef NIM_CHAR tyArray__4249al09aeC68W9cvqMnjIYOA[129];

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__Yq5XYz2ycX5V5B9bUM4Uyiw)(NimStringDesc* path, NIM_BOOL globalSymbols);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__ALH9bdNwXEzg7MPq4PA9csvw)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(NI64, ze64__Ym9bDMq70VeyLEG9cy2hJAlw)(NI32 x);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__k6kyf4Co79a84IkK9blFuQVA_2, "Ws2_32.dll", 10);
STRING_LITERAL(TM__k6kyf4Co79a84IkK9blFuQVA_5, "Ws2_32.dll", 10);
STRING_LITERAL(TM__k6kyf4Co79a84IkK9blFuQVA_10, "kernel32", 8);
STRING_LITERAL(TM__k6kyf4Co79a84IkK9blFuQVA_11, "kernel32", 8);
N_LIB_PRIVATE TNimType NTI__C9ahX3gj0cVjII4vjiaSHBQ_;
extern TNimType NTI__nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI__BUq6xsa39af9cBdeNXAkA9azQ_;
extern TNimType NTI__S9agCYBinaYZnGWcjTdxclg_;
N_LIB_PRIVATE TNimType NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_;
N_LIB_PRIVATE TNimType NTI__nBU9bsV5o5Xw80pGpGVR8Bw_;
N_LIB_PRIVATE TNimType NTI__9boVVq0W9aThvt3y6X6MODJQ_;
N_LIB_PRIVATE TNimType NTI__9ayhTq9cybD7eA9aZA09akSNXg_;
extern TNimType NTI__BVbkP29c9aHJK9bePRvpX9bHIQ_;
extern TNimType NTI__sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTI__C9agHgxfUtpEDlac6Nu0MCw_;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE tyObject_GUID__J2WQBMgezjwf6Trblkflgg WSAID_CONNECTEX__YmR9c9crObjjK9ckt1ygsPQKg = {((NI32) 631375801), ((NI16) -8717), ((NI16) 18016), {((NI8) -114),
((NI8) -23),
((NI8) 118),
((NI8) -27),
((NI8) -116),
((NI8) 116),
((NI8) 6),
((NI8) 62)}
}
;
N_LIB_PRIVATE tyObject_GUID__J2WQBMgezjwf6Trblkflgg WSAID_ACCEPTEX__pwoOiDuyZgHBOLaI2GSBpg = {((NI32) -1254720015), ((NI16) -13396), ((NI16) 4559), {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
}
;
N_LIB_PRIVATE tyObject_GUID__J2WQBMgezjwf6Trblkflgg WSAID_GETACCEPTEXSOCKADDRS__rSjtFMq7pCHQR2EQvcKbDg = {((NI32) -1254720014), ((NI16) -13396), ((NI16) 4559), {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
}
;
N_LIB_PRIVATE tyProc__5ctyytqoGFQ0BA1imFGbVw inet_ntop_real__FVXn9aJ5AOo23ScDsZUc9aZw = NIM_NIL;
N_LIB_PRIVATE void* ws2__hGspZUrVrEMpO9aP9c3dJQPQ;
static void* TM__k6kyf4Co79a84IkK9blFuQVA_3;
tyProc__As5z9bYt859cLKWaorPRgQYA Dl_13633465_;
static void* TM__k6kyf4Co79a84IkK9blFuQVA_8;
tyProc__aO673xGTLLxou7P7GxoCXA Dl_13631835_;
tyProc__im9buRnIvptJfzdASYMEbBA Dl_13632001_;
tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_13631830_;
tyProc__9aO2cP4IgwjXF8JfUR57CHQ Dl_13633283_;
tyProc__IQbFr9cLT9bipWCXYfwYwjOw Dl_13633288_;
tyProc__m8OtNuKklv1X2vQjXQkzSA Dl_13635067_;
tyProc__LGDJfXC77WFm4ami8tbVyg Dl_13632022_;
tyProc__9bc9cLDdaqTE6n5J78feKRYg Dl_13632860_;
tyProc__9cfAa2qMwRsugQ9bZaJfhIcQ Dl_13632640_;
tyProc__Tjolzh1w2dIIpj3oCDGPFw Dl_13632864_;
tyProc__uryidYWkntM7ddjZSyxvyQ Dl_13633586_;
tyProc__dsGSP5d71RCsLRHTMM4ScA Dl_13635132_;
tyProc__Rm9bSPgU9bryMLuDkmTLzYBA Dl_13635138_;
tyProc__dh38EbgnCgluxaqYvYonAg Dl_13634091_;
tyProc__JIaVmlkaszRmqoQwQevY9aA Dl_13634097_;
tyProc__MvjKU9c5nvs0N3IrS4vNgSw Dl_13633470_;
tyProc__T129bsPZ4FvuSF4rGFSBKkg Dl_13633298_;
tyProc__IV3cwg4tBg3JP8ITSKt7oQ Dl_13633479_;
tyProc__kfyUyr89bETC8vA9b9aJWaMyQ Dl_13635106_;
tyProc__EzSr684Zq8WJvaKasuLSqQ Dl_13635082_;

/* section: NIM_merge_PROCS */
N_LIB_PRIVATE N_NIMCALL(NI64, rdFileTime__DfLqBYlqX7ZqK7NeVOk8ew)(tyObject_FILETIME__bs4NMleDDVF7xsEK0SGLBw f) {
	NI64 result;
	NI64 T1_;
	NI64 T2_;
	result = (NI64)0;
	T1_ = (NI64)0;
	T1_ = ze64__Ym9bDMq70VeyLEG9cy2hJAlw(f.dwLowDateTime);
	T2_ = (NI64)0;
	T2_ = ze64__Ym9bDMq70VeyLEG9cy2hJAlw(f.dwHighDateTime);
	result = (NI64)(T1_ | (NI64)((NU64)(T2_) << (NU64)(((NI) 32))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_winleanInit000)(void) {
{
	ws2__hGspZUrVrEMpO9aP9c3dJQPQ = loadLib__Yq5XYz2ycX5V5B9bUM4Uyiw(((NimStringDesc*) &TM__k6kyf4Co79a84IkK9blFuQVA_2), NIM_FALSE);
	{
		void* T5_;
		if (!!((ws2__hGspZUrVrEMpO9aP9c3dJQPQ == NIM_NIL))) goto LA3_;
		T5_ = (void*)0;
		T5_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(ws2__hGspZUrVrEMpO9aP9c3dJQPQ, "inet_ntop");
		inet_ntop_real__FVXn9aJ5AOo23ScDsZUc9aZw = ((tyProc__5ctyytqoGFQ0BA1imFGbVw) (T5_));
	}
	LA3_: ;
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_winleanDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__k6kyf4Co79a84IkK9blFuQVA_42_8[8];
static TNimNode* TM__k6kyf4Co79a84IkK9blFuQVA_49_5[5];
static TNimNode TM__k6kyf4Co79a84IkK9blFuQVA_0[17];

/* section: NIM_merge_TYPE_INIT3 */
NTI__C9ahX3gj0cVjII4vjiaSHBQ_.size = sizeof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ);
NTI__C9ahX3gj0cVjII4vjiaSHBQ_.align = NIM_ALIGNOF(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ);
NTI__C9ahX3gj0cVjII4vjiaSHBQ_.kind = 18;
NTI__C9ahX3gj0cVjII4vjiaSHBQ_.base = 0;
NTI__C9ahX3gj0cVjII4vjiaSHBQ_.flags = 3;
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[0] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[1];
TM__k6kyf4Co79a84IkK9blFuQVA_0[1].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[1].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_flags);
TM__k6kyf4Co79a84IkK9blFuQVA_0[1].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[1].name = "ai_flags";
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[1] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[2];
TM__k6kyf4Co79a84IkK9blFuQVA_0[2].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[2].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_family);
TM__k6kyf4Co79a84IkK9blFuQVA_0[2].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[2].name = "ai_family";
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[2] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[3];
TM__k6kyf4Co79a84IkK9blFuQVA_0[3].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[3].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_socktype);
TM__k6kyf4Co79a84IkK9blFuQVA_0[3].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[3].name = "ai_socktype";
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[3] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[4];
TM__k6kyf4Co79a84IkK9blFuQVA_0[4].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[4].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_protocol);
TM__k6kyf4Co79a84IkK9blFuQVA_0[4].typ = (&NTI__nlCscttRCss70IBTyuBqnA_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[4].name = "ai_protocol";
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[4] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[5];
TM__k6kyf4Co79a84IkK9blFuQVA_0[5].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[5].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_addrlen);
TM__k6kyf4Co79a84IkK9blFuQVA_0[5].typ = (&NTI__BUq6xsa39af9cBdeNXAkA9azQ_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[5].name = "ai_addrlen";
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[5] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[6];
TM__k6kyf4Co79a84IkK9blFuQVA_0[6].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[6].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_canonname);
TM__k6kyf4Co79a84IkK9blFuQVA_0[6].typ = (&NTI__S9agCYBinaYZnGWcjTdxclg_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[6].name = "ai_canonname";
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[6] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[7];
NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_.size = sizeof(SOCKADDR);
NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_.align = NIM_ALIGNOF(SOCKADDR);
NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_.kind = 18;
NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_.base = 0;
NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_.flags = 3;
NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_.node = &TM__k6kyf4Co79a84IkK9blFuQVA_0[8];
NTI__nBU9bsV5o5Xw80pGpGVR8Bw_.size = sizeof(SOCKADDR*);
NTI__nBU9bsV5o5Xw80pGpGVR8Bw_.align = NIM_ALIGNOF(SOCKADDR*);
NTI__nBU9bsV5o5Xw80pGpGVR8Bw_.kind = 21;
NTI__nBU9bsV5o5Xw80pGpGVR8Bw_.base = (&NTI__iPePZVyyc9cQV6V9cwz9ajG9bg_);
NTI__nBU9bsV5o5Xw80pGpGVR8Bw_.flags = 3;
TM__k6kyf4Co79a84IkK9blFuQVA_0[7].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[7].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_addr);
TM__k6kyf4Co79a84IkK9blFuQVA_0[7].typ = (&NTI__nBU9bsV5o5Xw80pGpGVR8Bw_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[7].name = "ai_addr";
TM__k6kyf4Co79a84IkK9blFuQVA_42_8[7] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[9];
TM__k6kyf4Co79a84IkK9blFuQVA_0[9].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[9].offset = offsetof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ, ai_next);
TM__k6kyf4Co79a84IkK9blFuQVA_0[9].typ = (&NTI__9boVVq0W9aThvt3y6X6MODJQ_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[9].name = "ai_next";
TM__k6kyf4Co79a84IkK9blFuQVA_0[0].len = 8; TM__k6kyf4Co79a84IkK9blFuQVA_0[0].kind = 2; TM__k6kyf4Co79a84IkK9blFuQVA_0[0].sons = &TM__k6kyf4Co79a84IkK9blFuQVA_42_8[0];
NTI__C9ahX3gj0cVjII4vjiaSHBQ_.node = &TM__k6kyf4Co79a84IkK9blFuQVA_0[0];
NTI__9boVVq0W9aThvt3y6X6MODJQ_.size = sizeof(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ*);
NTI__9boVVq0W9aThvt3y6X6MODJQ_.align = NIM_ALIGNOF(tyObject_AddrInfo__C9ahX3gj0cVjII4vjiaSHBQ*);
NTI__9boVVq0W9aThvt3y6X6MODJQ_.kind = 21;
NTI__9boVVq0W9aThvt3y6X6MODJQ_.base = (&NTI__C9ahX3gj0cVjII4vjiaSHBQ_);
NTI__9boVVq0W9aThvt3y6X6MODJQ_.flags = 3;
NTI__9ayhTq9cybD7eA9aZA09akSNXg_.size = sizeof(tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg);
NTI__9ayhTq9cybD7eA9aZA09akSNXg_.align = NIM_ALIGNOF(tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg);
NTI__9ayhTq9cybD7eA9aZA09akSNXg_.kind = 18;
NTI__9ayhTq9cybD7eA9aZA09akSNXg_.base = 0;
NTI__9ayhTq9cybD7eA9aZA09akSNXg_.flags = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_49_5[0] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[11];
TM__k6kyf4Co79a84IkK9blFuQVA_0[11].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[11].offset = offsetof(tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg, internal);
TM__k6kyf4Co79a84IkK9blFuQVA_0[11].typ = (&NTI__BVbkP29c9aHJK9bePRvpX9bHIQ_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[11].name = "internal";
TM__k6kyf4Co79a84IkK9blFuQVA_49_5[1] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[12];
TM__k6kyf4Co79a84IkK9blFuQVA_0[12].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[12].offset = offsetof(tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg, internalHigh);
TM__k6kyf4Co79a84IkK9blFuQVA_0[12].typ = (&NTI__BVbkP29c9aHJK9bePRvpX9bHIQ_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[12].name = "internalHigh";
TM__k6kyf4Co79a84IkK9blFuQVA_49_5[2] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[13];
TM__k6kyf4Co79a84IkK9blFuQVA_0[13].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[13].offset = offsetof(tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg, offset);
TM__k6kyf4Co79a84IkK9blFuQVA_0[13].typ = (&NTI__sVg18TP9cLifHyygRe9cro9aA_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[13].name = "offset";
TM__k6kyf4Co79a84IkK9blFuQVA_49_5[3] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[14];
TM__k6kyf4Co79a84IkK9blFuQVA_0[14].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[14].offset = offsetof(tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg, offsetHigh);
TM__k6kyf4Co79a84IkK9blFuQVA_0[14].typ = (&NTI__sVg18TP9cLifHyygRe9cro9aA_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[14].name = "offsetHigh";
TM__k6kyf4Co79a84IkK9blFuQVA_49_5[4] = &TM__k6kyf4Co79a84IkK9blFuQVA_0[15];
TM__k6kyf4Co79a84IkK9blFuQVA_0[15].kind = 1;
TM__k6kyf4Co79a84IkK9blFuQVA_0[15].offset = offsetof(tyObject_OVERLAPPED__9ayhTq9cybD7eA9aZA09akSNXg, hEvent);
TM__k6kyf4Co79a84IkK9blFuQVA_0[15].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__k6kyf4Co79a84IkK9blFuQVA_0[15].name = "hEvent";
TM__k6kyf4Co79a84IkK9blFuQVA_0[10].len = 5; TM__k6kyf4Co79a84IkK9blFuQVA_0[10].kind = 2; TM__k6kyf4Co79a84IkK9blFuQVA_0[10].sons = &TM__k6kyf4Co79a84IkK9blFuQVA_49_5[0];
NTI__9ayhTq9cybD7eA9aZA09akSNXg_.node = &TM__k6kyf4Co79a84IkK9blFuQVA_0[10];
NTI__C9agHgxfUtpEDlac6Nu0MCw_.size = sizeof(WSABUF);
NTI__C9agHgxfUtpEDlac6Nu0MCw_.align = NIM_ALIGNOF(WSABUF);
NTI__C9agHgxfUtpEDlac6Nu0MCw_.kind = 18;
NTI__C9agHgxfUtpEDlac6Nu0MCw_.base = 0;
NTI__C9agHgxfUtpEDlac6Nu0MCw_.flags = 3;
NTI__C9agHgxfUtpEDlac6Nu0MCw_.node = &TM__k6kyf4Co79a84IkK9blFuQVA_0[16];

/* section: NIM_merge_DYNLIB_INIT */
if (!((TM__k6kyf4Co79a84IkK9blFuQVA_3 = nimLoadLibrary(((NimStringDesc*) &TM__k6kyf4Co79a84IkK9blFuQVA_5)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__k6kyf4Co79a84IkK9blFuQVA_2));
	Dl_13633465_ = (tyProc__As5z9bYt859cLKWaorPRgQYA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "WSAStartup");
if (!((TM__k6kyf4Co79a84IkK9blFuQVA_8 = nimLoadLibrary(((NimStringDesc*) &TM__k6kyf4Co79a84IkK9blFuQVA_10)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__k6kyf4Co79a84IkK9blFuQVA_11));
	Dl_13631835_ = (tyProc__aO673xGTLLxou7P7GxoCXA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "FormatMessageW");
	Dl_13632001_ = (tyProc__im9buRnIvptJfzdASYMEbBA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "LocalFree");
	Dl_13631830_ = (tyProc__9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "GetLastError");
	Dl_13633283_ = (tyProc__9aO2cP4IgwjXF8JfUR57CHQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "socket");
	Dl_13633288_ = (tyProc__IQbFr9cLT9bipWCXYfwYwjOw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "closesocket");
	Dl_13635067_ = (tyProc__m8OtNuKklv1X2vQjXQkzSA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "WSAIoctl");
	Dl_13632022_ = (tyProc__LGDJfXC77WFm4ami8tbVyg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "GetModuleFileNameW");
	Dl_13632860_ = (tyProc__9bc9cLDdaqTE6n5J78feKRYg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "GetSystemTimeAsFileTime");
	Dl_13632640_ = (tyProc__9cfAa2qMwRsugQ9bZaJfhIcQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "MoveFileExW");
	Dl_13632864_ = (tyProc__Tjolzh1w2dIIpj3oCDGPFw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "Sleep");
	Dl_13633586_ = (tyProc__uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "GetCurrentProcess");
	Dl_13635132_ = (tyProc__dsGSP5d71RCsLRHTMM4ScA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "GetSystemTimes");
	Dl_13635138_ = (tyProc__Rm9bSPgU9bryMLuDkmTLzYBA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "GetProcessTimes");
	Dl_13634091_ = (tyProc__dh38EbgnCgluxaqYvYonAg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "CreateIoCompletionPort");
	Dl_13634097_ = (tyProc__JIaVmlkaszRmqoQwQevY9aA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_8, "GetQueuedCompletionStatus");
	Dl_13633470_ = (tyProc__MvjKU9c5nvs0N3IrS4vNgSw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "getaddrinfo");
	Dl_13633298_ = (tyProc__T129bsPZ4FvuSF4rGFSBKkg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "bind");
	Dl_13633479_ = (tyProc__IV3cwg4tBg3JP8ITSKt7oQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "freeaddrinfo");
	Dl_13635106_ = (tyProc__kfyUyr89bETC8vA9b9aJWaMyQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "WSASend");
	Dl_13635082_ = (tyProc__EzSr684Zq8WJvaKasuLSqQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_3, "WSARecv");
}

