[dependencies]
chrono = "0.4"

[dependencies.polars-arrow]
features = ["compute"]
path = "../polars-arrow"
version = "0.19.0"

[package]
authors = ["ritchie46 <ritchie46@gmail.com>"]
description = "Time related code for the polars dataframe library"
edition = "2021"
license = "MIT"
name = "polars-time"
version = "0.1.1"
