---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.general
  tasks:
    - name: "Load proxmox secrets."
      include_vars: "{{ molecule_yml.driver.options.proxmox_secrets }}"
      when: molecule_yml.driver.options.proxmox_secrets is defined
      no_log: true

    - name: "Create molecule instance(s)."
      proxmox_kvm:
        api_host: "{{ api_host | d(molecule_yml.driver.options.api_host) | d(omit) }}"
        api_user: "{{ api_user | d(molecule_yml.driver.options.api_user) | d(omit) }}"
        api_password: "{{ api_password | d(molecule_yml.driver.options.api_password) | d(omit) }}"
        api_token_id: "{{ api_token_id | d(molecule_yml.driver.options.api_token_id) | d(omit) }}"
        api_token_secret: "{{ api_token_secret | d(molecule_yml.driver.options.api_token_secret) | d(omit) }}"
        vmid: "{{ vm.template_vmid }}"
        clone: "{{ vm.name }}"
        name: "{{ vm.name }}"
        node: "{{ molecule_yml.driver.options.node }}"
        timeout: 300
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: vm
      register: proxmox_clone

    - name: "Start molecule instance(s)."
      proxmox_kvm:
        api_host: "{{ api_host | d(molecule_yml.driver.options.api_host) | d(omit) }}"
        api_user: "{{ api_user | d(molecule_yml.driver.options.api_user) | d(omit) }}"
        api_password: "{{ api_password | d(molecule_yml.driver.options.api_password) | d(omit) }}"
        api_token_id: "{{ api_token_id | d(molecule_yml.driver.options.api_token_id) | d(omit) }}"
        api_token_secret: "{{ api_token_secret | d(molecule_yml.driver.options.api_token_secret) | d(omit) }}"
        vmid: "{{ vmid }}"
        state: started
        timeout: 300
      loop: "{{ proxmox_clone.results | map(attribute='vmid') }}"
      loop_control:
        loop_var: vmid
      register: proxmox_start

    - name: "Wait for instance(s) to start."
      proxmox_qemu_agent:
        api_host: "{{ api_host | d(molecule_yml.driver.options.api_host) | d(omit) }}"
        api_user: "{{ api_user | d(molecule_yml.driver.options.api_user) | d(omit) }}"
        api_password: "{{ api_password | d(molecule_yml.driver.options.api_password) | d(omit) }}"
        api_token_id: "{{ api_token_id | d(molecule_yml.driver.options.api_token_id) | d(omit) }}"
        api_token_secret: "{{ api_token_secret | d(molecule_yml.driver.options.api_token_secret) | d(omit) }}"
        vmid: "{{ vmid }}"
      loop: "{{ proxmox_start.results | map(attribute='vmid') }}"
      loop_control:
        loop_var: vmid
      register: qemu_query

    - name: "Populate instance configs."
      set_fact:
        instance_config:
          instance: "{{ item.vm.name }}"
          address: "{{ item.vm.addresses[0] }}"
          user: "{{ molecule_yml.driver.options.ssh_user | d('molecule') }}"
          port: 22
          identity_file: "{{ molecule_yml.driver.options.ssh_identity_file }}"
          vmid: "{{ item.vm.vmid }}"
      loop: "{{ qemu_query.results }}"
      register: instance_configs

    - name: "Write instance configs."
      copy:
        content: "{{ instance_configs.results | map(attribute='ansible_facts.instance_config') | to_nice_yaml }}"
        dest: "{{ molecule_instance_config }}"
