[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "extendable_pydantic"
authors = [{name = "Laurent Mignon", email = "laurent.mignon@acsone.eu"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]
dynamic = ["version", "description"]
dependencies = [
    "extendable",
    "pydantic",
]
requires-python = ">=3.6"

[project.optional-dependencies]
test = [
    "pytest",
    "coverage[toml]",
]
mypy = [
    "mypy",
]

[project.urls]
Source = "https://github.com/lmignon/pydantic-ext"

[tool.flit.sdist]
exclude = [".github"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.coverage.run]
branch = true
source_pkgs = ["extendable_pydantic"]

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
]
