
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T12:52:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7dfae69884564cba4a49fdb4e6494eedb4abc7bb",
 "version": "1.11.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
