# Main package description
[tool.poetry]
name = "Digital-Twin-Distiller"
version = "2022.1"
description = "Python project for creating a long-lasting, encapsulated version of your numerical simulation or your machine-learning-based project."
authors = [
    "MONTANA Knowledge Management ltd. <info@distiller.dev>"
]
license = "AGPL"

# Project dependencies only
[tool.poetry.dependencies]
python = ">=3.8,<3.10"
Jinja2 = "^3.0.1"
aiofiles = "^0.7.0"
ezdxf = "^0.16.5"
fastapi = "^0.70"
gmsh = "^4.8.4"
importlib-resources = "^5.4.0"
mkdocs-git-revision-date-plugin = "^0.3.1"
mkdocs-material = "^7.3.6"
mkdocs = "^1.2.3"
mkdocstrings = "^0.16.2"
networkx = "^2.6.3"
numpy = "^1.21.0"
pydantic = "^1.8.2"
pygmsh = "^7.1.13"
pyvista = "^0.32.1"
scipy = "^1.7.0"
svgpathtools = "^1.4.2"
uvicorn = "^0.15.0"
vedo = "^2021"

# Dependencies for developers
Shapely = "^1.8.0"
tika = "^1.24"
scikit-learn = "^1.0.1"
sklearn = "^0.0"
gensim = "^4.1.2"
tqdm = "^4.62.3"
fasttext = "^0.9.2"
python-markdown-math = "^0.8"
# list all devtools here
[tool.poetry.dev-dependencies]
black = "*"
coverage = "*"
pre-commit = "*"
pytest = "*"
isort = "*"
pyupgrade = "^2.29"
pylint = "^2.11.1"
requests = "^2.26.0"


# build system setup
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# DEVTOOLS CONFIG #

#BLACK
[tool.black]
line-length = 120
target-version = ['py38']
force-exclude = '''
  (
    digital_twin_distiller/resources/
  | tests/solver_script_references/
  )
'''
quiet = true


# COVERAGE
# https://coverage.readthedocs.io/en/6.1.1/config.html

[tool.coverage.run]
command_line = "-m py.test"
source = ['digital_twin_distiller']
branch = true
# omit = []

[tool.coverage.report]
sort = "cover"
exclude_lines = [
    'if __name__ == "__main__":',
    'def __repr__',
    'def __str',
    '@(abc\.)?abstractmethod'
]
omit = ['tests', 'examples']



# ISORT
# https://pycqa.github.io/isort/docs/configuration/options.html

[tool.isort]
profile = "black"
line_length = 120
case_sensitive = true
use_parentheses = false
include_trailing_comma = true
multi_line_output = 3
force_grid_wrap = 0
quiet = true
skip="__init__.py"

[tool.pylint.MASTER]
max-line-length = 120
fail-under = 0.85
ignore = ['LICENSE']
ignore-paths = ['tests', 'resources', 'examples',
    'digital-twin-distiller/resources']
disable = [
    "bad-continuation",
    "duplicate-code",
    "invalid-name",
    "missing-docstring",
    "too-few-public-methods",
]

# [too.pylint.message_control]
# max-line-length = 80
# disable = [
#   "missing-docstring",
#   "unused-argument",
#   "no-value-for-parameter",
#   "no-member",
#   "no-else-return",
#   "bad-whitespace",
#   "bad-continuation",
#   "line-too-long",
#   "fixme",
#   "protected-access",
#   "too-few-public-methods",
# ]

[tool.poetry.scripts]
digital-twin-distiller = "digital_twin_distiller.cli:optimize_cli"
