[project]
name = "graiax-silkcoder"
version = "0.1.6"
description = "transform audio file to silk"
keywords = [ "silkv3",]
dependencies = []
readme = "README.md"
requires-python = ">=3.6"
[[project.authors]]
name = "I Love Study"
email = "1450069615@qq.com"

[build-system]
requires = [ "pdm-pep517", "setuptools",]
build-backend = "pdm.pep517.api"

[project.license]
text = "BSD-3.0"

[project.optional-dependencies]
ffmpeg = [ "imageio-ffmpeg",]

[project.urls]
repository = "https://github.com/I-love-study/graiax-silkcoder"

[tool.pdm]
build = "build.py"
package-dir = "src"
includes = [ "src/graiax",]
source-includes = [ "src/c_silkv3/src", "src/c_silkv3/interface",]

[tool.cibuildwheel]
skip = "pp*"
