name: Python package

on: [push]

jobs:

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Check formatting
      uses: pre-commit/action@v2.0.0

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        flake8 pytest_pretty_terminal --count --show-source --statistics --max-line-length 160
        flake8 . --count --exit-zero --statistics
    - name: Lint with pylint
      run: |
        python -m pip install pylint pytest
        python -m pip install -e .
        pylint --errors-only --score=n pytest_pretty_terminal
        pylint --exit-zero --score=n --disable=C,E,R --enable=useless-suppression pytest_pretty_terminal pytest_pretty_terminal
    - name: Lint with mypy
      run: |
        python -m pip install mypy
        mypy --ignore-missing-imports pytest_pretty_terminal
