[build-system]
requires = []
build-backend = "py_build_cmake.build"
backend-path = ["src"]

[project]
name = "py-build-cmake"
readme = "README.md"
requires-python = ">=3.8"
license = { "file" = "LICENSE" }
authors = [{ "name" = "Pieter P", "email" = "pieter.p@no-email.com" }]
keywords = ["pep517", "cmake"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
]
urls = { "Documentation" = "https://tttapa.github.io/py-build-cmake" }
dependencies = ["distlib", "flit"]
dynamic = ["version", "description"]

[tool.py-build-cmake.sdist]
include = []
exclude = []
