[tool.poetry]
name = "fastapi-returns-router"
version = "1.0.1"
description = "This FastAPI Router Implementation bridges the gap between FastAPI and Returns"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ikollipara/fastapi-returns"
authors = ["Ian Kollipara <ian.kollipara@cune.org>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.72.0"
returns = "^0.18.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"
mypy = "^0.931"
black = "^21.12b0"
coverage = "^6.2"
requests = "^2.27.1"
ipython = "^8.0.0"
uvicorn = "^0.17.0"
trio = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
