segment_name_list = [
    "ABS",
    "ACC",
    "ADD",
    "AFF",
    "AIG",
    "AIL",
    "AIP",
    "AIS",
    "AL1",
    "APR",
    "ARQ",
    "AUT",
    "BHS",
    "BLC",
    "BLG",
    "BPO",
    "BPX",
    "BTS",
    "BTX",
    "CDM",
    "CER",
    "CM0",
    "CM1",
    "CM2",
    "CNS",
    "CON",
    "CSP",
    "CSR",
    "CSS",
    "CTD",
    "CTI",
    "DB1",
    "DG1",
    "DRG",
    "DSC",
    "DSP",
    "ECD",
    "ECR",
    "EDU",
    "EQL",
    "EQP",
    "EQU",
    "ERQ",
    "ERR",
    "EVN",
    "FAC",
    "FHS",
    "FT1",
    "FTS",
    "GOL",
    "GP1",
    "GP2",
    "GT1",
    "IAM",
    "IIM",
    "IN1",
    "IN2",
    "IN3",
    "INV",
    "IPC",
    "ISD",
    "LAN",
    "LCC",
    "LCH",
    "LDP",
    "LOC",
    "LRL",
    "MFA",
    "MFE",
    "MFI",
    "MRG",
    "MSA",
    "MSH",
    "NCK",
    "NDS",
    "NK1",
    "NPU",
    "NSC",
    "NST",
    "NTE",
    "OBR",
    "OBX",
    "ODS",
    "ODT",
    "OM1",
    "OM2",
    "OM3",
    "OM4",
    "OM5",
    "OM6",
    "OM7",
    "ORC",
    "ORG",
    "OVR",
    "PCR",
    "PD1",
    "PDA",
    "PDC",
    "PEO",
    "PES",
    "PID",
    "PR1",
    "PRA",
    "PRB",
    "PRC",
    "PRD",
    "PSH",
    "PTH",
    "PV1",
    "PV2",
    "QAK",
    "QID",
    "QPD",
    "QRD",
    "QRF",
    "QRI",
    "RCP",
    "RDF",
    "RDT",
    "RF1",
    "RGS",
    "RMI",
    "ROL",
    "RQ1",
    "RQD",
    "RXA",
    "RXC",
    "RXD",
    "RXE",
    "RXG",
    "RXO",
    "RXR",
    "SAC",
    "SCH",
    "SFT",
    "SID",
    "SPM",
    "SPR",
    "STF",
    "TCC",
    "TCD",
    "TQ1",
    "TQ2",
    "TXA",
    "UB1",
    "UB2",
    "URD",
    "URS",
    "VAR",
    "VTQ"
]

segment_name_dict = {
    "ABS": "Abstract",
    "ACC": "Accident",
    "ADD": "Addendum",
    "AFF": "Professional Affiliation",
    "AIG": "Appointment Information - General Resource",
    "AIL": "Appointment Information - Location Resource",
    "AIP": "Appointment Information - Personnel Resource",
    "AIS": "Appointment Information",
    "AL1": "Patient Allergy Information",
    "APR": "Appointment Preferences",
    "ARQ": "Appointment Request",
    "AUT": "Authorization Information",
    "BHS": "Batch Header Segment",
    "BLC": "Blood Code",
    "BLG": "Billing",
    "BPO": "Blood product order",
    "BPX": "Blood product dispense status",
    "BTS": "Batch Trailer Segment",
    "BTX": "Blood Product Transfusion/Disposition",
    "CDM": "Charge Description Master",
    "CER": "Certificate Detail",
    "CM0": "Clinical Study Master",
    "CM1": "Clinical Study Phase Master",
    "CM2": "Clinical Study Schedule Master",
    "CNS": "Clear Notification",
    "CON": "Consent",
    "CSP": "Clinical Study Phase",
    "CSR": "Clinical Study Registration",
    "CSS": "Clinical Study Data Schedule Segment",
    "CTD": "Contact Data",
    "CTI": "Clinical Trial Identification",
    "DB1": "Disability",
    "DG1": "Diagnosis",
    "DRG": "Diagnosis Related Group",
    "DSC": "Continuation Pointer",
    "DSP": "Display Data",
    "ECD": "Equipment Command",
    "ECR": "Equipment Command Response",
    "EDU": "Educational Detail",
    "EQL": "Embedded Query Language",
    "EQP": "Equipment/log Service",
    "EQU": "Equipment Detail",
    "ERQ": "Event replay query",
    "ERR": "Error",
    "EVN": "Event Type",
    "FAC": "Facility",
    "FHS": "File Header Segment",
    "FT1": "Financial Transaction",
    "FTS": "File Trailer Segment",
    "GOL": "Goal Detail",
    "GP1": "Grouping/Reimbursement - Visit",
    "GP2": "Grouping/Reimbursement - Procedure Line Item",
    "GT1": "Guarantor",
    "IAM": "Patient Adverse Reaction Information",
    "IIM": "Inventory Item Master",
    "IN1": "Insurance",
    "IN2": "Insurance Additional Information",
    "IN3": "Insurance Additional Information, Certification",
    "INV": "Inventory Detail",
    "IPC": "Imaging Procedure Control Segment",
    "ISD": "Interaction Status Detail",
    "LAN": "Language Detail",
    "LCC": "Location Charge Code",
    "LCH": "Location Characteristic",
    "LDP": "Location Department",
    "LOC": "Location Identification",
    "LRL": "Location Relationship",
    "MFA": "Master File Acknowledgment",
    "MFE": "Master File Entry",
    "MFI": "Master File Identification",
    "MRG": "Merge Patient Information",
    "MSA": "Message Acknowledgment",
    "MSH": "Message Header",
    "NCK": "System Clock",
    "NDS": "Notification Detail",
    "NK1": "Next of Kin / Associated Parties",
    "NPU": "Bed Status Update",
    "NSC": "Application Status Change",
    "NST": "Application control level statistics",
    "NTE": "Notes and Comments",
    "OBR": "Observation Request",
    "OBX": "Observation/Result",
    "ODS": "Dietary Orders, Supplements, and Preferences",
    "ODT": "Diet Tray Instructions",
    "OM1": "General Segment",
    "OM2": "Numeric Observation",
    "OM3": "Categorical Service/Test/Observation",
    "OM4": "Observations that Require Specimens",
    "OM5": "Observation Batteries (Sets)",
    "OM6": "Observations that are Calculated from Other Observations",
    "OM7": "Additional Basic Attributes",
    "ORC": "Common Order",
    "ORG": "Practitioner Organization Unit",
    "OVR": "Override Segment",
    "PCR": "Possible Causal Relationship",
    "PD1": "Patient Additional Demographic",
    "PDA": "Patient Death and Autopsy",
    "PDC": "Product Detail Country",
    "PEO": "Product Experience Observation",
    "PES": "Product Experience Sender",
    "PID": "Patient Identification",
    "PR1": "Procedures",
    "PRA": "Practitioner Detail",
    "PRB": "Problem Details",
    "PRC": "Pricing",
    "PRD": "Provider Data",
    "PSH": "Product Summary Header",
    "PTH": "Pathway",
    "PV1": "Patient Visit",
    "PV2": "Patient Visit - Additional Information",
    "QAK": "Query Acknowledgment",
    "QID": "Query Identification",
    "QPD": "Query Parameter Definition",
    "QRD": "Original-Style Query Definition",
    "QRF": "Original style query filter",
    "QRI": "Query Response Instance",
    "RCP": "Response Control Parameter",
    "RDF": "Table Row Definition",
    "RDT": "Table Row Data",
    "RF1": "Referral Information",
    "RGS": "Resource Group",
    "RMI": "Risk Management Incident",
    "ROL": "Role",
    "RQ1": "Requisition Detail-1",
    "RQD": "Requisition Detail",
    "RXA": "Pharmacy/Treatment Administration",
    "RXC": "Pharmacy/Treatment Component Order",
    "RXD": "Pharmacy/Treatment Dispense",
    "RXE": "Pharmacy/Treatment Encoded Order",
    "RXG": "Pharmacy/Treatment Give",
    "RXO": "Pharmacy/Treatment Order",
    "RXR": "Pharmacy/Treatment Route",
    "SAC": "Specimen Container detail",
    "SCH": "Scheduling Activity Information",
    "SFT": "Software Segment",
    "SID": "Substance Identifier",
    "SPM": "Specimen",
    "SPR": "Stored Procedure Request Definition",
    "STF": "Staff Identification",
    "TCC": "Test Code Configuration",
    "TCD": "Test Code Detail",
    "TQ1": "Timing/Quantity",
    "TQ2": "Timing/Quantity Relationship",
    "TXA": "Transcription Document Header",
    "UB1": "UB82 Data",
    "UB2": "UB92 Data",
    "URD": "Results/update Definition",
    "URS": "Unsolicited Selection",
    "VAR": "Variance",
    "VTQ": "Virtual Table Query Request"
}

element_group = {
    "ABS": [
        "Discharge Care Provider",
        "Transfer Medical Service Code",
        "Severity of Illness Code",
        "Date/Time of Attestation",
        "Attested By",
        "Triage Code",
        "Abstract Completion Date/Time",
        "Abstracted By",
        "Case Category Code",
        "Caesarian Section Indicator",
        "Gestation Category Code",
        "Gestation Period - Weeks",
        "Newborn Code",
        "Stillborn Indicator"
    ],
    "ACC": [
        "Accident Date/Time",
        "Accident Code",
        "Accident Location",
        "Auto Accident State",
        "Accident Job Related Indicator",
        "Accident Death Indicator",
        "Entered By",
        "Accident Description",
        "Brought In By",
        "Police Notified Indicator",
        "Accident Address"
    ],
    "ADD": [
        "Addendum Continuation Pointer"
    ],
    "AFF": [
        "Set ID - AFF",
        "Professional Organization",
        "Professional Organization Address",
        "Professional Organization Affiliation Date Range",
        "Professional Affiliation Additional Information"
    ],
    "AIG": [
        "Set ID - AIG",
        "Segment Action Code",
        "Resource ID",
        "Resource Type",
        "Resource Group",
        "Resource Quantity",
        "Resource Quantity Units",
        "Start Date/Time",
        "Start Date/Time Offset",
        "Start Date/Time Offset Units",
        "Duration",
        "Duration Units",
        "Allow Substitution Code",
        "Filler Status Code"
    ],
    "AIL": [
        "Set ID - AIL",
        "Segment Action Code",
        "Location Resource ID",
        "Location Type-AIL",
        "Location Group",
        "Start Date/Time",
        "Start Date/Time Offset",
        "Start Date/Time Offset Units",
        "Duration",
        "Duration Units",
        "Allow Substitution Code",
        "Filler Status Code"
    ],
    "AIP": [
        "Set ID - AIP",
        "Segment Action Code",
        "Personnel Resource ID",
        "Resource Type",
        "Resource Group",
        "Start Date/Time",
        "Start Date/Time Offset",
        "Start Date/Time Offset Units",
        "Duration",
        "Duration Units",
        "Allow Substitution Code",
        "Filler Status Code"
    ],
    "AIS": [
        "Set ID - AIS",
        "Segment Action Code",
        "Universal Service Identifier",
        "Start Date/Time",
        "Start Date/Time Offset",
        "Start Date/Time Offset Units",
        "Duration",
        "Duration Units",
        "Allow Substitution Code",
        "Filler Status Code",
        "Placer Supplemental Service Information",
        "Filler Supplemental Service Information"
    ],
    "AL1": [
        "Set ID - AL1",
        "Allergen Type Code",
        "Allergen Code/Mnemonic/Description",
        "Allergy Severity Code",
        "Allergy Reaction Code",
        "Identification Date"
    ],
    "APR": [
        "Time Selection Criteria",
        "Resource Selection Criteria",
        "Location Selection Criteria",
        "Slot Spacing Criteria",
        "Filler Override Criteria"
    ],
    "ARQ": [
        "Placer Appointment ID",
        "Filler Appointment ID",
        "Occurrence Number",
        "Placer Group Number",
        "Schedule ID",
        "Request Event Reason",
        "Appointment Reason",
        "Appointment Type",
        "Appointment Duration",
        "Appointment Duration Units",
        "Requested Start Date/Time Range",
        "Priority-ARQ",
        "Repeating Interval",
        "Repeating Interval Duration",
        "Placer Contact Person",
        "Placer Contact Phone Number",
        "Placer Contact Address",
        "Placer Contact Location",
        "Entered By Person",
        "Entered By Phone Number",
        "Entered By Location",
        "Parent Placer Appointment ID",
        "Parent Filler Appointment ID",
        "Placer Order Number",
        "Filler Order Number"
    ],
    "AUT": [
        "Authorizing Payor, Plan ID",
        "Authorizing Payor, Company ID",
        "Authorizing Payor, Company Name",
        "Authorization Effective Date",
        "Authorization Expiration Date",
        "Authorization Identifier",
        "Reimbursement Limit",
        "Requested Number of Treatments",
        "Authorized Number of Treatments",
        "Process Date"
    ],
    "BHS": [
        "Batch Field Separator",
        "Batch Encoding Characters",
        "Batch Sending Application",
        "Batch Sending Facility",
        "Batch Receiving Application",
        "Batch Receiving Facility ",
        "Batch Creation Date/Time",
        "Batch Security",
        "Batch Name/ID/Type",
        "Batch Comment",
        "Batch Control ID",
        "Reference Batch Control ID"
    ],
    "BLC": [
        "Blood Product Code",
        "Blood Amount"
    ],
    "BLG": [
        "When to Charge",
        "Charge Type",
        "Account ID",
        "Charge Type Reason"
    ],
    "BPO": [
        "Set ID - BPO",
        "BP Universal Service ID",
        "BP  Processing Requirements",
        "BP Quantity",
        "BP Amount",
        "BP Units",
        "BP Intended Use Date/Time",
        "BP Intended Dispense From Location",
        "BP Intended Dispense From Address",
        "BP Requested Dispense Date/Time",
        "BP Requested Dispense To Location",
        "BP Requested Dispense To Address",
        "BP Indication for Use",
        "BP Informed Consent Indicator"
    ],
    "BPX": [
        "Set ID - BPX",
        "BP Dispense Status",
        "BP Status",
        "BP Date/Time of Status",
        "BC Donation ID",
        "BC Component",
        "BC Donation Type / Intended Use",
        "CP Commercial Product",
        "CP Manufacturer",
        "CP Lot Number",
        "BP Blood Group",
        "BC Special Testing",
        "BP Expiration Date/Time",
        "BP Quantity",
        "BP Amount",
        "BP Units",
        "BP Unique ID",
        "BP Actual Dispensed To Location",
        "BP Actual Dispensed To Address",
        "BP Dispensed to Receiver",
        "BP Dispensing Individual"
    ],
    "BTS": [
        "Batch Message Count",
        "Batch Comment",
        "Batch Totals"
    ],
    "BTX": [
        "Set ID - BTX",
        "BC Donation ID",
        "BC Component",
        "BC Blood Group",
        "CP Commercial Product",
        "CP Manufacturer",
        "CP Lot Number",
        "BP Quantity",
        "BP Amount",
        "BP Units",
        "BP Transfusion/Disposition Status",
        "BP Message Status",
        "BP Date/Time of Status",
        "BP Administrator",
        "BP Verifier",
        "BP Transfusion Start Date/Time of Status",
        "BP Transfusion End Date/Time of Status",
        "BP Adverse Reaction Type",
        "BP Transfusion Interrupted Reason"
    ],
    "CDM": [
        "Primary Key Value - CDM",
        "Charge Code Alias",
        "Charge Description Short",
        "Charge Description Long",
        "Description Override Indicator",
        "Exploding Charges",
        "Procedure Code",
        "Active/Inactive Flag",
        "Inventory Number",
        "Resource Load",
        "Contract Number",
        "Contract Organization",
        "Room Fee Indicator"
    ],
    "CER": [
        "Set ID - CER",
        "Serial Number",
        "Version",
        "Granting Authority",
        "Issuing Authority",
        "Signature of Issuing Authority",
        "Granting Country",
        "Granting State/Province",
        "Granting County/Parish",
        "Certificate Type",
        "Certificate Domain",
        "Subject ID",
        "Subject Name",
        "Subject Directory Attribute Extension (Health Professional Data)",
        "Subject Public Key Info",
        "Authority Key Identifier",
        "Basic Constraint",
        "CRL Distribution Point",
        "Jurisdiction Country",
        "Jurisdiction State/Province",
        "Jurisdiction County/Parish",
        "Jurisdiction Breadth",
        "Granting Date",
        "Issuing Date",
        "Activation Date",
        "Inactivation Date",
        "Expiration Date",
        "Renewal Date",
        "Revocation Date",
        "Revocation Reason Code",
        "Certificate Status"
    ],
    "CM0": [
        "Set ID - CM0",
        "Sponsor Study ID",
        "Alternate Study ID",
        "Title of Study",
        "Chairman of Study",
        "Last IRB Approval Date",
        "Total Accrual to Date",
        "Last Accrual Date",
        "Contact for Study",
        "Contact's Telephone Number",
        "Contact's Address"
    ],
    "CM1": [
        "Set ID - CM1",
        "Study Phase Identifier",
        "Description of Study Phase"
    ],
    "CM2": [
        "Set ID - CM2",
        "Scheduled Time Point",
        "Description of Time Point",
        "Events Scheduled This Time Point"
    ],
    "CNS": [
        "Starting Notification Reference Number",
        "Ending Notification Reference Number",
        "Starting Notification Date/Time",
        "Ending Notification Date/Time",
        "Starting Notification Code",
        "Ending Notification Code"
    ],
    "CON": [
        "Set ID - CON",
        "Consent Type",
        "Consent Form ID",
        "Consent Form Number",
        "Consent Text",
        "Subject-specific Consent Text",
        "Consent Background",
        "Subject-specific Consent Background",
        "Consenter-imposed limitations",
        "Consent Mode",
        "Consent Status",
        "Consent Discussion Date/Time",
        "Consent Decision Date/Time",
        "Consent Effective Date/Time",
        "Consent End Date/Time",
        "Subject Competence Indicator",
        "Translator Assistance Indicator",
        "Language Translated To",
        "Informational Material Supplied Indicator",
        "Consent Bypass Reason",
        "Consent Disclosure Level",
        "Consent Non-disclosure Reason",
        "Non-subject Consenter Reason",
        "Consenter ID",
        "Relationship to Subject Table"
    ],
    "CSP": [
        "Study Phase Identifier",
        "Date/time Study Phase Began",
        "Date/time Study Phase Ended",
        "Study Phase Evaluability"
    ],
    "CSR": [
        "Sponsor Study ID",
        "Alternate Study ID",
        "Institution Registering the Patient",
        "Sponsor Patient ID",
        "Alternate Patient ID - CSR",
        "Date/Time Of Patient Study Registration",
        "Person Performing Study Registration",
        "Study Authorizing Provider",
        "Date/time Patient Study Consent Signed",
        "Patient Study Eligibility Status",
        "Study Randomization Date/time",
        "Randomized Study Arm",
        "Stratum for Study Randomization",
        "Patient Evaluability Status",
        "Date/time Ended Study",
        "Reason Ended Study"
    ],
    "CSS": [
        "Study Scheduled Time Point",
        "Study Scheduled Patient Time Point",
        "Study Quality Control Codes"
    ],
    "CTD": [
        "Contact Role",
        "Contact Name",
        "Contact Address",
        "Contact Location",
        "Contact Communication Information",
        "Preferred Method of Contact",
        "Contact Identifiers"
    ],
    "CTI": [
        "Sponsor Study ID",
        "Study Phase Identifier",
        "Study Scheduled Time Point"
    ],
    "DB1": [
        "Set ID - DB1",
        "Disabled Person Code",
        "Disabled Person Identifier",
        "Disabled Indicator",
        "Disability Start Date",
        "Disability End Date",
        "Disability Return to Work Date",
        "Disability Unable to Work Date"
    ],
    "DG1": [
        "Set ID - DG1",
        "Diagnosis Coding Method",
        "Diagnosis Code - DG1",
        "Diagnosis Description",
        "Diagnosis Date/Time",
        "Diagnosis Type",
        "Major Diagnostic Category",
        "Diagnostic Related Group",
        "DRG Approval Indicator",
        "DRG Grouper Review Code",
        "Outlier Type",
        "Outlier Days",
        "Outlier Cost",
        "Grouper Version And Type",
        "Diagnosis Priority",
        "Diagnosing Clinician",
        "Diagnosis Classification",
        "Confidential Indicator",
        "Attestation Date/Time",
        "Diagnosis Identifier",
        "Diagnosis Action Code"
    ],
    "DRG": [
        "Diagnostic Related Group",
        "DRG Assigned Date/Time",
        "DRG Approval Indicator",
        "DRG Grouper Review Code",
        "Outlier Type",
        "Outlier Days",
        "Outlier Cost",
        "DRG Payor",
        "Outlier Reimbursement",
        "Confidential Indicator",
        "DRG Transfer Type"
    ],
    "DSC": [
        "Continuation Pointer",
        "Continuation Style"
    ],
    "DSP": [
        "Set ID - DSP",
        "Display Level",
        "Data Line",
        "Logical Break Point",
        "Result ID"
    ],
    "ECD": [
        "Reference Command Number",
        "Remote Control Command",
        "Response Required",
        "Requested Completion Time",
        "Parameters"
    ],
    "ECR": [
        "Command Response",
        "Date/Time Completed",
        "Command Response Parameters"
    ],
    "EDU": [
        "Set ID - EDU",
        "Academic Degree",
        "Academic Degree Program Date Range",
        "Academic Degree Program Participation Date Range",
        "Academic Degree Granted Date",
        "School",
        "School Type Code",
        "School Address",
        "Major Field of Study"
    ],
    "EQL": [
        "Query Tag",
        "Query/Response Format Code",
        "EQL Query Name",
        "EQL Query Statement"
    ],
    "EQP": [
        "Event type",
        "File Name",
        "Start Date/Time",
        "End Date/Time",
        "Transaction Data"
    ],
    "EQU": [
        "Equipment Instance Identifier",
        "Event Date/Time",
        "Equipment State",
        "Local/Remote Control State",
        "Alert Level"
    ],
    "ERQ": [
        "Query Tag",
        "Event Identifier",
        "Input Parameter List"
    ],
    "ERR": [
        "Error Code and Location",
        "Error Location",
        "HL7 Error Code",
        "Severity",
        "Application Error Code",
        "Application Error Parameter",
        "Diagnostic Information",
        "User Message",
        "Inform Person Indicator",
        "Override Type",
        "Override Reason Code",
        "Help Desk Contact Point"
    ],
    "EVN": [
        "Event Type Code",
        "Recorded Date/Time",
        "Date/Time Planned Event",
        "Event Reason Code",
        "Operator ID",
        "Event Occurred",
        "Event Facility"
    ],
    "FAC": [
        "Facility ID-FAC",
        "Facility Type",
        "Facility Address",
        "Facility Telecommunication",
        "Contact Person",
        "Contact Title",
        "Contact Address",
        "Contact Telecommunication",
        "Signature Authority",
        "Signature Authority Title",
        "Signature Authority Address",
        "Signature Authority Telecommunication"
    ],
    "FHS": [
        "File Field Separator",
        "File Encoding Characters",
        "File Sending Application",
        "File Sending Facility",
        "File Receiving Application",
        "File Receiving Facility",
        "File Creation Date/Time",
        "File Security",
        "File Name/ID",
        "File Header Comment",
        "File Control ID",
        "Reference File Control ID"
    ],
    "FT1": [
        "Set ID - FT1",
        "Transaction ID",
        "Transaction Batch ID",
        "Transaction Date",
        "Transaction Posting Date",
        "Transaction Type",
        "Transaction Code",
        "Transaction Description",
        "Transaction Description - Alt",
        "Transaction Quantity",
        "Transaction Amount - Extended",
        "Transaction Amount - Unit",
        "Department Code",
        "Insurance Plan ID",
        "Insurance Amount",
        "Assigned Patient Location",
        "Fee Schedule",
        "Patient Type",
        "Diagnosis Code - FT1",
        "Performed By Code",
        "Ordered By Code",
        "Unit Cost",
        "Filler Order Number",
        "Entered By Code",
        "Procedure Code",
        "Procedure Code Modifier",
        "Advanced Beneficiary Notice Code",
        "Medically Necessary Duplicate Procedure Reason.",
        "NDC Code",
        "Payment Reference ID",
        "Transaction Reference Key"
    ],
    "FTS": [
        "File Batch Count",
        "File Trailer Comment"
    ],
    "GOL": [
        "Action Code",
        "Action Date/Time",
        "Goal ID",
        "Goal Instance ID",
        "Episode of Care ID",
        "Goal List Priority",
        "Goal Established Date/Time",
        "Expected Goal Achieve Date/Time",
        "Goal Classification",
        "Goal Management Discipline",
        "Current Goal Review Status",
        "Current Goal Review Date/Time",
        "Next Goal Review Date/Time",
        "Previous Goal Review Date/Time",
        "Goal Review Interval",
        "Goal Evaluation",
        "Goal Evaluation Comment",
        "Goal Life Cycle Status",
        "Goal Life Cycle Status Date/Time",
        "Goal Target Type",
        "Goal Target Name"
    ],
    "GP1": [
        "Type of Bill Code",
        "Revenue Code",
        "Overall Claim Disposition Code",
        "OCE Edits per Visit Code",
        "Outlier Cost"
    ],
    "GP2": [
        "Revenue Code",
        "Number of Service Units",
        "Charge",
        "Reimbursement Action Code",
        "Denial or Rejection Code",
        "OCE Edit Code",
        "Ambulatory Payment Classification Code",
        "Modifier Edit Code",
        "Payment Adjustment Code",
        "Packaging Status Code",
        "Expected CMS Payment Amount",
        "Reimbursement Type Code",
        "Co-Pay Amount",
        "Pay Rate per Service Unit"
    ],
    "GT1": [
        "Set ID - GT1",
        "Guarantor Number",
        "Guarantor Name",
        "Guarantor Spouse Name",
        "Guarantor Address",
        "Guarantor Ph Num - Home",
        "Guarantor Ph Num - Business",
        "Guarantor Date/Time Of Birth",
        "Guarantor Administrative Sex",
        "Guarantor Type",
        "Guarantor Relationship",
        "Guarantor SSN",
        "Guarantor Date - Begin",
        "Guarantor Date - End",
        "Guarantor Priority",
        "Guarantor Employer Name",
        "Guarantor Employer Address",
        "Guarantor Employer Phone Number",
        "Guarantor Employee ID Number",
        "Guarantor Employment Status",
        "Guarantor Organization Name",
        "Guarantor Billing Hold Flag",
        "Guarantor Credit Rating Code",
        "Guarantor Death Date And Time",
        "Guarantor Death Flag",
        "Guarantor Charge Adjustment Code",
        "Guarantor Household Annual Income",
        "Guarantor Household Size",
        "Guarantor Employer ID Number",
        "Guarantor Marital Status Code",
        "Guarantor Hire Effective Date",
        "Employment Stop Date",
        "Living Dependency",
        "Ambulatory Status",
        "Citizenship",
        "Primary Language",
        "Living Arrangement",
        "Publicity Code",
        "Protection Indicator",
        "Student Indicator",
        "Religion",
        "Mother's Maiden Name",
        "Nationality",
        "Ethnic Group",
        "Contact Person's Name",
        "Contact Person's Telephone Number",
        "Contact Reason",
        "Contact Relationship",
        "Job Title",
        "Job Code/Class",
        "Guarantor Employer's Organization Name",
        "Handicap",
        "Job Status",
        "Guarantor Financial Class",
        "Guarantor Race",
        "Guarantor Birth Place",
        "VIP Indicator"
    ],
    "IAM": [
        "Set ID - IAM",
        "Allergen Type Code",
        "Allergen Code/Mnemonic/Description",
        "Allergy Severity Code",
        "Allergy Reaction Code",
        "Allergy Action Code",
        "Allergy Unique Identifier",
        "Action Reason",
        "Sensitivity to Causative Agent Code",
        "Allergen Group Code/Mnemonic/Description",
        "Onset Date",
        "Onset Date Text",
        "Reported Date/Time",
        "Reported By",
        "Relationship to Patient Code",
        "Alert Device Code",
        "Allergy Clinical Status Code",
        "Statused by Person",
        "Statused by Organization",
        "Statused at Date/Time"
    ],
    "IIM": [
        "Primary Key Value - IIM",
        "Service Item Code",
        "Inventory Lot Number",
        "Inventory Expiration Date",
        "Inventory Manufacturer Name",
        "Inventory Location",
        "Inventory Received Date",
        "Inventory Received Quantity",
        "Inventory Received Quantity Unit",
        "Inventory Received Item Cost",
        "Inventory On Hand Date",
        "Inventory On Hand Quantity",
        "Inventory On Hand Quantity Unit",
        "Procedure Code",
        "Procedure Code Modifier"
    ],
    "IN1": [
        "Set ID - IN1",
        "Insurance Plan ID",
        "Insurance Company ID",
        "Insurance Company Name",
        "Insurance Company Address",
        "Insurance Co Contact Person",
        "Insurance Co Phone Number",
        "Group Number",
        "Group Name",
        "Insured's Group Emp ID",
        "Insured's Group Emp Name",
        "Plan Effective Date",
        "Plan Expiration Date",
        "Authorization Information",
        "Plan Type",
        "Name Of Insured",
        "Insured's Relationship To Patient",
        "Insured's Date Of Birth",
        "Insured's Address",
        "Assignment Of Benefits",
        "Coordination Of Benefits",
        "Coord Of Ben. Priority",
        "Notice Of Admission Flag",
        "Notice Of Admission Date",
        "Report Of Eligibility Flag",
        "Report Of Eligibility Date",
        "Release Information Code",
        "Pre-Admit Cert (PAC)",
        "Verification Date/Time",
        "Verification By",
        "Type Of Agreement Code",
        "Billing Status",
        "Lifetime Reserve Days",
        "Delay Before L.R. Day",
        "Company Plan Code",
        "Policy Number",
        "Policy Deductible",
        "Policy Limit - Amount",
        "Policy Limit - Days",
        "Room Rate - Semi-Private",
        "Room Rate - Private",
        "Insured's Employment Status",
        "Insured's Administrative Sex",
        "Insured's Employer's Address",
        "Verification Status",
        "Prior Insurance Plan ID",
        "Coverage Type",
        "Handicap",
        "Insured's ID Number",
        "Signature Code",
        "Signature Code Date",
        "Insured's Birth Place",
        "VIP Indicator"
    ],
    "IN2": [
        "Insured's Employee ID",
        "Insured's Social Security Number",
        "Insured's Employer's Name and ID",
        "Employer Information Data",
        "Mail Claim Party",
        "Medicare Health Ins Card Number",
        "Medicaid Case Name",
        "Medicaid Case Number",
        "Military Sponsor Name",
        "Military ID Number",
        "Dependent Of Military Recipient",
        "Military Organization",
        "Military Station",
        "Military Service",
        "Military Rank/Grade",
        "Military Status",
        "Military Retire Date",
        "Military Non-Avail Cert On File",
        "Baby Coverage",
        "Combine Baby Bill",
        "Blood Deductible",
        "Special Coverage Approval Name",
        "Special Coverage Approval Title",
        "Non-Covered Insurance Code",
        "Payor ID",
        "Payor Subscriber ID",
        "Eligibility Source",
        "Room Coverage Type/Amount",
        "Policy Type/Amount",
        "Daily Deductible",
        "Living Dependency",
        "Ambulatory Status",
        "Citizenship",
        "Primary Language",
        "Living Arrangement",
        "Publicity Code",
        "Protection Indicator",
        "Student Indicator",
        "Religion",
        "Mother's Maiden Name",
        "Nationality",
        "Ethnic Group",
        "Marital Status",
        "Insured's Employment Start Date",
        "Employment Stop Date",
        "Job Title",
        "Job Code/Class",
        "Job Status",
        "Employer Contact Person Name",
        "Employer Contact Person Phone Number",
        "Employer Contact Reason",
        "Insured's Contact Person's Name",
        "Insured's Contact Person Phone Number",
        "Insured's Contact Person Reason",
        "Relationship to the Patient Start Date",
        "Relationship to the Patient Stop Date",
        "Insurance Co. Contact Reason",
        "Insurance Co Contact Phone Number",
        "Policy Scope",
        "Policy Source",
        "Patient Member Number",
        "Guarantor's Relationship To Insured",
        "Insured's Phone Number - Home",
        "Insured's Employer Phone Number",
        "Military Handicapped Program",
        "Suspend Flag",
        "Copay Limit Flag",
        "Stoploss Limit Flag",
        "Insured Organization Name and ID",
        "Insured Employer Organization Name and ID",
        "Race",
        "CMS Patient's Relationship to Insured"
    ],
    "IN3": [
        "Set ID - IN3",
        "Certification Number",
        "Certified By",
        "Certification Required",
        "Penalty",
        "Certification Date/Time",
        "Certification Modify Date/Time",
        "Operator",
        "Certification Begin Date",
        "Certification End Date",
        "Days",
        "Non-Concur Code/Description",
        "Non-Concur Effective Date/Time",
        "Physician Reviewer",
        "Certification Contact",
        "Certification Contact Phone Number",
        "Appeal Reason",
        "Certification Agency",
        "Certification Agency Phone Number",
        "Pre-Certification Requirement",
        "Case Manager",
        "Second Opinion Date",
        "Second Opinion Status",
        "Second Opinion Documentation Received",
        "Second Opinion Physician"
    ],
    "INV": [
        "Substance Identifier",
        "Substance Status",
        "Substance Type",
        "Inventory Container Identifier",
        "Container Carrier Identifier",
        "Position on Carrier",
        "Initial Quantity",
        "Current Quantity",
        "Available Quantity",
        "Consumption Quantity",
        "Quantity Units",
        "Expiration Date/Time",
        "First Used Date/Time",
        "On Board Stability Duration",
        "Test/Fluid Identifier(s)",
        "Manufacturer Lot Number",
        "Manufacturer Identifier",
        "Supplier Identifier",
        "On Board Stability Time",
        "Target Value"
    ],
    "IPC": [
        "Accession Identifier",
        "Requested Procedure ID",
        "Study Instance UID",
        "Scheduled Procedure Step ID",
        "Modality",
        "Protocol Code",
        "Scheduled Station Name",
        "Scheduled Procedure Step Location",
        "Scheduled AE Title"
    ],
    "ISD": [
        "Reference Interaction Number (unique identifier)",
        "Interaction Type Identifier",
        "Interaction Active State"
    ],
    "LAN": [
        "Set ID - LAN",
        "Language Code",
        "Language Ability Code",
        "Language Proficiency Code"
    ],
    "LCC": [
        "Primary Key Value - LCC",
        "Location Department",
        "Accommodation Type",
        "Charge Code"
    ],
    "LCH": [
        "Primary Key Value - LCH",
        "Segment Action Code",
        "Segment Unique Key",
        "Location Characteristic ID",
        "Location Characteristic Value-LCH"
    ],
    "LDP": [
        "Primary Key Value - LDP",
        "Location Department",
        "Location Service",
        "Specialty Type",
        "Valid Patient Classes",
        "Active/Inactive Flag",
        "Activation Date - LDP",
        "Inactivation Date - LDP",
        "Inactivated Reason",
        "Visiting Hours",
        "Contact Phone",
        "Location Cost Center"
    ],
    "LOC": [
        "Primary Key Value - LOC",
        "Location Description",
        "Location Type - LOC",
        "Organization Name - LOC",
        "Location Address",
        "Location Phone",
        "License Number",
        "Location Equipment",
        "Location Service Code"
    ],
    "LRL": [
        "Primary Key Value - LRL",
        "Segment Action Code",
        "Segment Unique Key",
        "Location Relationship ID",
        "Organizational Location Relationship Value",
        "Patient Location Relationship Value"
    ],
    "MFA": [
        "Record-Level Event Code",
        "MFN Control ID",
        "Event Completion Date/Time",
        "MFN Record Level Error Return",
        "Primary Key Value - MFA",
        "Primary Key Value Type - MFA"
    ],
    "MFE": [
        "Record-Level Event Code",
        "MFN Control ID",
        "Effective Date/Time",
        "Primary Key Value - MFE",
        "Primary Key Value Type"
    ],
    "MFI": [
        "Master File Identifier",
        "Master File Application Identifier",
        "File-Level Event Code",
        "Entered Date/Time",
        "Effective Date/Time",
        "Response Level Code"
    ],
    "MRG": [
        "Prior Patient Identifier List",
        "Prior Alternate Patient ID",
        "Prior Patient Account Number",
        "Prior Patient ID",
        "Prior Visit Number",
        "Prior Alternate Visit ID",
        "Prior Patient Name"
    ],
    "MSA": [
        "Acknowledgment Code",
        "Message Control ID",
        "Text Message",
        "Expected Sequence Number",
        "Delayed Acknowledgment Type",
        "Error Condition"
    ],
    "MSH": [
        "Field Separator",
        "Encoding Characters",
        "Sending Application",
        "Sending Facility",
        "Receiving Application",
        "Receiving Facility",
        "Date/Time Of Message",
        "Security",
        "Message Type",
        "Message Control ID",
        "Processing ID",
        "Version ID",
        "Sequence Number",
        "Continuation Pointer",
        "Accept Acknowledgment Type",
        "Application Acknowledgment Type",
        "Country Code",
        "Character Set",
        "Principal Language Of Message",
        "Alternate Character Set Handling Scheme",
        "Message Profile Identifier"
    ],
    "NCK": [
        "System Date/Time"
    ],
    "NDS": [
        "Notification Reference Number",
        "Notification Date/Time",
        "Notification Alert Severity",
        "Notification Code"
    ],
    "NK1": [
        "Set ID - NK1",
        "NK Name",
        "Relationship",
        "Address",
        "Phone Number",
        "Business Phone Number",
        "Contact Role",
        "Start Date",
        "End Date",
        "Next of Kin / Associated Parties Job Title",
        "Next of Kin / Associated Parties Job Code/Class",
        "Next of Kin / Associated Parties Employee Number",
        "Organization Name - NK1",
        "Marital Status",
        "Administrative Sex",
        "Date/Time of Birth",
        "Living Dependency",
        "Ambulatory Status",
        "Citizenship",
        "Primary Language",
        "Living Arrangement",
        "Publicity Code",
        "Protection Indicator",
        "Student Indicator",
        "Religion",
        "Mother's Maiden Name",
        "Nationality",
        "Ethnic Group",
        "Contact Reason",
        "Contact Person's Name",
        "Contact Person's Telephone Number",
        "Contact Person's Address",
        "Next of Kin/Associated Party's Identifiers",
        "Job Status",
        "Race",
        "Handicap",
        "Contact Person Social Security Number",
        "Next of Kin Birth Place",
        "VIP Indicator"
    ],
    "NPU": [
        "Bed Location",
        "Bed Status"
    ],
    "NSC": [
        "Application Change Type",
        "Current CPU",
        "Current Fileserver",
        "Current Application",
        "Current Facility",
        "New CPU",
        "New Fileserver",
        "New Application",
        "New Facility"
    ],
    "NST": [
        "Statistics Available",
        "Source Identifier",
        "Source Type",
        "Statistics Start",
        "Statistics End",
        "Receive Character Count",
        "Send Character Count",
        "Messages Received",
        "Messages Sent",
        "Checksum Errors Received",
        "Length Errors Received",
        "Other Errors Received",
        "Connect Timeouts",
        "Receive Timeouts",
        "Application control-level Errors"
    ],
    "NTE": [
        "Set ID - NTE",
        "Source of Comment",
        "Comment",
        "Comment Type"
    ],
    "OBR": [
        "Set ID - OBR",
        "Placer Order Number",
        "Filler Order Number",
        "Universal Service Identifier",
        "Priority - OBR",
        "Requested Date/Time",
        "Observation Date/Time",
        "Observation End Date/Time",
        "Collection Volume",
        "Collector Identifier",
        "Specimen Action Code",
        "Danger Code",
        "Relevant Clinical Information",
        "Specimen Received Date/Time",
        "Specimen Source",
        "Ordering Provider",
        "Order Callback Phone Number",
        "Placer Field 1",
        "Placer Field 2",
        "Filler Field 1",
        "Filler Field 2",
        "Results Rpt/Status Chng - Date/Time",
        "Charge to Practice",
        "Diagnostic Serv Sect ID",
        "Result Status",
        "Parent Result",
        "Quantity/Timing",
        "Result Copies To",
        "Parent",
        "Transportation Mode",
        "Reason for Study",
        "Principal Result Interpreter",
        "Assistant Result Interpreter",
        "Technician",
        "Transcriptionist",
        "Scheduled Date/Time",
        "Number of Sample Containers",
        "Transport Logistics of Collected Sample",
        "Collector's Comment",
        "Transport Arrangement Responsibility",
        "Transport Arranged",
        "Escort Required",
        "Planned Patient Transport Comment",
        "Procedure Code",
        "Procedure Code Modifier",
        "Placer Supplemental Service Information",
        "Filler Supplemental Service Information",
        "Medically Necessary Duplicate Procedure Reason.",
        "Result Handling"
    ],
    "OBX": [
        "Set ID - OBX",
        "Value Type",
        "Observation Identifier",
        "Observation Sub-ID",
        "Observation Value",
        "Units",
        "References Range",
        "Abnormal Flags",
        "Probability",
        "Nature of Abnormal Test",
        "Observation Result Status",
        "Effective Date of Reference Range",
        "User Defined Access Checks",
        "Date/Time of the Observation",
        "Producer's ID",
        "Responsible Observer",
        "Observation Method",
        "Equipment Instance Identifier",
        "Date/Time of the Analysis"
    ],
    "ODS": [
        "Type",
        "Service Period",
        "Diet, Supplement, or Preference Code",
        "Text Instruction"
    ],
    "ODT": [
        "Tray Type",
        "Service Period",
        "Text Instruction"
    ],
    "OM1": [
        "Sequence Number - Test/Observation Master File",
        "Producer's Service/Test/Observation ID",
        "Permitted Data Types",
        "Specimen Required",
        "Producer ID",
        "Observation Description",
        "Other Service/Test/Observation IDs for the Observation",
        "Other Names",
        "Preferred Report Name for the Observation",
        "Preferred Short Name or Mnemonic for Observation",
        "Preferred Long Name for the Observation",
        "Orderability",
        "Identity of Instrument Used to Perform this Study",
        "Coded Representation of Method",
        "Portable Device Indicator",
        "Observation Producing Department/Section",
        "Telephone Number of Section",
        "Nature of Service/Test/Observation",
        "Report Subheader",
        "Report Display Order",
        "Date/Time Stamp for any change in Definition for the Observation",
        "Effective Date/Time of Change",
        "Typical Turn-Around Time",
        "Processing Time",
        "Processing Priority",
        "Reporting Priority",
        "Outside Site(s) Where Observation may be Performed ",
        "Address of Outside Site(s)",
        "Phone Number of Outside Site",
        "Confidentiality Code",
        "Observations Required to Interpret the Observation",
        "Interpretation of Observations",
        "Contraindications to Observations",
        "Reflex Tests/Observations",
        "Rules that Trigger Reflex Testing",
        "Fixed Canned Message",
        "Patient Preparation",
        "Procedure Medication",
        "Factors that may Affect the Observation",
        "Service/Test/Observation Performance Schedule",
        "Description of Test Methods",
        "Kind of Quantity Observed",
        "Point Versus Interval",
        "Challenge Information",
        "Relationship Modifier",
        "Target Anatomic Site Of Test",
        "Modality Of Imaging Measurement"
    ],
    "OM2": [
        "Sequence Number - Test/Observation Master File",
        "Units of Measure",
        "Range of Decimal Precision",
        "Corresponding SI Units of Measure",
        "SI Conversion Factor",
        "Reference (Normal) Range - Ordinal and Continuous Observations",
        "Critical Range for Ordinal and Continuous Observations",
        "Absolute Range for Ordinal and Continuous Observations",
        "Delta Check Criteria",
        "Minimum Meaningful Increments"
    ],
    "OM3": [
        "Sequence Number - Test/Observation Master File",
        "Preferred Coding System",
        "Valid Coded 'Answers'",
        "Normal Text/Codes for Categorical Observations",
        "Abnormal Text/Codes for Categorical Observations",
        "Critical Text/Codes for Categorical Observations",
        "Value Type"
    ],
    "OM4": [
        "Sequence Number - Test/Observation Master File",
        "Derived Specimen",
        "Container Description",
        "Container Volume",
        "Container Units",
        "Specimen",
        "Additive",
        "Preparation",
        "Special Handling Requirements",
        "Normal Collection Volume",
        "Minimum Collection Volume",
        "Specimen Requirements",
        "Specimen Priorities",
        "Specimen Retention Time"
    ],
    "OM5": [
        "Sequence Number - Test/Observation Master File",
        "Test/Observations Included within an Ordered Test Battery",
        "Observation ID Suffixes"
    ],
    "OM6": [
        "Sequence Number - Test/Observation Master File",
        "Derivation Rule"
    ],
    "OM7": [
        "Sequence Number - Test/Observation Master File",
        "Universal Service Identifier",
        "Category Identifier",
        "Category Description",
        "Category Synonym",
        "Effective Test/Service Start Date/Time",
        "Effective Test/Service End Date/Time",
        "Test/Service Default Duration Quantity",
        "Test/Service Default Duration Units",
        "Test/Service Default Frequency",
        "Consent Indicator",
        "Consent Identifier",
        "Consent Effective Start Date/Time",
        "Consent Effective End Date/Time",
        "Consent Interval Quantity",
        "Consent Interval Units",
        "Consent Waiting Period Quantity",
        "Consent Waiting Period Units",
        "Effective Date/Time of Change",
        "Entered By",
        "Orderable-at Location",
        "Formulary Status",
        "Special Order Indicator",
        "Primary Key Value - CDM"
    ],
    "ORC": [
        "Order Control",
        "Placer Order Number",
        "Filler Order Number",
        "Placer Group Number",
        "Order Status",
        "Response Flag",
        "Quantity/Timing",
        "Parent Order",
        "Date/Time of Transaction",
        "Entered By",
        "Verified By",
        "Ordering Provider",
        "Enterer's Location",
        "Call Back Phone Number",
        "Order Effective Date/Time",
        "Order Control Code Reason",
        "Entering Organization",
        "Entering Device",
        "Action By",
        "Advanced Beneficiary Notice Code",
        "Ordering Facility Name",
        "Ordering Facility Address",
        "Ordering Facility Phone Number",
        "Ordering Provider Address",
        "Order Status Modifier",
        "Advanced Beneficiary Notice Override Reason",
        "Filler's Expected Availability Date/Time",
        "Confidentiality Code",
        "Order Type",
        "Enterer Authorization Mode"
    ],
    "ORG": [
        "Set ID - ORG",
        "Organization Unit Code",
        "Organization Unit Type Code",
        "Primary Org Unit Indicator",
        "Practitioner Org Unit Identifier",
        "Health Care Provider Type Code",
        "Health Care Provider Classification Code",
        "Health Care Provider Area of Specialization Code",
        "Effective Date Range",
        "Employment Status Code",
        "Board Approval Indicator",
        "Primary Care Physician Indicator"
    ],
    "OVR": [
        "Business Rule Override Type",
        "Business Rule Override Code",
        "Override Comments",
        "Override Entered By",
        "Override Authorized By"
    ],
    "PCR": [
        "Implicated Product",
        "Generic Product",
        "Product Class",
        "Total Duration Of Therapy",
        "Product Manufacture Date",
        "Product Expiration Date",
        "Product Implantation Date",
        "Product Explantation Date",
        "Single Use Device",
        "Indication For Product Use",
        "Product Problem",
        "Product Serial/Lot Number",
        "Product Available For Inspection",
        "Product Evaluation Performed",
        "Product Evaluation Status",
        "Product Evaluation Results",
        "Evaluated Product Source",
        "Date Product Returned To Manufacturer",
        "Device Operator Qualifications",
        "Relatedness Assessment",
        "Action Taken In Response To The Event",
        "Event Causality Observations",
        "Indirect Exposure Mechanism"
    ],
    "PD1": [
        "Living Dependency",
        "Living Arrangement",
        "Patient Primary Facility",
        "Patient Primary Care Provider Name and ID No.",
        "Student Indicator",
        "Handicap",
        "Living Will Code",
        "Organ Donor Code",
        "Separate Bill",
        "Duplicate Patient",
        "Publicity Code",
        "Protection Indicator",
        "Protection Indicator Effective Date",
        "Place of Worship",
        "Advance Directive Code",
        "Immunization Registry Status",
        "Immunization Registry Status Effective Date",
        "Publicity Code Effective Date",
        "Military Branch",
        "Military Rank/Grade",
        "Military Status"
    ],
    "PDA": [
        "Death Cause Code",
        "Death Location",
        "Death Certified Indicator",
        "Death Certificate Signed Date/Time",
        "Death Certified By",
        "Autopsy Indicator",
        "Autopsy Start and End Date/Time",
        "Autopsy Performed By",
        "Coroner Indicator"
    ],
    "PDC": [
        "Manufacturer/Distributor",
        "Country",
        "Brand Name",
        "Device Family Name",
        "Generic Name",
        "Model Identifier",
        "Catalogue Identifier",
        "Other Identifier",
        "Product Code",
        "Marketing Basis",
        "Marketing Approval ID",
        "Labeled Shelf Life",
        "Expected Shelf Life",
        "Date First Marketed",
        "Date Last Marketed"
    ],
    "PEO": [
        "Event Identifiers Used",
        "Event Symptom/Diagnosis Code",
        "Event Onset Date/Time",
        "Event Exacerbation Date/Time",
        "Event Improved Date/Time",
        "Event Ended Data/Time",
        "Event Location Occurred Address",
        "Event Qualification",
        "Event Serious",
        "Event Expected",
        "Event Outcome",
        "Patient Outcome",
        "Event Description From Others",
        "Event From Original Reporter",
        "Event Description From Patient",
        "Event Description From Practitioner",
        "Event Description From Autopsy",
        "Cause Of Death",
        "Primary Observer Name",
        "Primary Observer Address",
        "Primary Observer Telephone",
        "Primary Observer's Qualification",
        "Confirmation Provided By",
        "Primary Observer Aware Date/Time",
        "Primary Observer's identity May Be Divulged"
    ],
    "PES": [
        "Sender Organization Name",
        "Sender Individual Name",
        "Sender Address",
        "Sender Telephone",
        "Sender Event Identifier",
        "Sender Sequence Number",
        "Sender Event Description",
        "Sender Comment",
        "Sender Aware Date/Time",
        "Event Report Date",
        "Event Report Timing/Type",
        "Event Report Source",
        "Event Reported To"
    ],
    "PID": [
        "Set ID - PID",
        "Patient ID",
        "Patient Identifier List",
        "Alternate Patient ID - PID",
        "Patient Name",
        "Mother's Maiden Name",
        "Date/Time of Birth",
        "Administrative Sex",
        "Patient Alias",
        "Race",
        "Patient Address",
        "County Code",
        "Phone Number - Home",
        "Phone Number - Business",
        "Primary Language",
        "Marital Status",
        "Religion",
        "Patient Account Number",
        "SSN Number - Patient",
        "Driver's License Number - Patient",
        "Mother's Identifier",
        "Ethnic Group",
        "Birth Place",
        "Multiple Birth Indicator",
        "Birth Order",
        "Citizenship",
        "Veterans Military Status",
        "Nationality",
        "Patient Death Date and Time",
        "Patient Death Indicator",
        "Identity Unknown Indicator",
        "Identity Reliability Code",
        "Last Update Date/Time",
        "Last Update Facility",
        "Species Code",
        "Breed Code",
        "Strain",
        "Production Class Code",
        "Tribal Citizenship"
    ],
    "PR1": [
        "Set ID - PR1",
        "Procedure Coding Method",
        "Procedure Code",
        "Procedure Description",
        "Procedure Date/Time",
        "Procedure Functional Type",
        "Procedure Minutes",
        "Anesthesiologist",
        "Anesthesia Code",
        "Anesthesia Minutes",
        "Surgeon",
        "Procedure Practitioner",
        "Consent Code",
        "Procedure Priority",
        "Associated Diagnosis Code",
        "Procedure Code Modifier",
        "Procedure DRG Type",
        "Tissue Type Code",
        "Procedure Identifier",
        "Procedure Action Code"
    ],
    "PRA": [
        "Primary Key Value - PRA",
        "Practitioner Group",
        "Practitioner Category",
        "Provider Billing",
        "Specialty",
        "Practitioner ID Numbers",
        "Privileges",
        "Date Entered Practice",
        "Institution",
        "Date Left Practice",
        "Government Reimbursement Billing Eligibility",
        "Set ID - PRA"
    ],
    "PRB": [
        "Action Code",
        "Action Date/Time",
        "Problem ID",
        "Problem Instance ID",
        "Episode of Care ID",
        "Problem List Priority",
        "Problem Established Date/Time",
        "Anticipated Problem Resolution Date/Time",
        "Actual Problem Resolution Date/Time",
        "Problem Classification",
        "Problem Management Discipline",
        "Problem Persistence",
        "Problem Confirmation Status",
        "Problem Life Cycle Status",
        "Problem Life Cycle Status Date/Time",
        "Problem Date of Onset",
        "Problem Onset Text",
        "Problem Ranking",
        "Certainty of Problem (0-1)",
        "Probability of Problem",
        "Individual Awareness of Problem",
        "Problem Prognosis",
        "Individual Awareness of Prognosis",
        "Family/Significant Other Awareness of Problem/Prognosis",
        "Security/Sensitivity"
    ],
    "PRC": [
        "Primary Key Value - PRC",
        "Facility ID - PRC",
        "Department",
        "Valid Patient Classes",
        "Price",
        "Formula",
        "Minimum Quantity",
        "Maximum Quantity",
        "Minimum Price",
        "Maximum Price",
        "Effective Start Date",
        "Effective End Date",
        "Price Override Flag",
        "Billing Category",
        "Chargeable Flag",
        "Active/Inactive Flag",
        "Cost",
        "Charge On Indicator"
    ],
    "PRD": [
        "Provider Role",
        "Provider Name",
        "Provider Address",
        "Provider Location",
        "Provider Communication Information",
        "Preferred Method of Contact",
        "Provider Identifiers",
        "Effective Start Date of Provider Role",
        "Effective End Date of Provider Role"
    ],
    "PSH": [
        "Report Type",
        "Report Form Identifier",
        "Report Date",
        "Report Interval Start Date",
        "Report Interval End Date",
        "Quantity Manufactured",
        "Quantity Distributed",
        "Quantity Distributed Method",
        "Quantity Distributed Comment",
        "Quantity in Use",
        "Quantity in Use Method",
        "Quantity in Use Comment",
        "Number of Product Experience Reports Filed by Facility",
        "Number of Product Experience Reports Filed by Distributor"
    ],
    "PTH": [
        "Action Code",
        "Pathway ID",
        "Pathway Instance ID",
        "Pathway Established Date/Time",
        "Pathway Life Cycle Status",
        "Change Pathway Life Cycle Status Date/Time"
    ],
    "PV1": [
        "Set ID - PV1",
        "Patient Class",
        "Assigned Patient Location",
        "Admission Type",
        "Preadmit Number",
        "Prior Patient Location",
        "Attending Doctor",
        "Referring Doctor",
        "Consulting Doctor",
        "Hospital Service",
        "Temporary Location",
        "Preadmit Test Indicator",
        "Re-admission Indicator",
        "Admit Source",
        "Ambulatory Status",
        "VIP Indicator",
        "Admitting Doctor",
        "Patient Type",
        "Visit Number",
        "Financial Class",
        "Charge Price Indicator",
        "Courtesy Code",
        "Credit Rating",
        "Contract Code",
        "Contract Effective Date",
        "Contract Amount",
        "Contract Period",
        "Interest Code",
        "Transfer to Bad Debt Code",
        "Transfer to Bad Debt Date",
        "Bad Debt Agency Code",
        "Bad Debt Transfer Amount",
        "Bad Debt Recovery Amount",
        "Delete Account Indicator",
        "Delete Account Date",
        "Discharge Disposition",
        "Discharged to Location",
        "Diet Type",
        "Servicing Facility",
        "Bed Status",
        "Account Status",
        "Pending Location",
        "Prior Temporary Location",
        "Admit Date/Time",
        "Discharge Date/Time",
        "Current Patient Balance",
        "Total Charges",
        "Total Adjustments",
        "Total Payments",
        "Alternate Visit ID",
        "Visit Indicator",
        "Other Healthcare Provider"
    ],
    "PV2": [
        "Prior Pending Location",
        "Accommodation Code",
        "Admit Reason",
        "Transfer Reason",
        "Patient Valuables",
        "Patient Valuables Location",
        "Visit User Code",
        "Expected Admit Date/Time",
        "Expected Discharge Date/Time",
        "Estimated Length of Inpatient Stay",
        "Actual Length of Inpatient Stay",
        "Visit Description",
        "Referral Source Code",
        "Previous Service Date",
        "Employment Illness Related Indicator",
        "Purge Status Code",
        "Purge Status Date",
        "Special Program Code",
        "Retention Indicator",
        "Expected Number of Insurance Plans",
        "Visit Publicity Code",
        "Visit Protection Indicator",
        "Clinic Organization Name",
        "Patient Status Code",
        "Visit Priority Code",
        "Previous Treatment Date",
        "Expected Discharge Disposition",
        "Signature on File Date",
        "First Similar Illness Date",
        "Patient Charge Adjustment Code",
        "Recurring Service Code",
        "Billing Media Code",
        "Expected Surgery Date and Time",
        "Military Partnership Code",
        "Military Non-Availability Code",
        "Newborn Baby Indicator",
        "Baby Detained Indicator",
        "Mode of Arrival Code",
        "Recreational Drug Use Code",
        "Admission Level of Care Code",
        "Precaution Code",
        "Patient Condition Code",
        "Living Will Code",
        "Organ Donor Code",
        "Advance Directive Code",
        "Patient Status Effective Date",
        "Expected LOA Return Date/Time",
        "Expected Pre-admission Testing Date/Time",
        "Notify Clergy Code"
    ],
    "QAK": [
        "Query Tag",
        "Query Response Status",
        "Message Query Name",
        "Hit Count",
        "This payload",
        "Hits remaining"
    ],
    "QID": [
        "Query Tag",
        "Message Query Name"
    ],
    "QPD": [
        "Message Query Name",
        "Query Tag",
        "User Parameters (in successive fields)"
    ],
    "QRD": [
        "Query Date/Time",
        "Query Format Code",
        "Query Priority",
        "Query ID",
        "Deferred Response Type",
        "Deferred Response Date/Time",
        "Quantity Limited Request",
        "Who Subject Filter",
        "What Subject Filter",
        "What Department Data Code",
        "What Data Code Value Qual.",
        "Query Results Level"
    ],
    "QRF": [
        "Where Subject Filter",
        "When Data Start Date/Time",
        "When Data End Date/Time",
        "What User Qualifier",
        "Other QRY Subject Filter",
        "Which Date/Time Qualifier",
        "Which Date/Time Status Qualifier",
        "Date/Time Selection Qualifier",
        "When Quantity/Timing Qualifier",
        "Search Confidence Threshold"
    ],
    "QRI": [
        "Candidate Confidence",
        "Match Reason Code",
        "Algorithm Descriptor"
    ],
    "RCP": [
        "Query Priority",
        "Quantity Limited Request",
        "Response Modality",
        "Execution and Delivery Time",
        "Modify Indicator",
        "Sort-by Field",
        "Segment group inclusion"
    ],
    "RDF": [
        "Number of Columns per Row",
        "Column Description"
    ],
    "RDT": [
        "Column Value"
    ],
    "RF1": [
        "Referral Status",
        "Referral Priority",
        "Referral Type",
        "Referral Disposition",
        "Referral Category",
        "Originating Referral Identifier",
        "Effective Date",
        "Expiration Date",
        "Process Date",
        "Referral Reason",
        "External Referral Identifier"
    ],
    "RGS": [
        "Set ID - RGS",
        "Segment Action Code",
        "Resource Group ID"
    ],
    "RMI": [
        "Risk Management Incident Code",
        "Date/Time Incident",
        "Incident Type Code"
    ],
    "ROL": [
        "Role Instance ID",
        "Action Code",
        "Role-ROL",
        "Role Person",
        "Role Begin Date/Time",
        "Role End Date/Time",
        "Role Duration",
        "Role Action Reason",
        "Provider Type",
        "Organization Unit Type",
        "Office/Home Address/Birthplace",
        "Phone"
    ],
    "RQ1": [
        "Anticipated Price",
        "Manufacturer Identifier",
        "Manufacturer's Catalog",
        "Vendor ID",
        "Vendor Catalog",
        "Taxable",
        "Substitute Allowed"
    ],
    "RQD": [
        "Requisition Line Number",
        "Item Code - Internal",
        "Item Code - External",
        "Hospital Item Code",
        "Requisition Quantity",
        "Requisition Unit of Measure",
        "Dept. Cost Center",
        "Item Natural Account Code",
        "Deliver To ID",
        "Date Needed"
    ],
    "RXA": [
        "Give Sub-ID Counter",
        "Administration Sub-ID Counter",
        "Date/Time Start of Administration",
        "Date/Time End of Administration",
        "Administered Code",
        "Administered Amount",
        "Administered Units",
        "Administered Dosage Form",
        "Administration Notes",
        "Administering Provider",
        "Administered-at Location",
        "Administered Per (Time Unit)",
        "Administered Strength",
        "Administered Strength Units",
        "Substance Lot Number",
        "Substance Expiration Date",
        "Substance Manufacturer Name",
        "Substance/Treatment Refusal Reason",
        "Indication",
        "Completion Status",
        "Action Code - RXA",
        "System Entry Date/Time",
        "Administered Drug Strength Volume",
        "Administered Drug Strength Volume Units",
        "Administered Barcode Identifier",
        "Pharmacy Order Type"
    ],
    "RXC": [
        "RX Component Type",
        "Component Code",
        "Component Amount",
        "Component Units",
        "Component Strength",
        "Component Strength Units",
        "Supplementary Code",
        "Component Drug Strength Volume",
        "Component Drug Strength Volume Units"
    ],
    "RXD": [
        "Dispense Sub-ID Counter",
        "Dispense/Give Code",
        "Date/Time Dispensed",
        "Actual Dispense Amount",
        "Actual Dispense Units",
        "Actual Dosage Form",
        "Prescription Number",
        "Number of Refills Remaining",
        "Dispense Notes",
        "Dispensing Provider",
        "Substitution Status",
        "Total Daily Dose",
        "Dispense-to Location",
        "Needs Human Review",
        "Pharmacy/Treatment Supplier's Special Dispensing Instructions",
        "Actual Strength",
        "Actual Strength Unit",
        "Substance Lot Number",
        "Substance Expiration Date",
        "Substance Manufacturer Name",
        "Indication",
        "Dispense Package Size",
        "Dispense Package Size Unit",
        "Dispense Package Method",
        "Supplementary Code",
        "Initiating Location",
        "Packaging/Assembly Location",
        "Actual Drug Strength Volume",
        "Actual Drug Strength Volume Units",
        "Dispense to Pharmacy",
        "Dispense to Pharmacy Address",
        "Pharmacy Order Type",
        "Dispense Type"
    ],
    "RXE": [
        "Quantity/Timing",
        "Give Code",
        "Give Amount - Minimum",
        "Give Amount - Maximum",
        "Give Units",
        "Give Dosage Form",
        "Provider's Administration Instructions",
        "Deliver-To Location",
        "Substitution Status",
        "Dispense Amount",
        "Dispense Units",
        "Number Of Refills",
        "Ordering Provider's DEA Number",
        "Pharmacist/Treatment Supplier's Verifier ID",
        "Prescription Number",
        "Number of Refills Remaining",
        "Number of Refills/Doses Dispensed",
        "D/T of Most Recent Refill or Dose Dispensed",
        "Total Daily Dose",
        "Needs Human Review",
        "Pharmacy/Treatment Supplier's Special Dispensing Instructions",
        "Give Per (Time Units)",
        "Give Rate Amount",
        "Give Rate Units",
        "Give Strength",
        "Give Strength Units",
        "Give Indication",
        "Dispense Package Size",
        "Dispense Package Size Unit",
        "Dispense Package Method",
        "Supplementary Code",
        "Original Order Date/Time",
        "Give Drug Strength Volume",
        "Give Drug Strength Volume Units",
        "Controlled Substance Schedule",
        "Formulary Status",
        "Pharmaceutical Substance Alternative",
        "Pharmacy of Most Recent Fill",
        "Initial Dispense Amount",
        "Dispensing Pharmacy",
        "Dispensing Pharmacy Address",
        "Deliver-to Patient Location",
        "Deliver-to Address",
        "Pharmacy Order Type"
    ],
    "RXG": [
        "Give Sub-ID Counter",
        "Dispense Sub-ID Counter",
        "Quantity/Timing",
        "Give Code",
        "Give Amount - Minimum",
        "Give Amount - Maximum",
        "Give Units",
        "Give Dosage Form",
        "Administration Notes",
        "Substitution Status",
        "Dispense-to Location",
        "Needs Human Review",
        "Pharmacy/Treatment Supplier's Special Administration Instructions",
        "Give Per (Time Unit)",
        "Give Rate Amount",
        "Give Rate Units",
        "Give Strength",
        "Give Strength Units",
        "Substance Lot Number",
        "Substance Expiration Date",
        "Substance Manufacturer Name",
        "Indication",
        "Give Drug Strength Volume",
        "Give Drug Strength Volume Units",
        "Give Barcode Identifier",
        "Pharmacy Order Type"
    ],
    "RXO": [
        "Requested Give Code",
        "Requested Give Amount - Minimum",
        "Requested Give Amount - Maximum",
        "Requested Give Units",
        "Requested Dosage Form",
        "Provider's Pharmacy/Treatment Instructions",
        "Provider's Administration Instructions",
        "Deliver-To Location",
        "Allow Substitutions",
        "Requested Dispense Code",
        "Requested Dispense Amount",
        "Requested Dispense Units",
        "Number Of Refills",
        "Ordering Provider's DEA Number",
        "Pharmacist/Treatment Supplier's Verifier ID",
        "Needs Human Review",
        "Requested Give Per (Time Unit)",
        "Requested Give Strength",
        "Requested Give Strength Units",
        "Indication",
        "Requested Give Rate Amount",
        "Requested Give Rate Units",
        "Total Daily Dose",
        "Supplementary Code",
        "Requested Drug Strength Volume",
        "Requested Drug Strength Volume Units",
        "Pharmacy Order Type",
        "Dispensing Interval"
    ],
    "RXR": [
        "Route",
        "Administration Site",
        "Administration Device",
        "Administration Method",
        "Routing Instruction",
        "Administration Site Modifier"
    ],
    "SAC": [
        "External Accession Identifier",
        "Accession Identifier",
        "Container Identifier",
        "Primary (parent) Container Identifier ",
        "Equipment Container Identifier",
        "Specimen Source",
        "Registration Date/Time",
        "Container Status",
        "Carrier Type",
        "Carrier Identifier",
        "Position in Carrier",
        "Tray Type - SAC",
        "Tray Identifier",
        "Position in Tray",
        "Location",
        "Container Height",
        "Container Diameter",
        "Barrier Delta",
        "Bottom Delta",
        "Container Height/Diameter/Delta Units",
        "Container Volume",
        "Available Specimen Volume",
        "Initial Specimen Volume",
        "Volume Units",
        "Separator Type",
        "Cap Type",
        "Additive",
        "Specimen Component",
        "Dilution Factor",
        "Treatment",
        "Temperature",
        "Hemolysis Index",
        "Hemolysis Index Units",
        "Lipemia Index",
        "Lipemia Index Units",
        "Icterus Index",
        "Icterus Index Units",
        "Fibrin Index",
        "Fibrin Index Units",
        "System Induced Contaminants",
        "Drug Interference",
        "Artificial Blood",
        "Special Handling Code",
        "Other Environmental Factors"
    ],
    "SCH": [
        "Placer Appointment ID",
        "Filler Appointment ID",
        "Occurrence Number",
        "Placer Group Number",
        "Schedule ID",
        "Event Reason",
        "Appointment Reason",
        "Appointment Type",
        "Appointment Duration",
        "Appointment Duration Units",
        "Appointment Timing Quantity",
        "Placer Contact Person",
        "Placer Contact Phone Number",
        "Placer Contact Address",
        "Placer Contact Location",
        "Filler Contact Person",
        "Filler Contact Phone Number",
        "Filler Contact Address",
        "Filler Contact Location",
        "Entered By Person",
        "Entered By Phone Number",
        "Entered By Location",
        "Parent Placer Appointment ID",
        "Parent Filler Appointment ID",
        "Filler Status Code",
        "Placer Order Number",
        "Filler Order Number"
    ],
    "SFT": [
        "Software Vendor Organization",
        "Software Certified Version or Release Number",
        "Software Product Name",
        "Software Binary ID",
        "Software Product Information",
        "Software Install Date"
    ],
    "SID": [
        "Application / Method Identifier",
        "Substance Lot Number",
        "Substance Container Identifier",
        "Substance Manufacturer Identifier"
    ],
    "SPM": [
        "Set ID - SPM",
        "Specimen ID",
        "Specimen Parent IDs",
        "Specimen Type",
        "Specimen Type Modifier",
        "Specimen Additives",
        "Specimen Collection Method",
        "Specimen Source Site",
        "Specimen Source Site Modifier",
        "Specimen Collection Site",
        "Specimen Role",
        "Specimen Collection Amount",
        "Grouped Specimen Count",
        "Specimen Description",
        "Specimen Handling Code",
        "Specimen Risk Code",
        "Specimen Collection Date/Time",
        "Specimen Received Date/Time",
        "Specimen Expiration Date/Time",
        "Specimen Availability",
        "Specimen Reject Reason",
        "Specimen Quality",
        "Specimen Appropriateness",
        "Specimen Condition",
        "Specimen Current Quantity",
        "Number of Specimen Containers",
        "Container Type",
        "Container Condition",
        "Specimen Child Role"
    ],
    "SPR": [
        "Query Tag",
        "Query/Response Format Code",
        "Stored Procedure Name",
        "Input Parameter List"
    ],
    "STF": [
        "Primary Key Value - STF",
        "Staff Identifier List",
        "Staff Name",
        "Staff Type",
        "Administrative Sex",
        "Date/Time of Birth",
        "Active/Inactive Flag",
        "Department",
        "Hospital Service - STF",
        "Phone",
        "Office/Home Address/Birthplace",
        "Institution Activation Date",
        "Institution Inactivation Date",
        "Backup Person ID",
        "E-Mail Address",
        "Preferred Method of Contact",
        "Marital Status",
        "Job Title",
        "Job Code/Class",
        "Employment Status Code",
        "Additional Insured on Auto",
        "Driver's License Number - Staff",
        "Copy Auto Ins",
        "Auto Ins. Expires",
        "Date Last DMV Review",
        "Date Next DMV Review",
        "Race",
        "Ethnic Group",
        "Re-activation Approval Indicator",
        "Citizenship",
        "Death Date and Time",
        "Death Indicator",
        "Institution Relationship Type Code",
        "Institution Relationship Period",
        "Expected Return Date",
        "Cost Center Code",
        "Generic Classification Indicator",
        "Inactive Reason Code"
    ],
    "TCC": [
        "Universal Service Identifier",
        "Test Application Identifier",
        "Specimen Source",
        "Auto-Dilution Factor Default",
        "Rerun Dilution Factor Default",
        "Pre-Dilution Factor Default",
        "Endogenous Content of Pre-Dilution Diluent",
        "Inventory Limits Warning Level",
        "Automatic Rerun Allowed",
        "Automatic Repeat Allowed",
        "Automatic Reflex Allowed",
        "Equipment Dynamic Range",
        "Units",
        "Processing Type"
    ],
    "TCD": [
        "Universal Service Identifier",
        "Auto-Dilution Factor",
        "Rerun Dilution Factor",
        "Pre-Dilution Factor",
        "Endogenous Content of Pre-Dilution Diluent",
        "Automatic Repeat Allowed",
        "Reflex Allowed",
        "Analyte Repeat Status"
    ],
    "TQ1": [
        "Set ID - TQ1",
        "Quantity",
        "Repeat Pattern",
        "Explicit Time",
        "Relative Time and Units",
        "Service Duration",
        "Start date/time",
        "End date/time",
        "Priority",
        "Condition text",
        "Text instruction",
        "Conjunction",
        "Occurrence duration",
        "Total occurrences"
    ],
    "TQ2": [
        "Set ID - TQ2",
        "Sequence/Results Flag",
        "Related Placer Number",
        "Related Filler Number",
        "Related Placer Group Number",
        "Sequence Condition Code",
        "Cyclic Entry/Exit Indicator",
        "Sequence Condition Time Interval",
        "Cyclic Group Maximum Number of Repeats",
        "Special Service Request Relationship"
    ],
    "TXA": [
        "Set ID - TXA",
        "Document Type",
        "Document Content Presentation",
        "Activity Date/Time",
        "Primary Activity Provider Code/Name",
        "Origination Date/Time",
        "Transcription Date/Time",
        "Edit Date/Time",
        "Originator Code/Name",
        "Assigned Document Authenticator",
        "Transcriptionist Code/Name",
        "Unique Document Number",
        "Parent Document Number",
        "Placer Order Number",
        "Filler Order Number",
        "Unique Document File Name",
        "Document Completion Status",
        "Document Confidentiality Status",
        "Document Availability Status",
        "Document Storage Status",
        "Document Change Reason",
        "Authentication Person, Time Stamp",
        "Distributed Copies (Code and Name of Recipients) "
    ],
    "UB1": [
        "Set ID - UB1",
        "Blood Deductible (43)",
        "Blood Furnished-Pints Of (40)",
        "Blood Replaced-Pints (41)",
        "Blood Not Replaced-Pints (42)",
        "Co-Insurance Days (25)",
        "Condition Code (35-39)",
        "Covered Days (23)",
        "Non Covered Days (24)",
        "Value Amount and Code (46-49)",
        "Number Of Grace Days (90)",
        "Special Program Indicator (44)",
        "PSRO/UR Approval Indicator (87)",
        "PSRO/UR Approved Stay-Fm (88)",
        "PSRO/UR Approved Stay-To (89)",
        "Occurrence (28-32)",
        "Occurrence Span (33)",
        "Occur Span Start Date (33)",
        "Occur Span End Date (33)",
        "UB-82 Locator 2",
        "UB-82 Locator 9",
        "UB-82 Locator 27",
        "UB-82 Locator 45"
    ],
    "UB2": [
        "Set ID - UB2",
        "Co-Insurance Days (9)",
        "Condition Code (24-30)",
        "Covered Days (7)",
        "Non-Covered Days (8)",
        "Value Amount and Code",
        "Occurrence Code and Date (32-35)",
        "Occurrence Span Code/Dates (36)",
        "UB92 Locator 2 (State)",
        "UB92 Locator 11 (State)",
        "UB92 Locator 31 (National)",
        "Document Control Number",
        "UB92 Locator 49 (National)",
        "UB92 Locator 56 (State)",
        "UB92 Locator 57 (National)",
        "UB92 Locator 78 (State)",
        "Special Visit Count"
    ],
    "URD": [
        "R/U Date/Time",
        "Report Priority",
        "R/U Who Subject Definition",
        "R/U What Subject Definition",
        "R/U What Department Code",
        "R/U Display/Print Locations",
        "R/U Results Level"
    ],
    "URS": [
        "R/U Where Subject Definition",
        "R/U When Data Start Date/Time",
        "R/U When Data End Date/Time",
        "R/U What User Qualifier",
        "R/U Other Results Subject Definition",
        "R/U Which Date/Time Qualifier",
        "R/U Which Date/Time Status Qualifier",
        "R/U Date/Time Selection Qualifier",
        "R/U Quantity/Timing Qualifier"
    ],
    "VAR": [
        "Variance Instance ID",
        "Documented Date/Time",
        "Stated Variance Date/Time",
        "Variance Originator",
        "Variance Classification",
        "Variance Description"
    ],
    "VTQ": [
        "Query Tag",
        "Query/Response Format Code",
        "VT Query Name",
        "Virtual Table Name",
        "Selection Criteria"
    ]
}

observation_id = {
            "HEMATOLOGY": {
            'WBC': 'WHITE BLOOD CELL',
            'RBC': 'RED BLOOD CELL',
            'PLT': 'PLATELET',
            'HGB': 'HEMOGLOBIN CONCENTRATION',
            'LYM': 'LYMPHOCYTES',
            'MON': 'MONOCYTES',
            'NEU': 'NEUTROPHILS',
            'EO': 'EOSINOPHILS',
            'BAS': 'BASOPHIL',
            'HCT': 'HEMATOCRIT',
            'MCV': 'MEAN CORPUSUCULAR VOLUME',
            'MCH': 'MEAN CORPUSUCULAR HEMOGLOBIN',
            'MCHC': 'MEAN CORPUSUCULAR HEMOGLOBIN CONCENTRATION',
            'MPV': 'MEAN PLATELET VOLUME',
            'PDW': 'PLATELET DISTRIBUTION WIDTH',
            'MID': 'MID-SIZED',
            'GRAN': 'GRANULOCYTE',
            'PLCC': 'PLATELET LARGE CELL COUNT',
            'PLCR': 'PLATELET LARGE CELL RATIO',
            'PCT': 'PLATELETCRIT',
            'ALY': 'ATYPICAL LYMPHOCYTES',
            'LIC': 'LARGE IMMATURE CELLS',
            'LYM': 'LYMPHOCYTES',
            'LY': 'LYMPHOCYTES',
            'MO': 'MONOCYTES',
            'RDW': 'RED BLOOD CELL DISTRIBUTION WIDTH',
            'LCC': 'PLATELET LARGE CELL DISTRIBUTION',
            'LCR': 'PLATELET LARGE CELL RATIO',
            'GR': 'GRANULOCYTE'
        },
}

suffixes = {
            '%': 'PERCENTAGE',
            '#': 'NUMBER',
            'CV|cv': 'COEFFICIENT OF VARIATION',
            'SD|sv': 'STANDARD DEVIATION',
            '[a-zA-Z]*(Histogram)[a-zA-Z]*': 'HISTOGRAM',
    }
