[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'

[tool.poetry]
name = 'vsgan'
version = '1.6.4'
description = 'VapourSynth Single Image Super-Resolution Generative Adversarial Network (GAN)'
authors = [
    'PHOENiX <rlaphoenix@pm.me>',
]
license = 'MIT'
readme = 'README.md'
homepage = 'https://github.com/rlaphoenix/vsgan'
repository = 'https://github.com/rlaphoenix/vsgan'
keywords = ['vapoursynth', 'upscaling', 'gan', 'deep-learning', 'esrgan']
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Topic :: Multimedia :: Video',
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
numpy = "^1.21.1"
VapourSynth = {version = "^57", optional = true}
torch = {version = "^1.10.0", optional = true}
Sphinx = {version = "^4.3.2", optional = true}
furo = {version = "^2021.11.23", optional = true}
dunamai = {version = "^1.7.0", optional = true}
m2r2 = {version = "^0.3.2", optional = true}
sphinxcontrib-youtube = {version = "^1.0.1", optional = true}
sphinxcontrib-images = {version = "^0.9.4", optional = true}

[tool.poetry.extras]
vs = ["VapourSynth"]
pytorch = ["torch"]
docs = ["Sphinx", "furo", "dunamai", "m2r2", "sphinxcontrib-youtube", "sphinxcontrib-images"]
