
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-26T12:16:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f53b40d263436a67c63f2e14ff305cbc8a9c871",
 "version": "4.9.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
