environment:
  matrix:
    - PYTHON: "C:\\Miniconda37"
      CONDA_PYTHON: "python=3.7"
    - PYTHON: "C:\\Miniconda37-x64"
      CONDA_PYTHON: "python=3.9"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library;%PYTHON%\\Library\\bin;%PYTHON%\\Library\\mingw-w64\\bin;%PATH%

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install %CONDA_PYTHON% numpy matplotlib jupyter
  - pip install -e .[tests]

build: false  # Not a C# project

test_script:
  - pytest nengo -v --durations=20
