
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-31T14:03:39-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b478462e683b97f1bb8d7254e611671572a254c",
 "version": "v0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
