- project:
    merge-mode: squash-merge
    default-branch: main
    templates:
      - publish-to-pypi
      - publish-otc-docs-pti
    check:
      jobs:
        - otc-tox-pep8
        - otc-tox-py39
    gate:
      jobs:
        - otc-tox-pep8
        - otc-tox-py39
