[tool.poetry]
name = "snapedautility"
version = "0.1.0"
description = "A package for doing great things!"
authors = ["Kyle Ahn"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
palmerpenguins = "^0.1.4"
altair = "^4.2.0"
numpy = "^1.22.1"
pandas = "^1.3.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
numpy = "^1.22.1"
pandas = "^1.3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
