[tool.poetry]
name = "rtvs-archiver"
version = "0.1.1"
description = ""
authors = ["Mathew Cohle <mathewcohle@protonmail.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/mathewcohle/rtvs-archiver"
repository = "https://github.com/mathewcohle/rtvs-archiver"

[tool.poetry.scripts]
rtvs_archiver = "rtvs_archiver.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"
requests = "^2.27.1"
lxml = "^4.7.1"
tqdm = "^4.62.3"
aiohttp = "^3.8.1"
pendulum = "^2.1.2"
aiofiles = "^0.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
