[tool.poetry]
name = "nonebot-plugin-heweather"
version = "0.5.1"
description = "Get Heweather information and convert to pictures"
authors = ["kexue <x@kexue.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.3,<4.0.0"
httpx = ">=0.18.0,<1.0.0"
nonebot-plugin-htmlrender = ">=0.0.4.1"
nonebot-adapter-onebot = {version = "2.0.0-beta.1", source = "aliyun"}

[tool.poetry.dev-dependencies]
black = {version = "^21.12b0", allow-prereleases = true}
nonebot2 = "2.0.0-beta.1"
pillow = {version = "^8.4.0", source = "aliyun"}

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
