[tool.poetry]
name = "jupyterbot"
version = "0.0.21"
description = ""
authors = [
"Johnata Brayan <johnatabrayan@gmail.com>", 
"Vinicius Mariano Gonçalves <vinicius.marianog@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
