[package]
name = "jsonschema-python"
version = "0.14.0"
authors = ["Dmitry Dygalo <dadygalo@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.rst"
description = "JSON schema validaton library"
repository = "https://github.com/Stranger6667/jsonschema-rs"
keywords = ["jsonschema", "validation"]
categories = ["web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "jsonschema_rs"
crate-type = ["cdylib"]

[build-dependencies]
built = { version = "0.5", features = ["chrono"] }

[dependencies.jsonschema]
path = "./jsonschema-lib"
version = "*"
default-features = false
features = ["resolve-http", "resolve-file"]

[dependencies]
serde_json = "1"
serde = "1"
pyo3 = { version = "^0.15", features = ["extension-module"] }
pyo3-built = "0.4"

[package.metadata.maturin]
requires-python = ">=3.6"
project-url = { repository = "https://github.com/Stranger6667/jsonschema-rs" }
maintainer = "Dmitry Dygalo"
maintainer-email = "Dmitry Dygalo <dadygalo@gmail.com>"
classifier = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
]

[profile.release]
codegen-units = 1
lto = "on"
