[tool.poetry]
name = "azure-telemetry"
version = "0.1.0"
description = "This package is used for mounting any kind of storage account into Databricks using keyvault and for general logging as well"
description-file =
    README.rst
description-content-type = text/x-rst
authors = ["RajamannarAanjaram <rajamannaraanjaram@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
opencensus-ext-azure = "^1.1.1"
opencensus-ext-requests = "^0.7.6"
msrestazure = "^0.6.4"
azure-mgmt-monitor = "^3.0.0"
azure-mgmt-datalake-analytics = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
