
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-28T15:00:10-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9ae0a1d7b380737b33ff10853fc4f1e58a7ee34",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
