# Generated by Django 3.2.5 on 2022-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_config', '0002_config_property_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config_property',
            options={'ordering': ['application', 'property_group', 'property_name']},
        ),
        migrations.AddField(
            model_name='config_property',
            name='property_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
