[tool.poetry]
name = "cloops"
version = "1.0.2"
description = "dfgdfg"
authors = ["Your Name <you@example.com>"]
license = "dsdfsdfsdf"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
