/* Generated by Nim Compiler v1.6.2 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw;
struct tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w {
NI64 ticks;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(void, tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ) (NU64* res);
struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw {
NI64 seconds;
NI nanosecond;
};
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, initDuration__pureZtimes_379)(NI64 nanoseconds, NI64 microseconds, NI64 milliseconds, NI64 seconds, NI64 minutes, NI64 hours, NI64 days, NI64 weeks);
N_LIB_PRIVATE N_NIMCALL(NI64, inNanoseconds__pureZtimes_697)(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw dur);
N_LIB_PRIVATE TNimType NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_;
extern TNimType NTIint5452__Aav8dQoMlCFnZRxA0IhTHQ_;
STRING_LITERAL(TM__IP4V1hRabVpf8OnX9bWuPxw_4, "kernel32", 8);
STRING_LITERAL(TM__IP4V1hRabVpf8OnX9bWuPxw_5, "kernel32", 8);
static void* TM__IP4V1hRabVpf8OnX9bWuPxw_2;
tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ Dl_1811939332_;
tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ Dl_1811939334_;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w, getMonoTime__stdZmonotimes_8)(void) {
	tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w result;
	NU64 ticks;
	NU64 freq;
	NU64 queryPerformanceCounterFreq;
	nimZeroMem((void*)(&result), sizeof(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w));
	ticks = (NU64)0;
	Dl_1811939332_((&ticks));
	freq = (NU64)0;
	Dl_1811939334_((&freq));
	queryPerformanceCounterFreq = (NU64)((NU64)(1000000000ULL) / (NU64)(freq));
	nimZeroMem((void*)(&result), sizeof(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w));
	result.ticks = ((NI64) ((NU64)((NU64)(ticks) * (NU64)(queryPerformanceCounterFreq))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lteq___stdZmonotimes_44)(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w a, tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w b) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (a.ticks <= b.ticks);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___stdZmonotimes_48)(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w a, tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w b) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (a.ticks == b.ticks);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt___stdZmonotimes_40)(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w a, tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w b) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (a.ticks < b.ticks);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, minus___stdZmonotimes_28)(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w a, tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w b) {
	tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw));
	result = initDuration__pureZtimes_379((NI64)(a.ticks - b.ticks), IL64(0), IL64(0), IL64(0), IL64(0), IL64(0), IL64(0), IL64(0));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w, plus___stdZmonotimes_32)(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w a, tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw b) {
	tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w result;
	tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w T1_;
	NI64 T2_;
	nimZeroMem((void*)(&result), sizeof(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w));
	nimZeroMem((void*)(&T1_), sizeof(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w));
	T2_ = (NI64)0;
	T2_ = inNanoseconds__pureZtimes_697(b);
	T1_.ticks = (NI64)(a.ticks + T2_);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_monotimesDatInit000)(void) {
static TNimNode TM__IP4V1hRabVpf8OnX9bWuPxw_0[1];
NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_.size = sizeof(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w);
NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_.align = NIM_ALIGNOF(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w);
NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_.kind = 18;
NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_.base = 0;
NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_.flags = 1;
TM__IP4V1hRabVpf8OnX9bWuPxw_0[0].kind = 1;
TM__IP4V1hRabVpf8OnX9bWuPxw_0[0].offset = offsetof(tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w, ticks);
TM__IP4V1hRabVpf8OnX9bWuPxw_0[0].typ = (&NTIint5452__Aav8dQoMlCFnZRxA0IhTHQ_);
TM__IP4V1hRabVpf8OnX9bWuPxw_0[0].name = "ticks";
NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_.node = &TM__IP4V1hRabVpf8OnX9bWuPxw_0[0];
if (!((TM__IP4V1hRabVpf8OnX9bWuPxw_2 = nimLoadLibrary(((NimStringDesc*) &TM__IP4V1hRabVpf8OnX9bWuPxw_4)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__IP4V1hRabVpf8OnX9bWuPxw_5));
	Dl_1811939332_ = (tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ) nimGetProcAddr(TM__IP4V1hRabVpf8OnX9bWuPxw_2, "QueryPerformanceCounter");
	Dl_1811939334_ = (tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ) nimGetProcAddr(TM__IP4V1hRabVpf8OnX9bWuPxw_2, "QueryPerformanceFrequency");
}

