
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-26T09:27:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b63a506caa2296e847ee47db8758db467c3a413",
 "version": "4.9.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
