# Generated by Django 3.1.5 on 2021-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0002_titlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Staff Type',
                'verbose_name_plural': 'Staff Types',
            },
        ),
    ]
