# Generated by Django 3.1.5 on 2021-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0006_auto_20210124_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveReasonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Passive Reason',
                'verbose_name_plural': 'Passive Reasons',
            },
        ),
    ]
