# Generated by Django 3.1.5 on 2021-05-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0008_passivestaffeventmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassiveStaffEventModel',
            new_name='PassiveStaffLogModel',
        ),
    ]
