# Generated by Django 3.2.11 on 2022-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0002_auto_20220118_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshhost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sshhost',
            name='private_key',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='私钥'),
        ),
        migrations.AddField(
            model_name='sshhost',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='标签分类'),
        ),
        migrations.AddField(
            model_name='sshhost',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='sshhost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
