# Generated by Django 3.2.11 on 2022-01-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtproxy', '0009_auto_20220119_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ovpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='[new ovpn]', max_length=64, null=True, verbose_name='备注')),
                ('host', models.CharField(default='[new]', max_length=64, verbose_name='服务器地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('protocol', models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp')], default='tcp', max_length=12, verbose_name='协议类型')),
            ],
            options={
                'verbose_name': 'OVPN',
                'verbose_name_plural': 'OVPN',
            },
        ),
        migrations.AlterModelOptions(
            name='portforward',
            options={'verbose_name': '端口转发', 'verbose_name_plural': '端口转发'},
        ),
    ]
