# Generated by Django 3.2.11 on 2022-01-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtproxy', '0010_auto_20220121_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovpn',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='ovpn',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ovpn',
            name='host',
            field=models.CharField(default='127.0.0.1', max_length=64, verbose_name='服务器地址'),
        ),
        migrations.AlterField(
            model_name='ovpn',
            name='port',
            field=models.IntegerField(default=1194, verbose_name='端口'),
        ),
    ]
