[tool.poetry]
name = "miguxespy"
version = "1.0.1"
description = "Modulo que traduz português para miguxês e suas variações (arcaico, moderno e NEO-miguxês). Inspirado no projeto de Aurelio Jargas, que pode ser encontrado em: https://aurelio.net/coisinha/miguxeitor"
authors = ["Matheus Alves <theustloz@gmail.com>"]

packages = [
    {include = "miguxes_py"}
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
