[build-system]
requires = ["flit_core >=3.5, <4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "intake_sdmx"
author = "dr-leo"
author-email = "fhaxbox66@gmail.com"
home-page = "https://github.com/dr-leo/pandasdmx"
dist-name = "intake_sdmx"
description-file = "README.rst"
requires = [
    "pandasdmx[cache] >= 1.7.0",
    "intake >= 0.6.5"]
requires-python = ">=3.7.8,<4"
keywords = "statistics, SDMX, intake, data, economics, science, plot"
classifiers = [
"Intended Audience :: Developers",
"Intended Audience :: Science/Research",
    "Intended Audience :: Financial and Insurance Industry",
"Development Status :: 4 - Beta",
"Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis",
"License :: OSI Approved :: Apache Software License"]

[tool.flit.metadata.requires-extra]  
doc = ["sphinx >= 3.4", 
"IPython"]
test = ["pytest >= 5"] 

[tool.flit.entrypoints."intake.drivers"]  
sdmx_sources = "intake_sdmx:SDMXSources"
sdmx_dataflows = "intake_sdmx:SDMXDataflows"
sdmx_data = "intake_sdmx:SDMXData" 

[tool.flit.metadata.urls]
Documentation = "https://intake_sdmx.readthedocs.io/"

[tool.flit.sdist]
include = ["LICENSE"]
