[tool.poetry]
name = "pyhof"
version = "0.1.3"
description = "Python High Order Functions library"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/PyGamer0/functools_plus"
repository = "https://github.com/PyGamer0/functools_plus"
authors = ["PyGamer0"]

[tool.poetry.dependencies]
python = ">3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
