# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import embedding_store_pb2 as proto_dot_embedding__store__pb2


class EmbeddingHubStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSpace = channel.unary_unary(
                '/embeddinghub.EmbeddingHub/CreateSpace',
                request_serializer=proto_dot_embedding__store__pb2.CreateSpaceRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__store__pb2.CreateSpaceResponse.FromString,
                )
        self.DeleteSpace = channel.unary_unary(
                '/embeddinghub.EmbeddingHub/DeleteSpace',
                request_serializer=proto_dot_embedding__store__pb2.DeleteSpaceRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__store__pb2.DeleteSpaceResponse.FromString,
                )
        self.Set = channel.unary_unary(
                '/embeddinghub.EmbeddingHub/Set',
                request_serializer=proto_dot_embedding__store__pb2.SetRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__store__pb2.SetResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/embeddinghub.EmbeddingHub/Get',
                request_serializer=proto_dot_embedding__store__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__store__pb2.GetResponse.FromString,
                )
        self.MultiSet = channel.stream_unary(
                '/embeddinghub.EmbeddingHub/MultiSet',
                request_serializer=proto_dot_embedding__store__pb2.MultiSetRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__store__pb2.MultiSetResponse.FromString,
                )
        self.MultiGet = channel.stream_stream(
                '/embeddinghub.EmbeddingHub/MultiGet',
                request_serializer=proto_dot_embedding__store__pb2.MultiGetRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__store__pb2.MultiGetResponse.FromString,
                )
        self.NearestNeighbor = channel.unary_unary(
                '/embeddinghub.EmbeddingHub/NearestNeighbor',
                request_serializer=proto_dot_embedding__store__pb2.NearestNeighborRequest.SerializeToString,
                response_deserializer=proto_dot_embedding__store__pb2.NearestNeighborResponse.FromString,
                )


class EmbeddingHubServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiSet(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiGet(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NearestNeighbor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSpace,
                    request_deserializer=proto_dot_embedding__store__pb2.CreateSpaceRequest.FromString,
                    response_serializer=proto_dot_embedding__store__pb2.CreateSpaceResponse.SerializeToString,
            ),
            'DeleteSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSpace,
                    request_deserializer=proto_dot_embedding__store__pb2.DeleteSpaceRequest.FromString,
                    response_serializer=proto_dot_embedding__store__pb2.DeleteSpaceResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=proto_dot_embedding__store__pb2.SetRequest.FromString,
                    response_serializer=proto_dot_embedding__store__pb2.SetResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=proto_dot_embedding__store__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_embedding__store__pb2.GetResponse.SerializeToString,
            ),
            'MultiSet': grpc.stream_unary_rpc_method_handler(
                    servicer.MultiSet,
                    request_deserializer=proto_dot_embedding__store__pb2.MultiSetRequest.FromString,
                    response_serializer=proto_dot_embedding__store__pb2.MultiSetResponse.SerializeToString,
            ),
            'MultiGet': grpc.stream_stream_rpc_method_handler(
                    servicer.MultiGet,
                    request_deserializer=proto_dot_embedding__store__pb2.MultiGetRequest.FromString,
                    response_serializer=proto_dot_embedding__store__pb2.MultiGetResponse.SerializeToString,
            ),
            'NearestNeighbor': grpc.unary_unary_rpc_method_handler(
                    servicer.NearestNeighbor,
                    request_deserializer=proto_dot_embedding__store__pb2.NearestNeighborRequest.FromString,
                    response_serializer=proto_dot_embedding__store__pb2.NearestNeighborResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embeddinghub.EmbeddingHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingHub(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddinghub.EmbeddingHub/CreateSpace',
            proto_dot_embedding__store__pb2.CreateSpaceRequest.SerializeToString,
            proto_dot_embedding__store__pb2.CreateSpaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddinghub.EmbeddingHub/DeleteSpace',
            proto_dot_embedding__store__pb2.DeleteSpaceRequest.SerializeToString,
            proto_dot_embedding__store__pb2.DeleteSpaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddinghub.EmbeddingHub/Set',
            proto_dot_embedding__store__pb2.SetRequest.SerializeToString,
            proto_dot_embedding__store__pb2.SetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddinghub.EmbeddingHub/Get',
            proto_dot_embedding__store__pb2.GetRequest.SerializeToString,
            proto_dot_embedding__store__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MultiSet(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/embeddinghub.EmbeddingHub/MultiSet',
            proto_dot_embedding__store__pb2.MultiSetRequest.SerializeToString,
            proto_dot_embedding__store__pb2.MultiSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MultiGet(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/embeddinghub.EmbeddingHub/MultiGet',
            proto_dot_embedding__store__pb2.MultiGetRequest.SerializeToString,
            proto_dot_embedding__store__pb2.MultiGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NearestNeighbor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeddinghub.EmbeddingHub/NearestNeighbor',
            proto_dot_embedding__store__pb2.NearestNeighborRequest.SerializeToString,
            proto_dot_embedding__store__pb2.NearestNeighborResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
