
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-27T19:21:24-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "11aa7a524dccefdbaef66de75a28a20a47878ff1",
 "version": "0.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
