[tool.poetry]
name = "graph-wrapper"
version = "1.3.0"
description = "Wrappers of popular network libraries with type annotation"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"
homepage = "https://github.com/binh-vu/graph"
packages = [
    { include = "graph" }
]

[tool.poetry.dependencies]
python = "^3.8"
retworkx = "^0.11.0"
typing_extensions = "^4.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
