[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sphinx_metavar"
authors = [{name = "Jean Abou-Samra", email = "jean@abou-samra.fr"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://gitlab.com/jeanas/sphinx-metavar"
