[tool.poetry]
name = "odin-bot-exchanges"
version = "0.7.2"
description = ""
authors = ["adolfrodeno <amvillalobos@uc.cl>"]

[tool.poetry.dependencies]
python = "^3.8"

python-dotenv = "^0.19.1"
odin-bot-entities = "^0.2.0"
binance-connector = "^1.9.0"
orionx-python-client = "^0.4.0"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
