
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-29T20:36:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "79b0f25133dbb8d7e7c1177bac50e6fefaf67ca5",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
