# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2022-01-28T20:16:57.710262'

__version__ = '2022.1.1'
__sha__ = 'dd19dc3453013503c2d1223b23838dec86ed6162'
__revision__ = 'dd19dc3453013503c2d1223b23838dec86ed6162'
