# Generated by Django 3.1.5 on 2021-01-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betik_app_staff', '0004_staffmodel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffmodel',
            index=models.Index(fields=['registration_number', 'start_date'], name='betik_app_s_registr_57c8af_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmodel',
            index=models.Index(fields=['start_date'], name='betik_app_s_start_d_65c228_idx'),
        ),
    ]
