
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-01T10:16:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "006d3d9a0e9208cff7a84e8c1642fdab662f4c3f",
 "version": "0.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
