
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-25T10:06:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1a3ad7c81f2cf9d482b2510473753904501e59d",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
