[tool.poetry]
name = "ip-reveal-headless"
version = "1.0.5"
description = "Quickly ascertain your public IP address, hostname, and local IP address."
authors = ["Taylor B. <tayjaybabee@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
humanize = "^3.1.0"
inspy_logger = "2.1a14"
inspyred_print = "^1.0"
python = "^3.8"
requests = "^2.25.0"
pypattyrn = "^1.2"
inspyre-toolbox = "^1.2a1"
toml = "^0.10.2"
johnnydep = "^1.10"
urllib3 = "^1.26.8"



[tool.poetry.dev-dependencies]
Sphinx = "^3.4.1"
changelog-generator = "^0.2.4"
pre-commit = "^2.15.0"
recommonmark = "^0.7.1"
PyFuncExtras = "^0.0.1"
ptipython = "^1.0.1"

[tool.poetry.scripts]
ip-reveal = 'ip_reveal_headless:main'
ip-reveal-headless = 'ip_reveal_headless:main'

[build-system]
requires = ["poetry-core>=0.12"]
build-backend = "poetry.core.masonry.api"
