/* Generated by Nim Compiler v1.6.2 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg;
typedef struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, tyProc__pduP3uOMtjDyYKG6z4GVFg) (NU64 opts, NU8 settings);
typedef N_CDECL_PTR(int, tyProc__cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef N_CDECL_PTR(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, tyProc__Rqjya8uauy9aPcyfGamaSrg) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* meth);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
NI32 errorCode;
};
struct tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg {
  tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA Sup;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
CRITICAL_SECTION lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef N_CDECL_PTR(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, tyProc__HXibadfWHwHwyhCwpIRD2A) (void);
typedef N_CDECL_PTR(unsigned long, tyProc__HBcM2Mt9bfW9bP8CkO25r0mA) (void);
typedef N_CDECL_PTR(NCSTRING, tyProc__ILGNrKdZ6rU9bHuzDylmHhA) (unsigned long e, NCSTRING buf);
typedef N_CDECL_PTR(int, tyProc__2PA7CxitARKs0jpUW1gQ0g) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* s, NCSTRING ciphers);
typedef N_CDECL_PTR(void, tyProc__IX9aeaSWx4arDCJq04EsJjQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING str);
typedef N_CDECL_PTR(long, tyProc__J5jVzoevP749cPcyUg9cwPEA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, int cmd, long larg, void* parg);
typedef N_CDECL_PTR(NI, tyProc__aF4y9aPKIi8D4VGrVvX011Q) (NI a, void* b);
typedef N_CDECL_PTR(void, tyProc__H5wL7jexPlRA7WCw9cqLm0A) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* s, NI mode, tyProc__aF4y9aPKIi8D4VGrVvX011Q cb);
typedef N_STDCALL_PTR(int, tyProc__tYatIIo0oRSB9bjHLep7yhQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING filename);
typedef N_CDECL_PTR(int, tyProc__xjxKRHVZXDqdWXw9bunoZ3w) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING filename, int typ);
typedef N_CDECL_PTR(int, tyProc__Vff1ipOwDPDGknaRJAdXjA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx);
typedef N_CDECL_PTR(int, tyProc__gZVmmOpGrWMJL1q0d9bMEZQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING CAfile, NCSTRING CApath);
typedef N_CDECL_PTR(void, tyProc__h4YRAkwlfyBfCYwRiY5JqA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* rbio, tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* wbio);
typedef N_CDECL_PTR(NI, tyProc__xGcw2zK9bzuUE9c8WzKW5hzw) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, int cmd, NI larg, void* parg);
typedef N_CDECL_PTR(void, tyProc__e47RoMUolEGMiUlfiZt9abQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* s);
typedef N_CDECL_PTR(int, tyProc__kxUw9cdxJbPtv0iPyoSbDBQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* s, int ret_code);
typedef N_CDECL_PTR(void, tyProc__v9chVxaoEEAWoxVjnpYxttA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, int mode);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_187)(NimStringDesc* name, NimStringDesc* alternativeName);
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_181)(void* dll, NimStringDesc* name, NimStringDesc* alternativeName);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_30)(void* lib, NCSTRING name);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(void*, thisModule__wrappersZopenssl_172)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_6)(void);
static N_INLINE(void*, sslModule__wrappersZopenssl_175)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern__pureZdynlib_49)(NimStringDesc* pattern, NIM_BOOL globalSymbols);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_191)(NimStringDesc* name, NimStringDesc* alternativeName);
__declspec(noreturn) N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidLibrary__pureZdynlib_9)(NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, loadPSSLMethod__wrappersZopenssl_199)(NimStringDesc* method1, NimStringDesc* method2);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5733)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5695)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5740)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5738)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5689)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_195)(NimStringDesc* name, NimStringDesc* alternativeName);
static N_INLINE(void*, utilModule__wrappersZopenssl_178)(void);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_2, "(libssl-1_1-x64|ssleay64|libssl64).dll", 38);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_3, "OPENSSL_init_ssl", 16);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_4, "SSL_library_init", 16);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_5, "SSL_load_error_strings", 22);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_8, "libcrypto-1_1-x64.dll", 21);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_10, "libeay64.dll", 12);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_11, "(libcrypto-1_1-x64|libeay64).dll", 32);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_14, "OPENSSL_add_all_algorithms_conf", 31);
N_LIB_PRIVATE TNimType NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_;
N_LIB_PRIVATE TNimType NTIsslptr__QQ33RYEe889cv60wm9bVkd8A_;
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_17, "libssl-1_1-x64.dll", 18);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "ssleay64.dll", 12);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_21, "libssl64.dll", 12);
extern TNimType NTIreflibraryerror__HV2B9a6TW6WPpQna2mQFeQQ_;
extern TNimType NTIlibraryerror__x1muge9crz9aAVqWWUrEL9aXg_;
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "Could not load ", 15);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_25, " nor ", 5);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_26, "SSLv23_method", 13);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_27, "TLS_method", 10);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_36, "OpenSSL_version_num", 19);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_37, "SSLeay", 6);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_38, "SSL_CTX_set_ciphersuites", 24);
N_LIB_PRIVATE void* thisMod__wrappersZopenssl_174;
N_LIB_PRIVATE void* sslMod__wrappersZopenssl_177;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_6;
tyProc__ln4kdL5W9bbX4a1xl8nnVXQ Dl_1912602975_;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_15;
tyProc__Rqjya8uauy9aPcyfGamaSrg Dl_1912602991_;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5632;
tyProc__HBcM2Mt9bfW9bP8CkO25r0mA Dl_1912603104_;
tyProc__ILGNrKdZ6rU9bHuzDylmHhA Dl_1912603100_;
tyProc__HXibadfWHwHwyhCwpIRD2A Dl_1912602795_;
tyProc__2PA7CxitARKs0jpUW1gQ0g Dl_1912603008_;
N_LIB_PRIVATE void* utilMod__wrappersZopenssl_180;
N_LIB_PRIVATE tyProc__IX9aeaSWx4arDCJq04EsJjQ theProc__wrappersZopenssl_338;
tyProc__J5jVzoevP749cPcyUg9cwPEA Dl_1912603165_;
tyProc__H5wL7jexPlRA7WCw9cqLm0A Dl_1912602999_;
tyProc__tYatIIo0oRSB9bjHLep7yhQ Dl_1912603015_;
tyProc__xjxKRHVZXDqdWXw9bunoZ3w Dl_1912603018_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_1912603022_;
tyProc__gZVmmOpGrWMJL1q0d9bMEZQ Dl_1912602993_;
tyProc__Rqjya8uauy9aPcyfGamaSrg Dl_1912602976_;
tyProc__Rqjya8uauy9aPcyfGamaSrg Dl_1912603233_;
tyProc__HXibadfWHwHwyhCwpIRD2A Dl_1912603237_;
tyProc__h4YRAkwlfyBfCYwRiY5JqA Dl_1912603264_;
tyProc__xGcw2zK9bzuUE9c8WzKW5hzw Dl_1912603178_;
tyProc__e47RoMUolEGMiUlfiZt9abQ Dl_1912603248_;
tyProc__ln4kdL5W9bbX4a1xl8nnVXQ Dl_1912603270_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_1912603268_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_1912603238_;
tyProc__xjxKRHVZXDqdWXw9bunoZ3w Dl_1912603240_;
tyProc__kxUw9cdxJbPtv0iPyoSbDBQ Dl_1912603057_;
tyProc__xjxKRHVZXDqdWXw9bunoZ3w Dl_1912603244_;
tyProc__v9chVxaoEEAWoxVjnpYxttA Dl_1912603042_;
tyProc__xjxKRHVZXDqdWXw9bunoZ3w Dl_1912603260_;
tyProc__xjxKRHVZXDqdWXw9bunoZ3w Dl_1912603252_;
N_LIB_PRIVATE N_NIMCALL(void, CRYPTO_malloc_init__wrappersZopenssl_540)(void) {
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void*, thisModule__wrappersZopenssl_172)(void) {
	void* result;
	result = (void*)0;
	{
		if (!(thisMod__wrappersZopenssl_174 == 0)) goto LA3_;
		thisMod__wrappersZopenssl_174 = loadLib__pureZdynlib_6();
	}
	LA3_: ;
	result = thisMod__wrappersZopenssl_174;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_181)(void* dll, NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
{	result = (void*)0;
	{
		if (!!((dll == 0))) goto LA3_;
		result = symAddr__pureZdynlib_30(dll, nimToCStringConv(name));
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = (result == 0);
			if (!(T7_)) goto LA8_;
			T7_ = (((NI) 0) < (alternativeName ? alternativeName->Sup.len : 0));
			LA8_: ;
			if (!T7_) goto LA9_;
			result = symAddr__pureZdynlib_30(dll, nimToCStringConv(alternativeName));
		}
		LA9_: ;
	}
	LA3_: ;
	{
		void* thisDynlib;
		if (!(result == 0)) goto LA13_;
		thisDynlib = thisModule__wrappersZopenssl_172();
		{
			if (!(thisDynlib == 0)) goto LA17_;
			result = NIM_NIL;
			goto BeforeRet_;
		}
		LA17_: ;
		result = symAddr__pureZdynlib_30(thisDynlib, nimToCStringConv(name));
		{
			NIM_BOOL T21_;
			T21_ = (NIM_BOOL)0;
			T21_ = (result == 0);
			if (!(T21_)) goto LA22_;
			T21_ = (((NI) 0) < (alternativeName ? alternativeName->Sup.len : 0));
			LA22_: ;
			if (!T21_) goto LA23_;
			result = symAddr__pureZdynlib_30(thisDynlib, nimToCStringConv(alternativeName));
		}
		LA23_: ;
	}
	LA13_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void*, sslModule__wrappersZopenssl_175)(void) {
	void* result;
	result = (void*)0;
	{
		if (!(sslMod__wrappersZopenssl_177 == 0)) goto LA3_;
		sslMod__wrappersZopenssl_177 = loadLibPattern__pureZdynlib_49(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_2), NIM_FALSE);
	}
	LA3_: ;
	result = sslMod__wrappersZopenssl_177;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_187)(NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = sslModule__wrappersZopenssl_175();
	result = symNullable__wrappersZopenssl_181(T1_, name, alternativeName);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_191)(NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
	result = (void*)0;
	result = sslSymNullable__wrappersZopenssl_187(name, alternativeName);
	{
		if (!(result == 0)) goto LA3_;
		raiseInvalidLibrary__pureZdynlib_9(nimToCStringConv(name));
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_library_init__wrappersZopenssl_225)(void) {
	int result;
	void* newInitSym;
	tyProc__cez8YhJI0vaCUcjGg6z4zA olderProc;
	void* T5_;
{	result = (int)0;
	newInitSym = sslSymNullable__wrappersZopenssl_187(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_3), ((NimStringDesc*) NIM_NIL));
	{
		tyProc__pduP3uOMtjDyYKG6z4GVFg newInitProc;
		if (!!((newInitSym == 0))) goto LA3_;
		newInitProc = ((tyProc__pduP3uOMtjDyYKG6z4GVFg) (newInitSym));
		result = newInitProc(0ULL, ((NU8) 0));
		goto BeforeRet_;
	}
	LA3_: ;
	T5_ = (void*)0;
	T5_ = sslSymThrows__wrappersZopenssl_191(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_4), ((NimStringDesc*) NIM_NIL));
	olderProc = ((tyProc__cez8YhJI0vaCUcjGg6z4zA) (T5_));
	{
		if (!!((olderProc == 0))) goto LA8_;
		result = olderProc();
	}
	LA8_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, SSL_load_error_strings__wrappersZopenssl_255)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc;
	void* T1_;
	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_187(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_5), ((NimStringDesc*) NIM_NIL));
	theProc = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	{
		if (!!((theProc == 0))) goto LA4_;
		theProc();
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, OpenSSL_add_all_algorithms__wrappersZopenssl_284)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc;
	void* T1_;
	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_187(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_14), ((NimStringDesc*) NIM_NIL));
	theProc = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	{
		if (!!((theProc == 0))) goto LA4_;
		theProc();
	}
	LA4_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5733)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5695)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5738)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5689((&gch__system_5632.zct), c);
}
static N_INLINE(void, decRef__system_5740)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5738(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5695(src);
		incRef__system_5733(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5695((*dest));
		decRef__system_5740(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, loadPSSLMethod__wrappersZopenssl_199)(NimStringDesc* method1, NimStringDesc* method2) {
	tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* result;
	void* methodSym;
	tyProc__HXibadfWHwHwyhCwpIRD2A method2Proc;
{	result = (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*)0;
	methodSym = sslSymNullable__wrappersZopenssl_187(method1, method2);
	{
		tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg* T5_;
		NimStringDesc* T6_;
		if (!(methodSym == 0)) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg*) newObj((&NTIreflibraryerror__HV2B9a6TW6WPpQna2mQFeQQ_), sizeof(tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIlibraryerror__x1muge9crz9aAVqWWUrEL9aXg_);
		(*T5_).Sup.Sup.Sup.name = "LibraryError";
		T6_ = NIM_NIL;
		T6_ = rawNewString((method1 ? method1->Sup.len : 0) + (method2 ? method2->Sup.len : 0) + 20);
appendString(T6_, ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_24));
appendString(T6_, method1);
appendString(T6_, ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_25));
appendString(T6_, method2);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.message), T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "LibraryError", "loadPSSLMethod", "openssl.nim", 367);
	}
	LA3_: ;
	method2Proc = ((tyProc__HXibadfWHwHwyhCwpIRD2A) (methodSym));
	result = method2Proc();
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, SSLv23_method__wrappersZopenssl_272)(void) {
	tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* result;
	result = (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*)0;
	result = loadPSSLMethod__wrappersZopenssl_199(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_26), ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_27));
	return result;
}
static N_INLINE(void*, utilModule__wrappersZopenssl_178)(void) {
	void* result;
	result = (void*)0;
	{
		if (!(utilMod__wrappersZopenssl_180 == 0)) goto LA3_;
		utilMod__wrappersZopenssl_180 = loadLibPattern__pureZdynlib_49(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_11), NIM_FALSE);
	}
	LA3_: ;
	result = utilMod__wrappersZopenssl_180;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_195)(NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = utilModule__wrappersZopenssl_178();
	result = symNullable__wrappersZopenssl_181(T1_, name, alternativeName);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long, getOpenSSLVersion__wrappersZopenssl_290)(void) {
	unsigned long result;
	tyProc__HBcM2Mt9bfW9bP8CkO25r0mA theProc;
	void* T1_;
	result = (unsigned long)0;
	T1_ = (void*)0;
	T1_ = utilSymNullable__wrappersZopenssl_195(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_36), ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_37));
	theProc = ((tyProc__HBcM2Mt9bfW9bP8CkO25r0mA) (T1_));
	{
		if (!(theProc == 0)) goto LA4_;
		result = ((unsigned long) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		result = theProc();
	}
	LA2_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_CTX_set_ciphersuites__wrappersZopenssl_331)(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING str) {
	int result;
	result = (int)0;
	{
		void* T5_;
		if (!(theProc__wrappersZopenssl_338 == 0)) goto LA3_;
		T5_ = (void*)0;
		T5_ = sslSymThrows__wrappersZopenssl_191(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_38), ((NimStringDesc*) NIM_NIL));
		theProc__wrappersZopenssl_338 = ((tyProc__IX9aeaSWx4arDCJq04EsJjQ) (T5_));
	}
	LA3_: ;
	theProc__wrappersZopenssl_338(ctx, str);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, SSLCTXSetMode__wrappersZopenssl_550)(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NI mode) {
	NI result;
	long T1_;
	result = (NI)0;
	T1_ = (long)0;
	T1_ = Dl_1912603165_(ctx, ((int) 33), ((long) (mode)), NIM_NIL);
	result = ((NI) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, SSL_set_tlsext_host_name__wrappersZopenssl_559)(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, NCSTRING name) {
	NI result;
	result = (NI)0;
	result = Dl_1912603178_(ssl, ((int) 55), ((NI) 0), ((void*) (name)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_opensslDatInit000)(void) {
static TNimNode TM__SLGpYVEqpFQ7VaPsJH6HIA_0[1];
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.size = sizeof(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw);
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.align = NIM_ALIGNOF(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw);
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.kind = 18;
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.base = 0;
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.flags = 1;
TM__SLGpYVEqpFQ7VaPsJH6HIA_0[0].len = 0; TM__SLGpYVEqpFQ7VaPsJH6HIA_0[0].kind = 2;
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.node = &TM__SLGpYVEqpFQ7VaPsJH6HIA_0[0];
NTIsslptr__QQ33RYEe889cv60wm9bVkd8A_.size = sizeof(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*);
NTIsslptr__QQ33RYEe889cv60wm9bVkd8A_.align = NIM_ALIGNOF(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*);
NTIsslptr__QQ33RYEe889cv60wm9bVkd8A_.kind = 21;
NTIsslptr__QQ33RYEe889cv60wm9bVkd8A_.base = (&NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_);
NTIsslptr__QQ33RYEe889cv60wm9bVkd8A_.flags = 3;
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_6 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_8)))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_6 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_10)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_11));
	Dl_1912602975_ = (tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "ERR_load_BIO_strings");
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_15 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_17)))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_15 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_19)))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_15 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_21)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_2));
	Dl_1912602991_ = (tyProc__Rqjya8uauy9aPcyfGamaSrg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_new");
	Dl_1912603104_ = (tyProc__HBcM2Mt9bfW9bP8CkO25r0mA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "ERR_peek_last_error");
	Dl_1912603100_ = (tyProc__ILGNrKdZ6rU9bHuzDylmHhA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "ERR_error_string");
	Dl_1912602795_ = (tyProc__HXibadfWHwHwyhCwpIRD2A) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "TLSv1_method");
	Dl_1912603008_ = (tyProc__2PA7CxitARKs0jpUW1gQ0g) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_set_cipher_list");
	Dl_1912603165_ = (tyProc__J5jVzoevP749cPcyUg9cwPEA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_ctrl");
	Dl_1912602999_ = (tyProc__H5wL7jexPlRA7WCw9cqLm0A) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_set_verify");
	Dl_1912603015_ = (tyProc__tYatIIo0oRSB9bjHLep7yhQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_use_certificate_chain_file");
	Dl_1912603018_ = (tyProc__xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_use_PrivateKey_file");
	Dl_1912603022_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_check_private_key");
	Dl_1912602993_ = (tyProc__gZVmmOpGrWMJL1q0d9bMEZQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_CTX_load_verify_locations");
	Dl_1912602976_ = (tyProc__Rqjya8uauy9aPcyfGamaSrg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_new");
	Dl_1912603233_ = (tyProc__Rqjya8uauy9aPcyfGamaSrg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "BIO_new");
	Dl_1912603237_ = (tyProc__HXibadfWHwHwyhCwpIRD2A) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "BIO_s_mem");
	Dl_1912603264_ = (tyProc__h4YRAkwlfyBfCYwRiY5JqA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_set_bio");
	Dl_1912603178_ = (tyProc__xGcw2zK9bzuUE9c8WzKW5hzw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_ctrl");
	Dl_1912603248_ = (tyProc__e47RoMUolEGMiUlfiZt9abQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_set_connect_state");
	Dl_1912603270_ = (tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "ERR_clear_error");
	Dl_1912603268_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_do_handshake");
	Dl_1912603238_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "BIO_ctrl_pending");
	Dl_1912603240_ = (tyProc__xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "BIO_read");
	Dl_1912603057_ = (tyProc__kxUw9cdxJbPtv0iPyoSbDBQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_get_error");
	Dl_1912603244_ = (tyProc__xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, "BIO_write");
	Dl_1912603042_ = (tyProc__v9chVxaoEEAWoxVjnpYxttA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_set_shutdown");
	Dl_1912603260_ = (tyProc__xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_write");
	Dl_1912603252_ = (tyProc__xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_15, "SSL_read");
}

