pipeline_name: scania_truck_fault_pipeline.pickle
train_batch_files: scania_truck_air_presure_fault_detector/train_batch_raw_files
test_batch_files: ml_api/prediction_batch_raw_files
validated_files: scania_truck_air_presure_fault_detector/validated_files
test_validated_files: ml_api/validated_files
train_db_path: scania_truck_air_presure_fault_detector/train_data/data.db
test_db_path: ml_api/data/data.db
train_data: scania_truck_air_presure_fault_detector/train_data/data.csv
test_data: ml_api/data/data.csv
train_query: scania_truck_air_presure_fault_detector/db_operations/train.sql
test_query: data/prediction.sql
kmeans_model_path: kmeans.pickle

random_state: 42
test_size: 0.33
cv: 2
sample_file_name: ApsFailure_08012020_120000.csv
length_0f_date_stamp_in_file: 8
length_0f_time_stamp_in_file: 6
number_of_columns : 171
unwanted_features:
  - cd_000
  - ch_000
  - ab_000
  - as_000
  - cd_000
  - cr_000
  - ef_000
  - bn_000
  - bo_000
  - bp_000
  - bq_000
  - br_000

target: class
features:
  - aa_000
  - ab_000
  - ac_000
  - ad_000
  - ae_000
  - af_000
  - ag_000
  - ag_001
  - ag_002
  - ag_003
  - ag_004
  - ag_005
  - ag_006
  - ag_007
  - ag_008
  - ag_009
  - ah_000
  - ai_000
  - aj_000
  - ak_000
  - al_000
  - am_0
  - an_000
  - ao_000
  - ap_000
  - aq_000
  - ar_000
  - as_000
  - at_000
  - au_000
  - av_000
  - ax_000
  - ay_000
  - ay_001
  - ay_002
  - ay_003
  - ay_004
  - ay_005
  - ay_006
  - ay_007
  - ay_008
  - ay_009
  - az_000
  - az_001
  - az_002
  - az_003
  - az_004
  - az_005
  - az_006
  - az_007
  - az_008
  - az_009
  - ba_000
  - ba_001
  - ba_002
  - ba_003
  - ba_004
  - ba_005
  - ba_006
  - ba_007
  - ba_008
  - ba_009
  - bb_000
  - bc_000
  - bd_000
  - be_000
  - bf_000
  - bg_000
  - bh_000
  - bi_000
  - bj_000
  - bk_000
  - bl_000
  - bm_000
  - bn_000
  - bo_000
  - bp_000
  - bq_000
  - br_000
  - bs_000
  - bt_000
  - bu_000
  - bv_000
  - bx_000
  - by_000
  - bz_000
  - ca_000
  - cb_000
  - cc_000
  - cd_000
  - ce_000
  - cf_000
  - cg_000
  - ch_000
  - ci_000
  - cj_000
  - ck_000
  - cl_000
  - cm_000
  - cn_000
  - cn_001
  - cn_002
  - cn_003
  - cn_004
  - cn_005
  - cn_006
  - cn_007
  - cn_008
  - cn_009
  - co_000
  - cp_000
  - cq_000
  - cr_000
  - cs_000
  - cs_001
  - cs_002
  - cs_003
  - cs_004
  - cs_005
  - cs_006
  - cs_007
  - cs_008
  - cs_009
  - ct_000
  - cu_000
  - cv_000
  - cx_000
  - cy_000
  - cz_000
  - da_000
  - db_000
  - dc_000
  - dd_000
  - de_000
  - df_000
  - dg_000
  - dh_000
  - di_000
  - dj_000
  - dk_000
  - dl_000
  - dm_000
  - dn_000
  - do_000
  - dp_000
  - dq_000
  - dr_000
  - ds_000
  - dt_000
  - du_000
  - dv_000
  - dx_000
  - dy_000
  - dz_000
  - ea_000
  - eb_000
  - ec_00
  - ed_000
  - ee_000
  - ee_001
  - ee_002
  - ee_003
  - ee_004
  - ee_005
  - ee_006
  - ee_007
  - ee_008
  - ee_009
  - ef_000
  - eg_000

logistic_regression_params:
  logistic__solver:
    - newton-cg
    - lbfgs
    - liblinear
  logistic__penalty:
    - l2
  logistic__C:
    - 100.0
    - 10.0
    - 1.0
    - 0.1
    - 0.01

random_forest_params:
  random_forest__n_estimators: 
    - 150
    - 300
    - 600
  random_forest__min_samples_leaf:
    - 2
    - 3  
  random_forest__min_samples_split:
    - 14
    - 12
  random_forest__max_features:
    - 0.7
    - 1.0
  random_forest__criterion: 
    - gini 
    - entropy

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Scania Truck
  run_name: scania_truck
  registered_model_name: model_
  remote_server_uri: http://mlflow:1234
