
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-30T18:23:33-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa0492da95dd495df1ee7a9ddf31d7274b647c26",
 "version": "2.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
